CityOfZion/neo3-boa

.gitignore
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3_test/example/if_test/ElseWithoutBody.py
boa3_test/example/if_test/IfElif.py
boa3_test/example/if_test/IfExpVariableCondition.py
boa3_test/example/if_test/IfExpWithoutElse.py
boa3_test/example/if_test/IfWithoutBody.py
boa3_test/tests/test_if.py

- Implemented else branch to if statement implemented in #10
- Implemented if expressions. If expressions must have both if and else branches.
Ex: `1 if True else 2`.
- `elif` branches will be implemented in another issue.

Convert If Else statement

---

boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3/model/builtin/decorator/builtindecorator.py
boa3/model/builtin/decorator/publicdecorator.py
boa3/model/builtin/method/builtinmethod.py
boa3/model/builtin/method/lenmethod.py
boa3/model/method.py
boa3_test/example/generation_test/GenerationWithDecorator.py
boa3_test/example/generation_test/GenerationWithoutDecorator.py
boa3_test/tests/test_file_generation.py

- Created a decorator to identify which methods should be included in the `abi` field of the manifest.
For example, in the smart contract below, only the `Main` method will be included in the abi
```python
@public
def Main(operation: str, args: Tuple[int]) -> int
return foo(args[0])
def foo(bar: int) -> int
return bar
```

Include 'public' annotation to methods that should be added to the ABI

---

boa3/analyser/analyser.py
boa3/analyser/constructanalyser.py
boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/exception/CompilerWarning.py
boa3/helpers/__init__.py
boa3/model/method.py
boa3/model/module.py
boa3/model/symbol.py
boa3/model/type/itype.py
boa3/model/variable.py
boa3/neo/vm/type/Integer.py
boa3_test/example/for_test/ForElse.py
boa3_test/example/for_test/MismatchedTypeCondition.py
boa3_test/example/for_test/NestedFor.py
boa3_test/example/for_test/NoCondition.py
boa3_test/example/for_test/StringCondition.py
boa3_test/example/for_test/TupleCondition.py
boa3_test/example/for_test/VariableCondition.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_for.py
boa3_test/tests/test_if.py
boa3_test/tests/test_while.py

- Implemented `for` statements that use a tuple or a variable as its iterator.
If the iterator type is not a sequence, a compiler error will be raised.
- String iteration is not implemented yet, so using a string value in the `for` statement is going to raise an exception.
- The keywords `continue`, `break` and `pass` are not implemented in this issue.

Convert For statement

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/compiler/filegenerator.py
boa3/model/method.py
boa3/model/type/booltype.py
boa3/model/type/inttype.py
boa3/model/type/nonetype.py
boa3/model/type/strtype.py
boa3/model/type/tupletype.py
boa3/neo/vm/VMCode.py
boa3_test/example/function_test/CallFunctionWrittenBefore.py
boa3_test/example/function_test/CallReturnFunctionOnReturn.py
boa3_test/example/function_test/CallReturnFunctionWithLiteralArgs.py
boa3_test/example/function_test/CallReturnFunctionWithVariableArgs.py
boa3_test/example/function_test/CallReturnFunctionWithoutArgs.py
boa3_test/example/function_test/CallVoidFunctionWithLiteralArgs.py
boa3_test/example/function_test/CallVoidFunctionWithVariableArgs.py
boa3_test/example/function_test/CallVoidFunctionWithoutArgs.py
boa3_test/example/generation_test/GenerationWithoutMain.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_function.py

- Implemented user-created function calls.
- Converts the function calls independently of the order of the functions. Converts both:
```python
def Main(a: int, b: int) -> int:
return Add(a, b)
def Add(a: int, b: int) -> int:
return a + b
```
and
```python
def Add(a: int, b: int) -> int:
return a + b
def Main(a: int, b: int) -> int:
return Add(a, b)
```
- Raise a compiler error if there's no main method.

Convert Function call

---

boa3/analyser/astanalyser.py
boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/model/variable.py
boa3_test/example/variable_test/MismatchedTypeAssignBinOp.py
boa3_test/example/variable_test/MismatchedTypeAssignMixedOp.py
boa3_test/example/variable_test/MismatchedTypeAssignSequenceGet.py
boa3_test/example/variable_test/MismatchedTypeAssignSequenceSet.py
boa3_test/example/variable_test/MismatchedTypeAssignUnOp.py
boa3_test/example/variable_test/MismatchedTypeAssignValue.py
boa3_test/example/variable_test/MismatchedTypeAugAssign.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_for.py
boa3_test/tests/test_variable.py

- Implemented type checking on variables assignments.
Since Neo VM is based on C#, some opcodes only work with specific types. For preventing weird behavior, neo-boa checks variable types on compile-time.
Because of this, the type of a variable can't be changed once defined, unlike standard Python.
- Variable declarations without type hint are only allowed if it is an assignment. In this case, the variable type will be the same as the assigned value type.

 Type check values in variable assignment

---

README.md
boa3/analyser/typeanalyser.py
boa3_test/example/arithmetic_test/MultipleExpressionsInLine.py
boa3_test/example/list_test/MultipleExpressionsInLine.py
boa3_test/example/logical_test/MultipleExpressionsInLine.py
boa3_test/example/relational_test/MultipleExpressionsInLine.py
boa3_test/example/tuple_test/MultipleExpressionsInLine.py
boa3_test/tests/test_multiple_expressions.py

Because of the way the Python abstract syntax tree is built, multiple expressions written in the same line were already converted correctly.
I included some unit tests to make sure that the expressions in the same line are working as expected.

Convert multiple expressions in same line

---

boa3/analyser/astanalyser.py
boa3/analyser/constructanalyser.py
boa3/analyser/moduleanalyser.py
boa3/model/type/anytype.py
boa3/model/type/genericsequencetype.py
boa3/model/type/listtype.py
boa3/model/type/sequencetype.py
boa3/model/type/tupletype.py
boa3/model/type/type.py
boa3_test/example/any_test/AnyList.py
boa3_test/example/any_test/AnySequenceAssignments.py
boa3_test/example/any_test/AnyTuple.py
boa3_test/example/any_test/AnyVariableAssignments.py
boa3_test/example/any_test/FunctionAnyParam.py
boa3_test/example/any_test/IntSequenceAnyAssignment.py
boa3_test/example/any_test/OperationWithAny.py
boa3_test/example/any_test/SequenceOfAnyIntSequence.py
boa3_test/example/any_test/SequenceOfAnySequence.py
boa3_test/example/any_test/SequenceOfIntSequence.py
boa3_test/example/any_test/StrSequenceAnyAssignment.py
boa3_test/example/any_test/StrSequenceStrAssignment.py
boa3_test/example/any_test/VariableAssignmentWithAny.py
boa3_test/example/list_test/Nep5Main.py
boa3_test/example/tuple_test/Nep5Main.py
boa3_test/tests/test_any.py
boa3_test/tests/test_types.py

Included `Any` type to identify which variables can be assigned to multiple values or if a function returns different type values.
In the current implementation of neo-boa, the following statement would cause a compiler error:
```python
a = 1
a = '2'  # raises an error
```
because the variable type is defined as the type of the first value assigned to it. In this case, the type of `a` is `int` and the error occurs when a non-`int` value is assigned to this variable.
But if the variable is explicitly defined with `Any` type, both assignments are allowed:
```python
a: Any = 1
a = '2'  # it doesn't raise an error
```
Currently, `Any` values cannot be used with typed operations without casting.
Type casting is not implemented yet.

Implement Any type

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/model/operation/binary/arithmetic/addition.py
boa3/model/operation/binary/arithmetic/floordivision.py
boa3/model/operation/binary/arithmetic/modulo.py
boa3/model/operation/binary/arithmetic/multiplication.py
boa3/model/operation/binary/arithmetic/strmultiplication.py
boa3/model/operation/binary/arithmetic/subtraction.py
boa3/model/operation/binary/logical/booleanand.py
boa3/model/operation/binary/logical/booleanor.py
boa3/model/operation/binary/relational/LessThan.py
boa3/model/operation/binary/relational/Lessthanorequal.py
boa3/model/operation/binary/relational/greaterthan.py
boa3/model/operation/binary/relational/greaterthanorequal.py
boa3/model/operation/binary/relational/numericequality.py
boa3/model/operation/binary/relational/numericinequality.py
boa3/model/operation/binary/relational/objectequality.py
boa3/model/operation/binary/relational/objectinequality.py
boa3/model/operation/binaryop.py
boa3/model/operation/operation.py
boa3/model/operation/unary/booleannot.py
boa3/model/operation/unary/negative.py
boa3/model/operation/unary/noneidentity.py
boa3/model/operation/unary/nonenotidentity.py
boa3/model/operation/unary/positive.py
boa3/neo/vm/VMCode.py
boa3_test/example/arithmetic_test/ConcatenationAugmentedAssignment.py
boa3_test/example/arithmetic_test/StringMultiplication.py
boa3_test/example/arithmetic_test/StringMultiplicationAugmentedAssignment.py
boa3_test/tests/test_arithmetic.py

- Implemented string arithmetic operators:
- String concatenation:
```
a = 'str1'
b = 'str2'
c = a + b
```
- String shallow copy:
```
a = 'str'
b = a * 3  # result: 'strstrstr'
```
- Also implemented these operators on augmented assignments:
```
a = 'str1'
b = 'str2'
a += b  # same as a = a + b
b *= 5  # same as b = b * 5
```

Convert string arithmetic operations

---

boa3/compiler/codegenerator.py
boa3/model/type/sequence/tupletype.py
boa3/neo/vm/opcode/Opcode.py
boa3/neo/vm/opcode/OpcodeInfo.py
boa3/neo/vm/opcode/OpcodeInformation.py
boa3_test/example/list_test/GetValueNegativeIndex.py
boa3_test/example/list_test/SetValueNegativeIndex.py
boa3_test/tests/test_for.py
boa3_test/tests/test_list.py
boa3_test/tests/test_multiple_expressions.py
boa3_test/tests/test_string.py
boa3_test/tests/test_tuple.py

Implemented Python feature of getting or setting a value from a sequence with negative index:
```
a = [1, 2, 3]
b = a[-1]  # get last from a
c = a[-4]  # get the position len(a) - 4, which is invalid
```

Sequence get and set with negative index

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/type/itype.py
boa3/model/type/primitive/booltype.py
boa3/model/type/primitive/bytestype.py
boa3/model/type/primitive/inttype.py
boa3/model/type/primitive/strtype.py
boa3/model/type/sequence/genericsequencetype.py
boa3/model/type/sequence/mutable/genericmutablesequencetype.py
boa3/model/type/sequence/sequencetype.py
boa3/model/type/type.py
boa3_test/example/built_in_methods_test/LenBytes.py
boa3_test/example/bytes_test/GetValue.py
boa3_test/example/bytes_test/GetValueNegativeIndex.py
boa3_test/example/bytes_test/LiteralBytes.py
boa3_test/example/bytes_test/SetValue.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_constant.py
boa3_test/tests/test_function.py
boa3_test/tests/test_if.py

- Implemented conversion of literal `bytes`
- Implemented `get` to bytes indexes. Python's `bytes` object does not support item assignment
- Implemented bytes `len()` method.

Convert Bytes type

---

boa3/analyser/typeanalyser.py
boa3/exception/CompilerError.py
boa3_test/example/function_test/CallFunctionWithoutVariables.py
boa3_test/example/function_test/CallFunctionWrittenBefore.py
boa3_test/example/function_test/DefaultReturn.py
boa3_test/example/function_test/ReturnElifMissing.py
boa3_test/example/function_test/ReturnElseMissing.py
boa3_test/example/function_test/ReturnFor.py
boa3_test/example/function_test/ReturnForElseMissing.py
boa3_test/example/function_test/ReturnForOnlyOnElse.py
boa3_test/example/function_test/ReturnIf.py
boa3_test/example/function_test/ReturnIfMissing.py
boa3_test/example/function_test/ReturnMultipleInnerIf.py
boa3_test/example/function_test/ReturnMultipleInnerIfMissing.py
boa3_test/example/function_test/ReturnWhile.py
boa3_test/example/function_test/ReturnWhileOnlyOnElse.py
boa3_test/example/function_test/ReturnWhileWithoutElse.py
boa3_test/tests/test_function.py
requirements.txt
setup.py

- Include a compiler error when the return statement is missing in functions with return type hint
- In #38 it was implemented the inclusion of a default return for this case. As [discussed](https://github.com/CityOfZion/neo3-boa/pull/38#issuecomment-644782772), it was changed to force the user to write all the returns if the return type is specified.
```
def example(a: int) -> int:
if a > 10:
return a
```

Include compiler error when missing return

---

boa3/analyser/importanalyser.py
boa3/neo3/core/cryptography/ecc.py

Using Python 3.8 shows the following warnings when trying to use the `neo3-boa`  CLI
```bash
(venv) eriks-MacBook-Pro:neo3-boa erik$ neo3-boa
/Users/erik/Documents/code/neo3-boa/boa3/analyser/importanalyser.py:22: SyntaxWarning: "is" with a literal. Did you mean "=="?
if import_target is 'typing':
/Users/erik/Documents/code/neo3-boa/boa3/neo3/core/cryptography/ecc.py:717: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if ysquare_root % 2 is not 0:
usage: neo3-boa [-h] input
neo3-boa: error: the following arguments are required: input
```

Resolve py38 SyntaxWarnings

---

boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/method.py
boa3_test/example/generation_test/GenerationWithoutMainAndPublicMethods.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_function.py

In the latest version of Neo, the `entryPoint` field of the manifest was removed.
The former `entryPoint` it's now included in the `methods` field.

Remove entrypoint field from the manifest

---

boa3/analyser/moduleanalyser.py
boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3_test/example/metadata_test/MetadataInfoAuthor.py
boa3_test/example/metadata_test/MetadataInfoAuthorMismatchedType.py
boa3_test/example/metadata_test/MetadataInfoDescription.py
boa3_test/example/metadata_test/MetadataInfoDescriptionMismatchedType.py
boa3_test/example/metadata_test/MetadataInfoEmail.py
boa3_test/example/metadata_test/MetadataInfoEmailMismatchedType.py
boa3_test/example/metadata_test/MetadataInfoExtras.py
boa3_test/example/metadata_test/MetadataInfoMultipleMethod.py
boa3_test/tests/test_metadata.py

- Included additional information into the metadata object to be included in the `extra` field of the manifest.
Included data about the smart contract:
https://github.com/CityOfZion/neo3-boa/blob/d25eec059859baf7bf70413e99173b4c5dbeb5b7/boa3/builtin/__init__.py#L28-L33
The new attributes are all optional. If none of them is updated, the `extra` field in the manifest will be `null`, as default.

Change metadata to define manifest 'extra' field information

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegeneratorvisitor.py
boa3/compiler/filegenerator.py
boa3/exception/CompilerError.py
boa3/model/method.py
boa3_test/example/metadata_test/MetadataInfoPayableIncorrectVerify.py
boa3_test/example/metadata_test/MetadataInfoPayableMissingVerify.py
boa3_test/example/metadata_test/MetadataInfoPayablePrivateVerify.py
boa3_test/tests/test_metadata.py

A payable smart contract must have a `verify` function.
If `verify` is not implemented or if its signature isn't correct the compiler will raise an error.
The `verify` function must implement the following signature:
```python
@public
def verify() -> bool
```
- `verify` can have arguments as well, but they're not been checked in this pull request. It will be implemented when the stared parameters (`*args`) is implemented

Include limitations when a smart contract is payable

---

boa3/analyser/moduleanalyser.py
boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/clearmethod.py
boa3_test/example/built_in_methods_test/ClearMutableSequence.py
boa3_test/example/built_in_methods_test/ClearMutableSequenceBuiltinCall.py
boa3_test/example/built_in_methods_test/ClearTooFewParameters.py
boa3_test/example/built_in_methods_test/ClearTooManyParameters.py
boa3_test/example/built_in_methods_test/ClearTuple.py
boa3_test/example/bytes_test/BytearrayClear.py
boa3_test/example/bytes_test/BytesClear.py
boa3_test/example/list_test/ClearList.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_list.py

Implemented Python `list` clear function
```
a: List[int] = [1, 2, 3]
a.clear()
a = [1, 2]
list.clear(a)
a = [3, 2, 1]
MutableSequence.clear(a)
b = bytearray(b'\x01\x02\x03')
b.clear()  # bytearray clear function is not implemented yet
```

Convert list clear method

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3_test/example/dict_test/EmptyDictAssignment.py
boa3_test/example/list_test/EmptyListAssignment.py
boa3_test/example/tuple_test/EmptyTupleAssignment.py
boa3_test/tests/test_dict.py
boa3_test/tests/test_list.py
boa3_test/tests/test_tuple.py

Fixed an error that was raised when assigning an empty collection to a typed collection.
```python
empty_list: List[int] = []
empty_tuple: Tuple[str] = ()
empty_dict: Dict[str, int] = {}
```

Typed collection assign error

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/reversemethod.py
boa3_test/example/built_in_methods_test/ReverseMutableSequence.py
boa3_test/example/built_in_methods_test/ReverseMutableSequenceBuiltinCall.py
boa3_test/example/built_in_methods_test/ReverseTooFewParameters.py
boa3_test/example/built_in_methods_test/ReverseTooManyParameters.py
boa3_test/example/built_in_methods_test/ReverseTuple.py
boa3_test/example/bytes_test/BytearrayReverse.py
boa3_test/example/bytes_test/BytesReverse.py
boa3_test/example/list_test/ReverseList.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_list.py

Implemented Python `reverse` function to `list` and `bytearray` types
```
a: List[int] = [1, 2, 3]
a.reverse()  # a = [3, 2, 1]
b = [1, 2]
list.reverse(b)  # b = [2, 1]
c = [3, 2, 1]
MutableSequence.reverse(c)  # c = [1, 2, 3]
d = bytearray(b'\x01\x02\x03')
d.reverse()  # d = bytearray(b'\x03\x02\x01')
```

Convert list reverse method

---

boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/builtin/classmethod/appendmethod.py
boa3/model/builtin/method/builtinmethod.py
boa3/neo/vm/opcode/Opcode.py
boa3/neo/vm/opcode/OpcodeInfo.py
boa3_test/example/bytes_test/BytearrayAppendWithBuiltin.py
boa3_test/example/bytes_test/BytearrayAppendWithMutableSequence.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_function.py
boa3_test/tests/test_list.py

Implemented Python `bytearray` append function
```
a = bytearray(b'\x01\x02\x03')
a.append(4)
bytearray.append(a, 5)
MutableSequence.append(a, 6)
a.append('7')  # compiler error - the list is defined as a list of ints and here it's trying to append a non-int value
```

Convert bytearray append method

---

boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/compiler/filegenerator.py
boa3/constants.py
boa3/helpers/__init__.py
boa3/model/callable.py
boa3/model/expression.py
boa3/model/importsymbol.py
boa3/model/module.py
boa3/model/variable.py
boa3/neo3/contracts/nef.py
boa3_test/example/import_test/FromImportTyping.py
boa3_test/example/import_test/FromImportVariable.py
boa3_test/example/import_test/FromImportWithGlobalVariables.py
boa3_test/example/variable_test/AssignLocalWithArgumentShadowingGlobal.py
boa3_test/example/variable_test/GetGlobalValueWrittenAfter.py
boa3_test/example/variable_test/GlobalAssignmentBetweenFunctions.py
boa3_test/example/variable_test/GlobalAssignmentInFunctionWithArgument.py
boa3_test/example/variable_test/GlobalAssignmentWithTuples.py
boa3_test/example/variable_test/GlobalAssignmentWithType.py
boa3_test/example/variable_test/GlobalAssignmentWithoutType.py
boa3_test/example/variable_test/GlobalDeclarationWithArgumentWrittenAfter.py
boa3_test/example/variable_test/GlobalDeclarationWithoutAssignment.py
boa3_test/example/variable_test/ManyGlobalAssignments.py
boa3_test/tests/test_constant.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_import.py
boa3_test/tests/test_variable.py

Implemented variable declarations and assignments outside the scope of a function
```
from typing import Any
owner: bytes = b'\x01\x02\x03'
empty_bytes = b''
def Main(operation: str) -> Any:
if operation == 'owner':
return owner
return empty_bytes
```
- Variables outside functions must be initialized with a value.
```
var_1: int
var_2: str
def foo() -> int:
return var_1
var_1 = 10
```

Convert Static Variable Declarations and Assignments

---

boa3/analyser/typeanalyser.py
boa3/compiler/filegenerator.py
boa3/model/builtin/classmethod/appendmethod.py
boa3/model/builtin/classmethod/clearmethod.py
boa3/neo3/contracts/nef.py
boa3_test/example/bytes_test/BytearrayClear.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_function.py
boa3_test/tests/test_list.py
boa3_test/tests/test_tuple.py

Implemented Python `bytearray` clear function
```
a = bytearray(b'\x01\x02\x03')
b = bytearray(b'\x03\x02\x01')
c = bytearray(b'\x0a\x0b\x0c')
a.clear()
MutableSequence.clear(b)
bytearray.clear(c)
```

Convert bytearray clear method

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtincallable.py
boa3/model/builtin/classmethod/mapkeysmethod.py
boa3/model/builtin/classmethod/mapvaluesmethod.py
boa3/model/builtin/decorator/builtindecorator.py
boa3/model/builtin/interop/interopevent.py
boa3/model/builtin/interop/interopmethod.py
boa3/model/builtin/interop/runtime/checkwitnessmethod.py
boa3/model/builtin/interop/runtime/logmethod.py
boa3/model/builtin/interop/runtime/triggermethod.py
boa3/model/builtin/interop/storage/storagedeletemethod.py
boa3/model/builtin/interop/storage/storagegetmethod.py
boa3/model/builtin/interop/storage/storageputmethod.py
boa3/model/builtin/method/builtinevent.py
boa3/model/builtin/method/builtinmethod.py
boa3/model/builtin/method/bytearraymethod.py
boa3/model/builtin/method/lenmethod.py
boa3/model/callable.py
boa3/model/event.py
boa3/model/method.py
boa3_test/example/function_test/CallFunctionWithKwargs.py
boa3_test/example/function_test/FunctionWithDefaultArgument.py
boa3_test/example/function_test/FunctionWithDefaultArgumentBetweenArgs.py
boa3_test/example/function_test/FunctionWithOnlyDefaultArguments.py
boa3_test/tests/test_function.py

Implemented default arguments to functions
```python
def example(a: int = 0, b: int = 0, c: int = 0) -> int:
return a + b + c
...
add()
add(5, 6)
add(9)
add(1, 2, 3)
```
This is only implemented to functions call inside the same smart contract for now

Function default argument

---

boa3/analyser/constructanalyser.py
boa3/analyser/typeanalyser.py
boa3/builtin/__init__.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/toscripthashmethod.py
boa3/model/type/primitive/booltype.py
boa3/model/type/primitive/bytestype.py
boa3/model/type/primitive/inttype.py
boa3/model/type/primitive/primitivetype.py
boa3/model/type/primitive/strtype.py
boa3_test/example/built_in_methods_test/ScriptHashBuiltinMismatchedType.py
boa3_test/example/built_in_methods_test/ScriptHashInt.py
boa3_test/example/built_in_methods_test/ScriptHashIntBuiltinCall.py
boa3_test/example/built_in_methods_test/ScriptHashMismatchedType.py
boa3_test/example/built_in_methods_test/ScriptHashStr.py
boa3_test/example/built_in_methods_test/ScriptHashStrBuiltinCall.py
boa3_test/example/built_in_methods_test/ScriptHashTooFewParameters.py
boa3_test/example/built_in_methods_test/ScriptHashTooManyParameters.py
boa3_test/example/built_in_methods_test/ScriptHashVariable.py
boa3_test/example/built_in_methods_test/ScriptHashVariableBuiltinCall.py
boa3_test/tests/test_builtin_method.py

Implemented a function to convert bytes, string and int values to a script hash value
```python
number_1_script: bytes = 1.to_script_hash()
number_2_script: bytes = int.to_script_hash(1)
string_script: bytes = 'str'.to_script_hash()
bytes_script: bytes = bytes.to_script_hash(b'\x01\x02\x03')
one = 1
script = one.to_script_hash()  # this function only works with literal values
```

Implement toScriptHash()

---

boa3/neo/__init__.py
boa3_test/tests/test_constant.py
requirements.txt

Fixed `to_script_hash()` result when converting account address strings
```python
addr1_script_hash = 'Nd7eAuHsKvvzHzSPyuJQALcYCcUrcwvm5W'.to_script_hash()
addr2_script_hash = str.to_script_hash('NPHivMjKsez5Z8opCkTUr5r8Uqk9uW6sif')
```

Fix address string to ScriptHash

---

boa3/analyser/typeanalyser.py
boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/tointmethod.py
boa3/neo/__init__.py
boa3_test/example/bytes_test/BytearrayToInt.py
boa3_test/example/bytes_test/BytearrayToIntWithBuiltin.py
boa3_test/example/bytes_test/BytearrayToIntWithBytesBuiltin.py
boa3_test/example/bytes_test/BytesToInt.py
boa3_test/example/bytes_test/BytesToIntWithBuiltin.py
boa3_test/example/bytes_test/BytesToIntWithBuiltinMismatchedTypes.py
boa3_test/example/bytes_test/BytesToIntWithBytearrayBuiltin.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_tuple.py

Implemented the conversion from bytes values to int values, using `little` byteroder
```python
x: int = b'\x01\x02'.to_int()  # expect 512
b = bytearray(b'\x01\x02\x03')
y: int = bytes.to_int(b)  # expect 197121
```

Implement bytes.to_int()

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/tobytesmethod.py
boa3_test/example/built_in_methods_test/IntToBytes.py
boa3_test/example/built_in_methods_test/IntToBytesWithBuiltin.py
boa3_test/example/built_in_methods_test/ToBytesMismatchedType.py
boa3_test/tests/test_builtin_method.py

Implemented the conversion from int values to bytes values, using `little` byteorder
```python
x1: bytes = (123).to_bytes()  # expected b'\x7b' = b'{'
x2: int = x1.to_int()  # expected 123
y: bytes = int.to_bytes(345)  # expected b'\x59\x01' = b'Y\x01'
```

Implement int.to_bytes()

---

boa3/compiler/codegenerator.py
boa3/neo/vm/type/Integer.py
boa3_test/tests/test_constant.py

Fixed a conversion error of integer values. Values that fills the bytes were been converting incorrectly
```python
x = 10_000_000  # this now is converted to b'\x80\x96\x98\x00'
y = -6_777_216
```

Fix error when inserting integer values

---

boa3/analyser/importanalyser.py
boa3/analyser/typeanalyser.py
boa3/model/builtin/classmethod/tobytesmethod.py
boa3_test/test_sc/built_in_methods_test/StrToBytes.py
boa3_test/test_sc/built_in_methods_test/StrToBytesWithBuiltin.py
boa3_test/tests/test_builtin_method.py

Implemented the conversion from str values to bytes values, using `utf-8` encoding
```python
x1: bytes = '123'.to_bytes()  # expected b'123'
x2: str = x1.to_str()  # expected '123'
y: bytes = str.to_bytes('abc')  # expected b'abc'
```

Implement str.to_bytes()

---

boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/extendmethod.py
boa3/model/builtin/classmethod/popmethod.py
boa3_test/test_sc/list_test/PopList.py
boa3_test/test_sc/list_test/PopListLiteralArgument.py
boa3_test/test_sc/list_test/PopListLiteralNegativeArgument.py
boa3_test/test_sc/list_test/PopListMismatchedTypeArgument.py
boa3_test/test_sc/list_test/PopListMismatchedTypeResult.py
boa3_test/test_sc/list_test/PopListTooManyArguments.py
boa3_test/test_sc/list_test/PopListVariableArgument.py
boa3_test/test_sc/list_test/PopListWithoutAssignment.py
boa3_test/tests/test_any.py
boa3_test/tests/test_constant.py
boa3_test/tests/test_exception.py
boa3_test/tests/test_function.py
boa3_test/tests/test_list.py
boa3_test/tests/test_while.py

Implemented pop method for `list` values
```python
from typing import List
def Main(op: str, args: list) -> List[str]:
a = ['1', '2', '3', '4', '5']
b = a.pop(4)  # removes '5' and assigns it to b
c = a.pop(-2)  # removes '3' and assigns it to c
d = a.pop()  # removes '4' and assigns it to d
return a  # expected ['1', '2']
```

Convert list pop method

---

boa3/analyser/importanalyser.py
boa3/compiler/compiler.py
boa3_test/test_sc/import_test/ImportNonExistantPackage.py
boa3_test/tests/test_exception.py
boa3_test/tests/test_import.py

When trying to import a non-existent package, the compiler was raising an exception.
Changed to log `UnresolvedReference`:

Fix error when using a non-existent import

---

boa3/analyser/astanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/compiler/vmcodemapping.py
boa3/exception/CompilerWarning.py
boa3/neo/vm/TryCode.py
boa3/neo/vm/VMCode.py
boa3/neo/vm/opcode/Opcode.py
boa3/neo/vm/opcode/OpcodeInfo.py
boa3_test/test_sc/exception_test/TryExceptBaseException.py
boa3_test/test_sc/exception_test/TryExceptFinally.py
boa3_test/test_sc/exception_test/TryExceptSpecificException.py
boa3_test/test_sc/exception_test/TryExceptWithName.py
boa3_test/test_sc/exception_test/TryExceptWithoutException.py
boa3_test/tests/test_exception.py

- Implemented try-exception statements
```python
def foo(bar: int) -> int:
try:
x = may_raise_exception(bar)
except Exception:
x = bar
return x
```
- `finally` statements are not implemented yet
- Currently, all exceptions are raised as `Exception`, so any specific exception in the `except` statement will be converted to `Exception`:
```python
def foo(bar: int) -> int:
try:
x = may_raise_exception(bar)
except AttributeError:
x = bar
return x
```
- Multiple `except` statements to the same `try` body are not implemented yet:
```python
def foo(bar: int) -> int:
try:
x = may_raise_exception(bar)
except AttributeError:
x = bar
except BaseException:
x = bar * 2
return x
```

Implement try except

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/model/method.py
boa3_test/test_sc/variable_test/GlobalAssignmentInFunctionWithArgument.py
boa3_test/tests/test_variable.py

- Implemented `global` keyword, to update external variables inside functions
```python
x = 10
def increase1():
global x  # it's using the external x instead of creating a local x
x += 1
```

Implement global keyword

---

README.md

- fix typo's in comment
- remove `json` code block identifier as it shows as red errors. Given that it previously only highlighted the `true` word, we don't really lose any highlighting
Old view

update neo debugger JSON of the readme

---

boa3/analyser/builtinfunctioncallanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/isinstancemethod.py
boa3/model/identifiedsymbol.py
boa3_test/test_sc/built_in_methods_test/IsInstanceBoolLiteral.py
boa3_test/test_sc/built_in_methods_test/IsInstanceBoolVariable.py
boa3_test/test_sc/built_in_methods_test/IsInstanceIntLiteral.py
boa3_test/test_sc/built_in_methods_test/IsInstanceIntVariable.py
boa3_test/test_sc/built_in_methods_test/IsInstanceListLiteral.py
boa3_test/test_sc/built_in_methods_test/IsInstanceManyTypes.py
boa3_test/test_sc/built_in_methods_test/IsInstanceStrLiteral.py
boa3_test/test_sc/built_in_methods_test/IsInstanceStrVariable.py
boa3_test/test_sc/built_in_methods_test/IsInstanceTupleLiteral.py
boa3_test/test_sc/built_in_methods_test/IsInstanceTupleVariable.py
boa3_test/test_sc/built_in_methods_test/IsInstanceVariableType.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_none.py

Implemented `isinstance` builtin method:
```python
def foo(bar: Any) -> bool:
return isinstance(bar, (int, str))
```
- Didn't implement type validation with `isinstance` method. So methods like:
```python
def foo(bar: Any) -> int:
if isinstance(bar, int):
return bar
else:
return 0
```
won't compile because the variable `bar` is not interpreted as an `int` value even after `isinstance` returns True. That'll be implemented when reassigning types to existing variables is implemented.

Implement isinstance function

---

boa3/analyser/builtinfunctioncallanalyser.py
boa3/model/builtin/interop/storage/storagegetmethod.py
boa3/model/builtin/method/isinstancemethod.py
boa3_test/tests/test_storage.py

The method was returning `None` when the key doesn't exist in the storage. Changed to return an empty `bytes`
```python
def main() -> bytes:
key = 'unknown_key'
return get(key)  # expected b''
```

Update Storage Get interop to return an empty bytearray when the key doesn't exist

---

boa3/analyser/optimizer/Operation.py
boa3/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/callmethod.py
boa3/model/builtin/interop/contract/getgasscripthashmethod.py
boa3/model/builtin/interop/contract/getneoscripthashmethod.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/method/rangemethod.py
boa3_test/test_sc/interop_test/CallScriptHash.py
boa3_test/test_sc/interop_test/CallScriptHashTooFewArguments.py
boa3_test/test_sc/interop_test/CallScriptHashTooManyArguments.py
boa3_test/test_sc/interop_test/CallScriptHashWithoutArgs.py
boa3_test/test_sc/interop_test/GasScriptHash.py
boa3_test/test_sc/interop_test/NeoScriptHash.py
boa3_test/tests/test_interop.py
setup.py

Implemented the `Contrac.Call` interop. Now it's possible to call other smart contracts from the ones compiled with neo3-boa
```python
from typing import Any
from boa3.builtin.interop.contract import NEO, call_contract
sample_script_hash = b'0123456789abcdefghij'
def example() -> Any:
result = call_contract(sample_script_hash, 'example', [1, 2])
if result is None:
return b''
else:
return result
def neo_balance(address: bytes) -> Any:
if len(address) != 20:
return None
balance = call_contract(NEO, 'balanceOf', [address])
if isinstance(balance, int):
return balance
else:
return 0
```

Implement smart contract call Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/getblocktimemethod.py
boa3_test/test_sc/interop_test/BlockTime.py
boa3_test/test_sc/interop_test/BlockTimeCantAssign.py
boa3_test/tests/test_interop.py

Implemented `Runtime.GetTime` interop to get blockchain's last block timestamp.
```python
from boa3.builtin.interop.runtime import get_time
def example() -> int:
return get_time
```

Implement Runtime Time Interop

---

boa3/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/getcurrentheightmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/CallingScriptHashCantAssign.py
boa3_test/test_sc/interop_test/CurrentHeight.py
boa3_test/test_sc/interop_test/CurrentHeightCantAssign.py
boa3_test/test_sc/interop_test/GasScriptHashCantAssign.py
boa3_test/test_sc/interop_test/NeoScriptHashCantAssign.py
boa3_test/tests/test_interop.py

Implemented `Blockchain.GetHeight` interop to get blockchain's current block height.
```python
from boa3.builtin.interop.blockchain import current_height
def example() -> int:
return current_height
```

Implement Height Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/getgasleftmethod.py
boa3_test/test_sc/interop_test/GasLeft.py
boa3_test/test_sc/interop_test/GasLeftCantAssign.py
boa3_test/tests/test_interop.py

Implemented `Runtime.GasLeft` interop to get smart contracts' invoker remaining gas.
```python
from boa3.builtin.interop.runtime import gas_left
def has_gas() -> bool:
return gas_left > 0
```

Implement Runtime GasLeft Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/getinvocationcountermethod.py
boa3_test/test_sc/interop_test/InvocationCounter.py
boa3_test/test_sc/interop_test/InvocationCounterCantAssign.py
boa3_test/tests/test_interop.py

Implemented `Runtime.GetInvocationCounter` interop.
```python
from boa3.builtin.interop.runtime import invocation_counter
def example():
invocations: int = invocation_counter
```

Implement Runtime InvocationCounter Interop

---

.circleci/config.yml

Included the installation of the TestEngine in the CircleCI's unit test flow.
Also, changed the Python version in the unit tests to 3.8.0 instead of the latest

Include TestEngine installation in the dependencies

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/toscripthashmethod.py
boa3_test/test_sc/built_in_methods_test/ScriptHashVariable.py
boa3_test/test_sc/built_in_methods_test/ScriptHashVariableBuiltinCall.py
boa3_test/tests/test_builtin_method.py

Change the to_script_hash implementation to allow it to be used inside functions and with variables
```
from boa3.builtin import to_script_hash
def foo():
address1: bytes = 'NPHivMjKsez5Z8opCkTUr5r8Uqk9uW6sif'.to_scrip_hash()
address2: bytes = str.to_script_hash('Nd7eAuHsKvvzHzSPyuJQALcYCcUrcwvm5W')
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4a73b056f1879cac6834c4743220899c457d874c/boa3_test/tests/test_builtin_method.py#L587-L704

Boa-128 Implement bytes toScriptHash() with Neo opcodes

---

boa3_test/test_sc/interop_test/CallScriptHash.py
boa3_test/test_sc/interop_test/CallScriptHashWithoutArgs.py
boa3_test/test_sc/list_test/IntList.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_interop.py
boa3_test/tests/test_list.py

Implemented the option to include other smart contracts in the TestEngine to tests that require calling other contracts.
```
engine = TestEngine(self.dirname)
engine.add_contract(call_contract_path)
result = self.run_smart_contract(engine, path, 'Main', call_hash, 'method', args)
self.assertEqual(expected_output, result)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/733e8a4495d0b439fcecf36bce02105ce4f2f1b4/boa3_test/tests/test_interop.py#L319-L337
https://github.com/CityOfZion/neo3-boa/blob/733e8a4495d0b439fcecf36bce02105ce4f2f1b4/boa3_test/tests/test_interop.py#L356-L370

Boa-260 Include other smart contracts in the TestEngine (neo3-boa)

---

boa3/builtin/interop/crypto/__init__.py
boa3/model/builtin/interop/crypto/verifywithecdsasecp256k1.py
boa3/model/builtin/interop/crypto/verifywithecdsasecp256r1.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256k1Bool.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256k1Bytes.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256k1Int.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256k1MismatchedType.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256k1Str.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256r1Bool.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256r1Bytes.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256r1Int.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256r1MismatchedType.py
boa3_test/test_sc/interop_test/VerifyWithECDsaSecp256r1Str.py
boa3_test/tests/test_interop.py

#114 
Implemented the Verify Interop 
Call verify_with_ecdsa_secp256r1 or verify_with_ecdsa_secp256k1
**Tests**
Unit tests are in located at boa3_test/tests/test_interop.py
**Platform:**
- Python version Python 3.7.9

Boa-83 Implement Verify Interop

---

boa3/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/base64decodemethod.py
boa3/model/builtin/interop/binary/base64encodemethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/Base64Decode.py
boa3_test/test_sc/interop_test/Base64DecodeMismatchedType.py
boa3_test/test_sc/interop_test/Base64Encode.py
boa3_test/test_sc/interop_test/Base64EncodeMismatchedType.py
boa3_test/tests/test_interop.py

#114
Implemented Base64 Interop
Step to reproduce the behaviour:
Call either base64_encode() or base64_decode()
**Tests**
It was tested using the test engine
**Platform:**
- Version: neo3-boa v0.5
- Python version: Python 3.7.9

Boa-223 Implement Base64 Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/getexecutingscripthashmethod.py
boa3_test/test_sc/interop_test/ExecutingScriptHash.py
boa3_test/test_sc/interop_test/ExecutingScriptHashCantAssign.py
boa3_test/tests/test_interop.py

#114 
Implemented ExecutingScriptHash Interop.
Assign executing_script_hash to a variable
**Tests**
Unit tests located at boa3/model/builtin/interop/interop.py
**Platform:**
- Python version Python 3.7.9

Boa-219 Implement Runtime ExecutingScriptHash Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/getentryscripthashmethod.py
boa3_test/test_sc/interop_test/EntryScriptHash.py
boa3_test/test_sc/interop_test/EntryScriptHashCantAssign.py
boa3_test/tests/test_interop.py

#114 
Implemented EntryScriptHash Interop
Call entry_script_hash.
**Tests**
Tested it using Opcode
**Platform:**
- Python version e.g. Python 3.8

Boa-221 Implement Runtime EntryScriptHash Interop

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/getplatformmethod.py
boa3_test/test_sc/interop_test/GetPlatform.py
boa3_test/test_sc/interop_test/GetPlatformCantAssign.py
boa3_test/tests/test_interop.py

#114 
Implemented Platform interop.
Use get_platform.
**Tests**
Used Opcode and Test engine.
**Platform:**

Boa-199 Implement Runtime Platform Interop

---

boa3/compiler/filegenerator.py
boa3/neo/__init__.py
boa3_test/test_sc/interop_test/CheckWitness.py
boa3_test/test_sc/interop_test/CheckWitnessImportedAs.py
boa3_test/test_sc/interop_test/DestroyContractTooManyArguments.py
boa3_test/test_sc/interop_test/UpdateContractTooManyArguments.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_interop.py

Included in the TestEngine the signing tests for testing ``check_witness``
```python
engine = TestEngine(self.dirname)
engine.add_signer_account(account)
result = self.run_smart_contract(engine, path, 'check_witness', account)
self.assertEqual(True, result)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c9e596a7d2b62cff50acbf57700a98fd2663fd43/boa3_test/tests/test_interop.py#L20-L46

Boa-283 Include CheckWitness in neo-boa's TestEngine

---

.gitignore
boa3/builtin/interop/contract/__init__.py
boa3/builtin/interop/contract/contract.py
boa3/model/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/contracttype.py
boa3/model/builtin/interop/contract/createmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/CreateContract.py
boa3_test/tests/test_interop.py

#114 
Changed Create Contract interop implementation, now it's returning a Contract class and it's attributes are a script and a manifest.
Call create_contract().
**Tests**
Using Opcode and Test engine.
**Platform:**

Boa-277 Change Create Contract interop implementation

---

boa3/builtin/interop/json/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/json/__init__.py
boa3/model/builtin/interop/json/jsondeserializemethod.py
boa3/model/builtin/interop/json/jsonserializemethod.py
boa3_test/test_sc/interop_test/JsonDeserialize.py
boa3_test/test_sc/interop_test/JsonSerialize.py
boa3_test/test_sc/interop_test/JsonSerializeBool.py
boa3_test/test_sc/interop_test/JsonSerializeBytes.py
boa3_test/test_sc/interop_test/JsonSerializeInt.py
boa3_test/test_sc/interop_test/JsonSerializeStr.py
boa3_test/tests/test_interop.py

#114 
Implemented JsonSerialize and JsonDeserialize interops
Call json_serialize or json_deserialize.
**Tests**
Tested json_serialize and json_deserialize with the TestEngine
**Platform:**

Boa-206 Implement Json Interops

---

boa3/builtin/contract/__init__.py
boa3/model/builtin/builtin.py
boa3/model/builtin/contract/abortmethod.py
boa3_test/test_sc/boa_built_in_methods_test/Abort.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_boa_builtin_method.py

#114 
Created abort(), a smart contract method, that uses Opcode.ABORT
Call abort()
**Tests**
Tested it using the test engine
**Platform:**

Boa-290 Create an abort method that uses Opcode.ABORT

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegeneratorvisitor.py
boa3_test/test_sc/bytes_test/AssignSlice.py
boa3_test/test_sc/relational_test/ListEqualityWithSlice.py
boa3_test/test_sc/string_test/GetValueToVariable.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_relational.py
boa3_test/tests/test_string.py

Fixed the type checking when using slices
```python 
@public
def main(a: bytearray) -> bytearray:
m = a[1:2]
return m
```
Instead of associating ``m`` with a ``bytearray`` variable, it was associating with ``int``
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bf5372e23129409cebc727287a05a372b50a5b8e/boa3_test/tests/test_bytes.py#L223-L236

Boa-279 Fix get type from slices

---

boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/if_test/InnerIfElse.py
boa3_test/tests/test_function.py
boa3_test/tests/test_if.py

Fixed the bug with multiple if-else branches inside of each other. The compiled smart contract wasn't following the same execution flow as expected.
```python
if a > b:
if c > d:
m = 3
else:
if b > c:
m =8
else:
m =10
else:
if c > d:
m = 1
else:
if b < c:
m = 11
else:
m = 22
```
**Tests**
Included a new unit test for testing the execution of issue
https://github.com/CityOfZion/neo3-boa/blob/b43d17bee348a3c4741351886ec61cd632b2c185/boa3_test/tests/test_if.py#L335-L356

Boa-281 Fix if else jumps when inside an if body

---

boa3/analyser/moduleanalyser.py
boa3_test/test_sc/for_test/ForIterateDict.py
boa3_test/tests/test_for.py

Fixed a bug related to the type checking of for statement's variable
```python
j = 20
d = {
'a': 1,
'b': 4,
4: 'blah',
'm': j,
'z': [1, 3, 4, 5, 'abcd', j]
}
output = ''
for item in d.keys():
output += item
```
In this code, ``d`` is evaluated as ``Dict[Any, Any]`` and consequently ``d.keys()`` is ``Sequence[Any]``. 
neo3-boa doesn't allow the + operator between ``str`` and ``Any``, so the instruction ``output += item`` should raise an error, but the smart contract with this piece of code was being successfully compiled
**Tests**
Created a unit test expecting a ``MismatchedTypes`` to be raised. Before the changes, this unit test would fail
https://github.com/CityOfZion/neo3-boa/blob/6fdda74eb51549b30e5d9d8a85719e9011f23269/boa3_test/ …

Boa-288 Fix Type checking bug with for variable

---

.circleci/config.yml
.gitignore
boa3/builtin/interop/contract/contract.py
boa3/compiler/compiler.py
boa3/compiler/filegenerator.py
boa3/model/builtin/interop/contract/contracttype.py
boa3/neo/contracts/neffile.py
boa3/neo3/contracts/nef.py
boa3_test/test_sc/class_test/ContractConstructor.py
boa3_test/tests/neo/smart_contract/test_neffile.py
boa3_test/tests/test_class.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_interop.py
boa3_test/tests/test_neo_types.py

Changed manifest and nef implementation to be compatible with the upcoming neo preview 4
**Tests**:
Tested all the unit tests using the most recent version of TestEngine, which uses a Neo version updated with manifest and nef changes

Boa-293 Make manifest and nef compatible with preview 4

---

boa3/analyser/typeanalyser.py
boa3/model/builtin/interop/runtime/getnotificationsmethod.py
boa3/model/builtin/interop/storage/storagegetcontextmethod.py
boa3/neo/core/types/UInt.py
boa3/neo3/contracts/nef.py
boa3_test/tests/neo/smart_contract/test_neffile.py
boa3_test/tests/test_class.py
boa3_test/tests/test_classes/block.py
boa3_test/tests/test_classes/signer.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_classes/transaction.py
boa3_test/tests/test_classes/witness.py
boa3_test/tests/test_interop.py

Included blocks and transactions in the TestEngine and fixed ``test_get_block_time`` unit test.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/6ca727eaf539601e916a8055fd412a9e31559df8/boa3_test/tests/test_interop.py#L1822-L1836

Boa-282 Include blocks and transactions in neo-boa's TestEngine

---

boa3/model/builtin/classmethod/tobytesmethod.py
boa3/model/builtin/interop/runtime/getcallingscripthashmethod.py
boa3/model/builtin/interop/runtime/getentryscripthashmethod.py
boa3/model/builtin/interop/runtime/getexecutingscripthashmethod.py
boa3/model/type/primitive/bytestype.py
boa3/neo/utils/__init__.py
boa3_test/test_sc/relational_test/CompareSameValueArgument.py
boa3_test/test_sc/relational_test/CompareSameValueHardCoded.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_for.py
boa3_test/tests/test_interop.py
boa3_test/tests/test_relational.py
boa3_test/tests/test_storage.py
boa3_test/tests/test_string.py
boa3_test/tests/test_test_engine.py

Fixed the comparison between two bytes values, which was always resulting False, even when it is the same value.
The problem is that the ``EQUAL`` opcode compares ``Buffer`` values comparing if it is the same object instead of checking if they store the same value. Fixed it changing the mapped Neo type for ``bytes`` from ``Buffer`` to ``ByteArray``
```python
@public
def testing_something() -> bool:
a = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
if a == a:
return True
else:
return False
```
This was returning False
**Tests**
Changed the unit tests to validate all the methods related to ``bytes`` values.

Boa-300 Comparing the same bytes is resulting in false

---

boa3/analyser/moduleanalyser.py
boa3_test/test_sc/dict_test/DictBoa2Test2.py
boa3_test/test_sc/list_test/ArrayBoa2Test1.py
boa3_test/tests/test_dict.py
boa3_test/tests/test_list.py

Evaluating value types of collection types (list, dict, tuple) was wrong when there are inner operations or function calls.
Solved this by checking in the ``typeanalyser.py`` the values again before setting to those variables
```python
m = [2, 4, 1, 5 + 12]  # instead of setting m as List[int] it was set to List[Any]
return m2[0] == q  # and this didn't work because == operation doesn't work with Any types yet
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d51d74d3517065c5d8e152740c25c46890c4211b/boa3_test/tests/test_list.py#L286-L293
https://github.com/CityOfZion/neo3-boa/blob/d51d74d3517065c5d8e152740c25c46890c4211b/boa3_test/tests/test_dict.py#L387-L393
**Platform:**
- Version: neo3-boa v0.6.0
- …

Boa-280 Fix error with comparison using list values

---

boa3/model/builtin/classmethod/extendmethod.py
boa3_test/test_sc/bytes_test/BytearrayExtendWithBuiltin.py
boa3_test/test_sc/list_test/ExtendAnyValue.py
boa3_test/test_sc/list_test/ExtendTupleValue.py
boa3_test/test_sc/list_test/ExtendWithBuiltin.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_list.py

Implemented the ``extend`` method for ``bytearray`` values. This method just worked for ``list`` values before
```python
def Main() -> bytearray:
a = bytearray(b'\x01\x02\x03')
a.extend(b'\x04\x05\x06')
return a
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d820c8e78a535c54c7a37c1a90f2d439afcc2e6d/boa3_test/tests/test_bytes.py#L447-L463
**Platform:**
- Version: neo3-boa v0.6.0

Boa-130 Convert bytearray extend method

---

boa3_test/tests/boa_test.py
boa3_test/tests/test_classes/testengine.py

The executions resulting FAULT was propagating its results to the following tests, as if the execution was successful.
Changed the TestEngine to only update its properties (storage, events, etc) if the execution result is HALT or when it's explicitly asked to update.
```
self.run_smart_contract(engine, path, 'Main')  # rollback on fault is True by default
self.run_smart_contract(engine, path, 'Main', rollback_on_fault=False)  # but it can save the changes if needed
```
**Platform:**
- Version; neo3-boa v.0.6.0

Rollback TestEngine Changes on FAULT result

---

boa3_test/tests/test_classes/nativeaccountstate.py
boa3_test/tests/test_classes/nativetokenprefix.py
boa3_test/tests/test_classes/storage.py
boa3_test/tests/test_classes/testengine.py

Included in the test storage methods to create fake balances of NEO and GAS for tests
```python
engine = TestEngine(self.dirname)
self.assertTrue(engine.add_neo(self.ACCOUNT, 1000))
self.assertTrue(engine.add_gas(self.ACCOUNT, 3000))
```
**Platform:**
- Version: neo3-boa v0.6.0

Fake Native contracts balance

---

README.md
boa3/builtin/interop/iterator/__init__.py
boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/model/builtin/interop/iterator/iteratornextmethod.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3_test/test_sc/interop_test/IteratorNext.py
boa3_test/tests/test_interop.py

Implemented the ``next`` method for iterating a ``Iterator`` object
```python
iterator = Iterator([1, 2, 3])
iterator.next()
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/9de9ab0dd261a0bf4c18d2974f16ac0435e44689/boa3_test/test_sc/interop_test/IteratorNext.py#L7-L9
**Platform:**

Boa-209 Implement Iterator Next Interop

---

boa3/model/builtin/builtin.py
boa3/model/operation/binary/arithmetic/concat.py
boa3_test/examples/NEP17.py
boa3_test/examples/nep5.py
boa3_test/examples/test_native/methods.py
boa3_test/test_sc/neo_type_test/UInt160ConcatWithBytes.py
boa3_test/tests/examples/test_examples.py
boa3_test/tests/test_classes/nativeaccountstate.py
boa3_test/tests/test_neo_types.py

Fixed concat operation validation when using non-primitive types (for example: `UInt160` instead of `bytes`)
```python
x = UInt160() + b'12345'  # UInt160 implements bytes, so this operation should be accepted
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/907d4be02fef7971cae74f46976c34cb7416aedb/boa3_test/tests/test_neo_types.py#L83-L96
**Platform:**

Boa-308 Fix operation validation for non-primitive types

---

boa3/analyser/moduleanalyser.py
boa3/builtin/interop/iterator/__init__.py
boa3/model/builtin/interop/iterator/getiteratorvalue.py
boa3/model/builtin/interop/iterator/iteratorinitmethod.py
boa3/model/builtin/interop/iterator/iteratornextmethod.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3_test/test_sc/interop_test/IteratorDictValueMismatchedType.py
boa3_test/test_sc/interop_test/IteratorListValueMismatchedType.py
boa3_test/test_sc/interop_test/IteratorValue.py
boa3_test/tests/test_interop.py

Implemented `value` property of `Iterator`s objects. It gets the value for the current position.
```python
iterator = Iterator([1, 2, 3])
iterator.next()
x: int = iterator.value
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f902123ebcf2ec22617aaffe35f524549f5d82a6/boa3_test/tests/test_interop.py#L1397-L1412
**Platform:**

Boa-211 Implement Iterator Value Interop

---

boa3/neo/__init__.py
boa3_test/tests/test_classes/block.py
boa3_test/tests/test_classes/signer.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_classes/transaction.py
boa3_test/tests/test_classes/witness.py

When an execution using the TestEngine returns HALT state, the executed transaction has to be included in the current block to better simulate the actual blockchain execution
**Platform:**

Boa-310 Include transaction result in the TestEngine

---

boa3/compiler/codegenerator.py
boa3/compiler/codegeneratorvisitor.py
boa3/neo/smart_contract/VoidType.py
boa3_test/test_sc/function_test/ConditionEmptyReturnFunction.py
boa3_test/test_sc/function_test/EmptyReturnWithOptionalReturnType.py
boa3_test/test_sc/function_test/ReturnVoidFunction.py
boa3_test/test_sc/function_test/ReturnVoidFunctionMismatchedType.py
boa3_test/tests/boa_test.py
boa3_test/tests/test_function.py

When using empty `return` statements in the middle of logic, the statement was being ignored in the execution.
```python
def foo(condition: bool, x: int):
if condition:
return  # this was being ignored and the execution flow was converted wrongly
do_something(x)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/17fc914ad7f5eaa2419b1f38bdc07a17d810e012/boa3_test/tests/test_function.py#L88-L146
**Platform:**

Boa-302 Verify the issue with empty return

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/maxmethod.py
boa3_test/test_sc/built_in_methods_test/MaxInt.py
boa3_test/test_sc/built_in_methods_test/MaxMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/MaxTooFewParameters.py
boa3_test/tests/test_builtin_method.py

Implemented max() to neo3-boa, the method currently only compares 2 ints.
Call the method with 2 ints as parameters
`max(int_1, int_2)`
**Tests**
Tested it using the test engine
https://github.com/CityOfZion/neo3-boa/blob/2f1938139d905550dc432e4e6a55548705c2d4c6/boa3_test/tests/test_builtin_method.py#L970-L980
**Platform:**
The original Python max() doesn't compare only 2 ints, so, in the future, this will be tweaked to correspond with the original one
.

Boa-178 Convert builtin max

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/minmethod.py
boa3_test/test_sc/built_in_methods_test/MinInt.py
boa3_test/test_sc/built_in_methods_test/MinMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/MinTooFewParameters.py
boa3_test/tests/test_builtin_method.py

Implemented min() to neo3-boa, the method currently only compares 2 ints.
Call the method with 2 ints as parameters
`min(int_1, int_2)`
**Tests**
Tested it using the test engine
https://github.com/CityOfZion/neo3-boa/blob/4e0685e30aa272f4dccae6437eb4cb25a5ddf9ff/boa3_test/tests/test_builtin_method.py#L998-L1014
**Platform:**
The original Python min() doesn't compare only 2 ints, so, in the future, this will be tweaked to correspond with the original one.

Boa-179 Convert builtin min

---

docs/ContractExamplesTest.md

Fixed the href of BytearrayGetValue.py and Bytearray type (from v0.6.1) and deleted one accidental copy GlobalAssignmentInFunctionWithArgument.py.
**Platform:**

Boa-298 Some linked examples in github are leading to a 404 error page

---

boa3/analyser/optimizer/__init__.py
boa3/analyser/symbolscope.py
boa3/model/builtin/interop/contract/contracttype.py
boa3/neo3/contracts/__init__.py
boa3/neo3/contracts/contracttypes.py
boa3_test/tests/test_types.py
boa3_test/tests/test_union.py

#207 
Fixed the execution errors caused by missing imports in #207
**Platform:**

Boa-297 Use isinstance condition in the semantics

---

boa3/builtin/interop/enumerator/__init__.py
boa3/model/builtin/interop/contract/contracttype.py
boa3/model/builtin/interop/enumerator/__init__.py
boa3/model/builtin/interop/enumerator/enumeratorinitmethod.py
boa3/model/builtin/interop/enumerator/enumeratortype.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/notificationtype.py
boa3/model/builtin/interop/storage/storagecontexttype.py
boa3/model/type/annotation/uniontype.py
boa3/model/type/itype.py
boa3_test/test_sc/import_test/FromImportTypingNotImplementedType.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorCreateInt.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorCreateList.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorCreateMismatchedTypes.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorCreateTuple.py
boa3_test/tests/test_interop/test_enumerator.py

Implemented the class `Enumerator` with its constructor being the Neo interop `Enumerator.Create`
```python
from boa3.builtin.interop.enumerator import Enumerator
def list_enumerator(x: list) -> Enumerator:
return Enumerator(x)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4d589e01bbe786aca7805cc219ebbeb72f0a5d73/boa3_test/tests/test_interop/test_enumerator.py#L11-L76
**Platform:**

Boa-214 Implement Enumerator Create Interop

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/builtin/interop/iterator/__init__.py
boa3/compiler/codegeneratorvisitor.py
boa3/compiler/vmcodemapping.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/iterator/__init__.py
boa3/model/builtin/interop/iterator/iteratorconcatmethod.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3/model/type/annotation/uniontype.py
boa3/model/type/collection/mapping/mappingtype.py
boa3_test/test_sc/interop_test/iterator/IteratorConcat.py
boa3_test/test_sc/interop_test/iterator/IteratorConcatMismatchedType.py
boa3_test/test_sc/interop_test/iterator/IteratorConcatWithDefinedTypes.py
boa3_test/tests/test_interop/test_iterator.py

Implemented the ``concat`` method for concatenating two ``Iterator``s objects
```python
iterator1 = Iterator([1, 2, 3])
iterator2 = Iterator({'1': 1, '2': 2, '3': 3})
iterator3 = iterator1.concat(iterator2)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/317aa1bacd0fd68cb902e249e4102d9b1759cba3/boa3_test/tests/test_interop/test_iterator.py#L124-L154 
**Platform:**

Boa-208 Implement Iterator Concat Interop

---

boa3/model/type/collection/icollection.py
boa3_test/examples/HTLC.py
boa3_test/examples/test_native/example_contract_for_htlc.py
boa3_test/examples/test_native/methods.py
boa3_test/examples/test_native/methods_copy.py
boa3_test/tests/examples/HTLCTests.py
docs/source/examples.rst

Added a template for an atomic swap transaction and some tests.
Deploy the HTLC smart contract, call atomic_swap(), transfer NEO or GAS to the smart contract, then withdraw with the right password.
**Tests**
Tested it using the TestEngine
**Platform:**
Currently, it's not possible to call the NEO or GAS contracts, therefore some tests were omitted, when call_contract() starts working properly again the tests will receive an update.

Boa-228 Create atomic swap example for neo3-boa

---

boa3/builtin/interop/iterator/__init__.py
boa3/model/builtin/interop/enumerator/enumeratortype.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3/model/builtin/interop/iterator/iteratorvaluesmethod.py
boa3_test/test_sc/interop_test/iterator/IteratorValues.py
boa3_test/test_sc/interop_test/iterator/IteratorValuesMismatchedType.py
boa3_test/tests/test_interop/test_iterator.py

Implemented `values` method of `Iterator`s objects. It gets an enumerator of the iterator's values.
```python
iterator = Iterator([1, 2, 3])
x = iterator.values()
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/acbb815ee410049cede74baf894e95e52579ae8f/boa3_test/tests/test_interop/test_iterator.py#L156-L177
**Platform:**

Boa-213 Implement Iterator Values Interop

---

boa3/builtin/interop/iterator/__init__.py
boa3/model/builtin/interop/enumerator/enumeratortype.py
boa3/model/builtin/interop/iterator/iteratorkeysmethod.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3_test/examples/HTLC.py
boa3_test/test_sc/interop_test/iterator/IteratorKeys.py
boa3_test/test_sc/interop_test/iterator/IteratorKeysMismatchedType.py
boa3_test/tests/examples/HTLCTests.py
boa3_test/tests/test_interop/test_iterator.py
setup.cfg

Implemented `keys` method of `Iterator`s objects. It gets an enumerator of the iterator's keys.
```python
iterator = Iterator([1, 2, 3])
enumerator = iterator.keys()
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fb6704ae115f028649bcbbae548ec3b03ed4ad8b/boa3_test/tests/test_interop/test_iterator.py#L179-L200
**Platform:**

Boa-212 Implement Iterator Keys Interop

---

boa3/analyser/typeanalyser.py
boa3/model/builtin/method/builtinmethod.py
boa3/model/builtin/method/isinstancemethod.py
boa3/neo/vm/VMCode.py
boa3_test/test_sc/built_in_methods_test/IsInstanceClass.py
boa3_test/test_sc/built_in_methods_test/IsInstanceManyTypesWithClass.py
boa3_test/tests/test_builtin_method.py

``isinstance`` with boa builtin types were not having the expected behavior.
After an evaluation, we arrived to the conclusion that it'll need a big refactor, so until there the usage of ``isinstance`` in those cases will raise an ``NotSupportedException``
```python
value = UInt160(value)
return isinstance(value, UInt160)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/919d39e8f37da40b6d99fcb5d80a03ab3464e847/boa3_test/tests/test_builtin_method.py#L960-L966
**Platform:**

Boa-320 Raise NotSupportedException when using isinstance with boa builtin types

---

boa3/builtin/interop/enumerator/__init__.py
boa3/model/builtin/interop/enumerator/enumeratorconcatmethod.py
boa3/model/builtin/interop/enumerator/enumeratortype.py
boa3/model/builtin/interop/iterator/iteratorconcatmethod.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorConcat.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorConcatMismatchedType.py
boa3_test/test_sc/interop_test/enumerator/EnumeratorConcatWithDefinedTypes.py
boa3_test/tests/test_interop/test_enumerator.py

Implemented the ``concat`` method for concatenating two ``Enumerator``s objects
```python
enumerator1 = Enumerator([1, 2, 3])
enumerator2 = Enumerator(('1', '2', '3'))
enumerator3 = enumerator1.concat(enumerator2)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/80ca4ded72aae9552aa4e408de12d9b571dcfc0d/boa3_test/tests/test_interop/test_enumerator.py#L78-L99
**Platform:**

Boa-215 Implement Enumerator Concat Interop

---

README.md
docs/source/install.rst

Changed neo3-boa documentation to require at least Python 3.7 instead of 3.8 and tested all unit tests to see if there was a compatibility problem.
**Tests**
Tested it using the TestEngine and Opcodes
**Platform:**
- OS:  Windows 10 x64

Boa-326 Match all documentation Python requirements to 3.7 as minimum

---

README.md
docs/source/install.rst
requirements.txt
requirements_dev.txt

#194 
Removed `Make sure you have installed MSVC v142 - Build tools VS 2019 C++ x64/x86 (v14.24). You can do this by installing Visual Studio 2019 and add C++ development features.` at README and docs, and removed bitarray and mmh3 as required packages to install.
**Tests**
Tested all unit test with the TestEngine and/or Opcode.
**Platform:**

Boa-322 Verify why does the neo3-boa requires C++ Build tools

---

boa3_test/tests/test_bytes.py

The is no need to fix bytes.to_bool(), it's returning exactly what it should return.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/de91e51c8b7125ce53393039ad101a0352ec9314/boa3_test/tests/test_bytes.py#L153-L159
**Platform:**

Boa-299 Fix bytes_to_bool_with_builtin

---

boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_test_engine.py

#193 
Checked if the TestEngine path exists and if not raise an Exception explaining why.
**Tests**
Deleted the folder and changed the name to see if an Exception would occur.
**Platform:**

Boa-323 Change the TestEngine error when the executable is not found

---

boa3/builtin/__init__.py
boa3/model/builtin/builtin.py
boa3_test/test_sc/metadata_test/MetadataInfoNewExtras.py
boa3_test/tests/test_metadata.py

Implemented a way to add more data in the metadata if the user wants to.
Create a dictionary and attribute it to `extras`
```
@metadata
def extras_manifest() -> NeoMetadata:
meta = NeoMetadata()
meta.extras = {'unittest1': 'string',
'unittest2': 123,
'unittest3': True,
'unittest4': ['list', 3210]
}
return meta
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3c7056d3fc4361941984c32addc66eda85abf660/boa3_test/tests/test_metadata.py#L145-L163
**Platform:**

Boa-166 Include generic extras in the metadata

---

boa3_test/tests/test_classes/nativetokenprefix.py

Fix the creation of fake balances for unit tests
**Platform:**

Fix TestEngine's Fake Balance

---

boa3/analyser/astanalyser.py
boa3/analyser/builtinfunctioncallanalyser.py
boa3_test/tests/test_file_generation.py

Some unit tests should be failing because compilation wasn't successful, but they're passing.
The problem was with the logging in the unit tests. This doesn't happen if using in the command line,
**Platform:**

Fix unit tests passing that were expected to fail

---

boa3/analyser/builtinfunctioncallanalyser.py
boa3/analyser/optimizer/__init__.py
boa3/analyser/typeanalyser.py
boa3_test/tests/boa_test.py

When there was an error in a built-in function analysis, it wasn't logged. That happened because the class responsible for this didn't receive the bool value for logging
**Platform:**

Fix BuiltinFunctionAnalyser log value

---

boa3/analyser/symbolscope.py
boa3/analyser/typeanalyser.py
boa3_test/test_sc/if_test/VariablesInIfScopes.py
boa3_test/tests/test_if.py

#253 
Fixed the error in type checking that was using the type set for a variable in a different branch 
```python
@public
def main(operation: int) -> bool:
if operation == 1:
a = 'deploy'
b = bytearray(b'deploy\x00\x00')
return a == b
elif operation == 2:
a = 'deploy'
b = bytearray(b'deploy')
return a == b
elif operation == 3:
a = b'deploy'
b = 'deploy'
return a == b
elif operation == 4:
a = 0
b = False
return a == b
elif operation == 5:
a = 0
b = ''
return a == b
elif operation == 6:
a = False
b = ''
return a == b
elif operation == 7:
a = False
b = -1
return a == b
return False
```
**Platform:**

Fix types in scope

---

boa3/analyser/moduleanalyser.py
boa3_test/test_sc/dict_test/DictAnyKeyAndValue.py
boa3_test/tests/test_dict.py

#247 
Fixed the incorrect assigned type to variables assigned with dictionary getters
https://github.com/CityOfZion/neo3-boa/blob/c686c020ca98855d6b943c4ba17d2c06e0dbe429/boa3_test/test_sc/dict_test/DictAnyKeyAndValue.py#L5-L28
**Platform:**

Fix dictionary being created as Any

---

.circleci/config.yml

#270
Changed the CircleCI workflow to run the unit tests using both Python 3.7 and 3.8
**Tests**
CicleCI result

Include 3.7 unit tests in CircleCI workflow

---

boa3/analyser/astanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/exception/CompilerError.py
boa3_test/test_sc/string_test/StringSimpleConcat.py
boa3_test/tests/test_string.py

#230
The error reported in the issue was already fixed in a later pull request (#235). Changed the message of InternalError to prevent showing exceptions' stack traces to the user.
Before
After
**Platform:**

change InternalError message

---

boa3/compiler/codegenerator/stackmemento.py
boa3/model/builtin/interop/contract/callmethod.py
boa3/neo3/contracts/__init__.py
boa3_test/test_sc/function_test/RecursiveFunction.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_if.py
boa3_test/tests/test_test_engine.py

#107 
Couldn't reproduce the failure in execution, so included a unit test running it with TestEngine.
```python
def fact(f: int) -> int:
if f <= 1:
return 1
return f * fact(f-1)
def main() -> int:
return fact(57)
```
**Platform:**

Included contract execution unit test

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/model/operation/binary/arithmetic/concat.py
boa3/model/operation/binary/binaryoperation.py
boa3/model/operation/binaryop.py
boa3_test/test_sc/list_test/ListSlicingStartLargerThanEnding.py
boa3_test/test_sc/range_test/RangeSlicingStartLargerThanEnding.py
boa3_test/test_sc/string_test/StringSlicingStartLargerThanEnding.py
boa3_test/test_sc/tuple_test/TupleSlicingStartLargerThanEnding.py
boa3_test/tests/test_list.py
boa3_test/tests/test_range.py
boa3_test/tests/test_string.py
boa3_test/tests/test_tuple.py

#238 
Fixed the slice execution when it should return an empty sequence. It was raising an exception for slices of `str` and `bytes` types.
```python
@public
def Main() -> str:
a = 'unit_test'
return a[3:2]   # expect ''
```
**Platform:**

Fixed slices that should return empty sequences

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/removemethod.py
boa3_test/test_sc/list_test/RemoveIntValue.py
boa3_test/test_sc/list_test/RemoveIntWithBuiltin.py
boa3_test/test_sc/list_test/RemoveValue.py
boa3_test/tests/test_list.py

#241
Implemented Python built-in `list` `remove` method.
```python
from typing import List
def Main(op: str, args: list) -> List[str]:
a = ['1', '2', '3']
a.remove('2')
return a  # expected ['1', '3']
```
**Platform:**

Convert list remove method

---

boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/builtin/method/isinstancemethod.py
boa3/model/method.py
boa3/model/type/anytype.py
boa3/model/type/classtype.py
boa3/model/type/collection/sequence/uint160type.py
boa3/model/type/itype.py
boa3/model/type/primitive/nonetype.py
boa3/neo/vm/opcode/Opcode.py
boa3_test/test_sc/built_in_methods_test/IsInstanceClass.py
boa3_test/test_sc/built_in_methods_test/IsInstanceUInt160.py
boa3_test/tests/test_builtin_method.py
boa3_test/tests/test_string.py

#314
Fixed Python built-in ``isinstance`` to work with neo3-boa built-in ``UInt160``.
```python
from boa3.builtin.type import UInt160
@public
def Main(value: Any) -> bool:
return isinstance(value, UInt160)
```
**Platform:**

Fix isinstance for UInt160

---

boa3/builtin/interop/runtime/__init__.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/builtin/interop/runtime/notifymethod.py
boa3/model/event.py
boa3_test/test_sc/dict_test/DictBoa2Test1.py
boa3_test/test_sc/dict_test/DictBoa2Test2.py
boa3_test/test_sc/dict_test/DictBoa2Test3.py
boa3_test/test_sc/dict_test/DictBoa2Test5ShouldNotCompile.py
boa3_test/test_sc/dict_test/DictBoa2Test6ShouldNotCompile.py
boa3_test/test_sc/event_test/EventBoa2Test.py
boa3_test/test_sc/interop_test/runtime/NotifyWithName.py
boa3_test/test_sc/interop_test/runtime/RuntimeBoa2Test.py
boa3_test/test_sc/interop_test/storage/StorageBoa2Test.py
boa3_test/test_sc/list_test/ReverseBoa2Test.py
boa3_test/tests/test_if.py
boa3_test/tests/test_interop/test_runtime.py

#272 
Included an optional argument in the `notify` interop function to allow to modify the notification's event name.
```python
from boa3.builtin.interop.runtime import notify
@public
def Main():
notify(10, 'example_notification')
```
**Platform:**

The byte[] eventName parameter is missing at notify()

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/gettriggermethod.py
boa3_test/test_sc/bytes_test/BytearrayBoa2Test.py
boa3_test/test_sc/bytes_test/BytearrayBoa2Test2.py
boa3_test/test_sc/bytes_test/BytearrayBoa2Test3.py
boa3_test/test_sc/function_test/RecursiveFunction.py
boa3_test/test_sc/interop_test/runtime/NotifyBool.py
boa3_test/test_sc/interop_test/runtime/NotifyInt.py
boa3_test/test_sc/interop_test/runtime/NotifyNone.py
boa3_test/test_sc/interop_test/runtime/NotifySequence.py
boa3_test/test_sc/interop_test/runtime/NotifyStr.py
boa3_test/test_sc/interop_test/runtime/RuntimeBoa2Test.py
boa3_test/test_sc/interop_test/runtime/Trigger.py
boa3_test/test_sc/interop_test/runtime/TriggerApplication.py
boa3_test/test_sc/interop_test/runtime/TriggerNotSystem.py
boa3_test/test_sc/interop_test/runtime/TriggerTypeBoa2Test.py
boa3_test/test_sc/interop_test/runtime/TriggerVerification.py

#264
Changed ``trigger`` interop function to ``get_trigger``
```python
from boa3.builtin.interop.runtime import TriggerType, get_trigger
@public
def Main() -> TriggerType:
return get_trigger()
```
**Platform:**

Change trigger() to get_trigger()

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/variable.py
boa3_test/test_sc/none_test/MismatchedTypesAssign.py
boa3_test/test_sc/none_test/ReassignVariableAfterNone.py
boa3_test/test_sc/none_test/ReassignVariableWithNone.py
boa3_test/test_sc/variable_test/ReassignVariableType.py
boa3_test/tests/test_bytes.py
boa3_test/tests/test_file_generation.py
boa3_test/tests/test_none.py
boa3_test/tests/test_variable.py

#239
Included support to reassign variables with values which types are different from the previously assigned type. Also, this new type is used during operation type validation, without conflicting with the first one.
```python
@public
def Main() -> int:
x = 'example'
y: str = 'code ' + x
x = 1234
return x
```
**Platform:**

Support reassign types to existing variables

---

boa3/builtin/interop/contract/contract.py
boa3/model/builtin/interop/contract/contracttype.py

#275 
Renamed `Contract`'s `script` variable to `nef`
```python
contract = Contract()
x = contract.nef
```
**Platform:**

Change Contract script attribute to nef

---

boa3/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/base58decodemethod.py
boa3/model/builtin/interop/binary/base58encodemethod.py
boa3_test/test_sc/interop_test/binary/Base58Decode.py
boa3_test/test_sc/interop_test/binary/Base58DecodeMismatchedType.py
boa3_test/test_sc/interop_test/binary/Base58Encode.py
boa3_test/test_sc/interop_test/binary/Base58EncodeMismatchedType.py

#274 
Changed the parameters and return types of `base58_encode` and `base58_decode` interop functions, that were implemented wrongly.
```python
from boa3.builtin.interop.binary import base58_decode, base58_encode
def encode(key: bytes) -> str:
return base58_encode(key)
def decode(key: str) -> bytes:
return base58_decode(key)
```
**Platform:**

Change base58_encode and base58_decode parameters

---

boa3_test/test_sc/interop_test/storage/StorageGetAndPut1.py
boa3_test/test_sc/interop_test/storage/StorageGetAndPut2.py
boa3_test/tests/boa_test.py
boa3_test/tests/examples/test_hello_world.py
boa3_test/tests/examples/test_ico.py
boa3_test/tests/test_classes/storage.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_interop/test_storage.py

#353
Fixed a problem in the TestEngine execution, that caused the executing smart contract to have access to other smart contracts' storages.
```python
path1 = self.get_contract_path('StorageGetAndPut1.py')
path2 = self.get_contract_path('StorageGetAndPut2.py')
key = 'example_key'
value = 42
engine = TestEngine()
result = self.run_smart_contract(engine, path1, 'put_value', key, value)
storage_value = engine.storage_get(key, path1)
assert Integer.from_bytes(storage_value)) == value
result = self.run_smart_contract(engine, path2, 'get_value', key)
assert result == 0
assert engine.storage_get(key, path2) is None
```
**Platform:**

Fix smart-contract storage access in test engine execution

---

boa3/model/builtin/interop/contract/contractmanagementmethod.py
boa3_test/test_sc/interop_test/UpdateContract.py
boa3_test/tests/test_interop/test_contract.py

#362 
When using `update_contract` or `destroy_contract` boa built-in methods, instead of returning no value it was returning null. This resulted in the execution failing due to the unexpected value.
Update or destroy a smart contract compiled with neo3-boa
**Platform:**

Fix return when using update_contract and destroy_contract

---

boa3/neo/utils/__init__.py
boa3/neo/vm/type/ContractParameterType.py
boa3_test/tests/test_classes/contract/neoabistruct.py
boa3_test/tests/test_classes/contract/neoeventstruct.py
boa3_test/tests/test_classes/contract/neomanifeststruct.py
boa3_test/tests/test_classes/contract/neomethodstruct.py
boa3_test/tests/test_classes/contract/neopermissionsstruct.py
boa3_test/tests/test_classes/contract/neostruct.py
boa3_test/tests/test_interop/test_blockchain.py
boa3_test/tests/test_interop/test_contract.py

#318 
The result of ``create_contract`` was returning with `null` manifest. The problem was in neo3-boa's unit tests, where it couldn't convert Neo's `Struct` type, which is the manifest's type in this case.
Implemented Struct conversion from TestEngine's output and a way to convert json to Struct for testing
Create a smart contract that calls `create_contract`
```python
from boa3.builtin.interop.contract import Contract, create_contract
@public
def Main(script: bytes, manifest: bytes) -> Contract:
return create_contract(script, manifest)
```
and deploy another smart contract invoking it.
```python
call_contract_path = 'path/to/other/contract.py'
nef_file, manifest = …
```

Contract Manifest returning null when using Contract related functions

---

boa3/analyser/astanalyser.py
boa3/analyser/typeanalyser.py
boa3/builtin/interop/storage/__init__.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/builtin/interop/storage/storagedeletemethod.py
boa3/model/builtin/interop/storage/storagefindmethod.py
boa3/model/builtin/interop/storage/storagegetmethod.py
boa3/model/builtin/interop/storage/storageputmethod.py
boa3/model/builtin/method/builtinmethod.py
boa3_test/test_sc/interop_test/storage/StorageBoa2Test.py
boa3_test/test_sc/interop_test/storage/StorageDeleteWithContext.py
boa3_test/test_sc/interop_test/storage/StorageFindWithContext.py
boa3_test/test_sc/interop_test/storage/StorageGetWithContext.py
boa3_test/test_sc/interop_test/storage/StoragePutWithContext.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_interop/test_storage.py

#354
Included an argument to each storage function to use a specific storage context.
```python
from typing import Any
from boa3.builtin.interop.storage import delete, get, get_context, put
@public
def main(operation: str, arg: str, val: str) -> Any:
storage_context = get_context()
if operation == 'get':
return get(arg, storage_context)
elif operation == 'put':
put(arg, val, storage_context)
return True
elif operation == 'del':
delete(arg, storage_context)
return True
elif operation == 'find':
return find(arg, storage_context)
return 'unknown operation'
```
**Platform:**

Add support to storage context in storage functions

---

README.md
README.rst
docs/source/getting-started.rst
setup.py

I think these are important for the RC1 release
1. Some time ago I pointed out that the required Python version differs from setup.py, documentation and the readme. 
2. current dev fails to install from source due the `parse_requirements` logic failing
3. current dev fails to install from source if the `wheel` package is not installed. `autopep8` and `coverage` fail. 
1. updated the versions to 3.7 & 3.8 to match with mamba
2. the `parse_requirements()` seems to have changed over time to return different objects. I can't exactly tell when and where or if it is just for a certain platform. The new solution is more generic. On OSX it worked as is, but Ubuntu fails.
3. while the failing packages are development requirements, I think it's …

Fix version and setup when installing from source

---

README.md
boa3/env.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_test_engine.py
boa3_test/tests/test_classes/testengine.py
docs/source/getting-started.rst

#375
[env.py](https://github.com/CityOfZion/neo3-boa/blob/8b66f12cfad881050e202e31cc474e39d83014c3/env.py) was not included when installing neo3-boa using pip. Because of that, users that installed using pip couldn't run the unit tests as specified in the [README file](https://github.com/CityOfZion/neo3-boa/tree/8b66f12cfad881050e202e31cc474e39d83014c3#tests)
Install neo3-boa's developer branch using pip. `env` should be inside boa3 package path.
**Platform:**

env is not included in pip installation

---

boa3/analyser/importanalyser.py
boa3/analyser/moduleanalyser.py
boa3/builtin/interop/storage/__init__.py
boa3/builtin/interop/storage/storagecontext.py
boa3/builtin/interop/storage/storagemap.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/storage/__init__.py
boa3/model/builtin/interop/storage/storagecontext/__init__.py
boa3/model/builtin/interop/storage/storagecontext/storagecontextcreatemapmethod.py
boa3/model/builtin/interop/storage/storagecontext/storagecontexttype.py
boa3/model/builtin/interop/storage/storagedeletemethod.py
boa3/model/builtin/interop/storage/storagefindmethod.py
boa3/model/builtin/interop/storage/storagegetcontextmethod.py
boa3/model/builtin/interop/storage/storagegetmethod.py
boa3/model/builtin/interop/storage/storagemap/__init__.py
boa3/model/builtin/interop/storage/storagemap/storagemapdeletemethod.py
boa3/model/builtin/interop/storage/storagemap/storagemapgetmethod.py
boa3/model/builtin/interop/storage/storagemap/storagemapputmethod.py
boa3/model/builtin/interop/storage/storagemap/storagemaptype.py
boa3/model/builtin/interop/storage/storageputmethod.py
boa3_test/test_sc/interop_test/storage/StorageCreateMap.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

#393 
Implemented the class StorageMap for simplifying the access to the storage.
```python
from boa3.builtin.interop.storage import get_context
@public
def Main(key: str) -> bytes:
storage_map = get_context().create_map('example')
return storage_map.get(key)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/a95c8fbca7e3f3c45f61fa4f2f63b96b77d9cfae/boa3_test/test_sc/interop_test/storage/StorageCreateMap.py#L1-L24
https://github.com/CityOfZion/neo3-boa/blob/a95c8fbca7e3f3c45f61fa4f2f63b96b77d9cfae/boa3_test/tests/compiler_tests/test_interop/test_storage.py#L616-L646
**Platform:**

Support to StorageMap

---

boa3/model/operation/binary/arithmetic/power.py
boa3/neo/vm/opcode/OpcodeInfo.py
boa3_test/test_sc/arithmetic_test/Power.py
boa3_test/test_sc/arithmetic_test/PowerAugmentedAssignment.py
boa3_test/tests/compiler_tests/test_arithmetic.py

#359 
Implemented exponentiation Opcode in the builtin
Use `x ** y`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/86f4d656238d0981ff8710c9a65fe556273c73dc/boa3_test/tests/compiler_tests/test_arithmetic.py#L262-L286
https://github.com/CityOfZion/neo3-boa/blob/86f4d656238d0981ff8710c9a65fe556273c73dc/boa3_test/tests/compiler_tests/test_arithmetic.py#L538-L552
**Platform:**
Also added POW and SQRT Opcodes in OpcodeInfo.

 Implement exponentiation as a builtin method to neo3-boa #359

---

boa3/builtin/__init__.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/sqrtmethod.py
boa3_test/test_sc/built_in_methods_test/Sqrt.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#358
Added a square root method
Call `sqrt()`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/6280ef4a1ee23eab6a6cc1d11fc4cfea9bbfbad0/boa3_test/tests/compiler_tests/test_builtin_method.py#L980-L1015
**Platform:**

Implement square root as a builtin method to neo3-boa #358

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/absmethod.py
boa3_test/test_sc/built_in_methods_test/Abs.py
boa3_test/test_sc/built_in_methods_test/AbsMismatchedTypesBytes.py
boa3_test/test_sc/built_in_methods_test/AbsMismatchedTypesString.py
boa3_test/test_sc/built_in_methods_test/AbsTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/AbsTooManyParameters.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#254 
Added an absolute value method.
Call `abs()`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/01464dd0a81b7fc952d06d7513bcc4e1cde456e8/boa3_test/tests/compiler_tests/test_builtin_method.py#L1017-L1052
**Platform:**

 Convert Python builtin abs #254

---

boa3/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/atoimethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/binary/Atoi.py
boa3_test/test_sc/interop_test/binary/AtoiDefault.py
boa3_test/test_sc/interop_test/binary/AtoiMismatchedType.py
boa3_test/test_sc/interop_test/binary/AtoiTooFewArguments.py
boa3_test/test_sc/interop_test/binary/AtoiTooManyArguments.py
boa3_test/tests/compiler_tests/test_interop/test_binary.py

#289 
Import the atoi function from boa3.builtin.interop.binary and use it in the smart contract. For example:
```python
from boa3.builtin.interop.binary import atoi
def test():
atoi('123', 10)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d2922b361d47528f758bfc03aff8bed55f439df0/boa3_test/tests/compiler_tests/test_interop/test_binary.py#L263-L320
**Platform:**

 Implement Binary Atoi Interop #289

---

boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_interop/test_native_contract.py
boa3_test/tests/examples_tests/test_HTLC.py
boa3_test/tests/examples_tests/test_NEP17.py
boa3_test/tests/examples_tests/test_amm.py
boa3_test/tests/examples_tests/test_nep5.py
boa3_test/tests/examples_tests/test_wrapped_neo.py
boa3_test/tests/test_classes/nativecontractprefix.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_classes/transaction.py
boa3_test/tests/test_classes/transactionattribute/__init__.py
boa3_test/tests/test_classes/transactionattribute/oracleresponse.py
boa3_test/tests/test_classes/transactionattribute/transactionattribute.py
boa3_test/tests/test_classes/transactionattribute/transactionattributetype.py

#407
Changed the TestEngine implementation inside neo3-boa to be able to test mocked Oracle responses.
```python
engine.run_oracle_response(request_id, OracleResponseCode.Success, result=b'12345')
```
**Tests**
Run the unit tests with the updated TestEngine.
Some of the unit tests from the examples smart contracts aren't working and are going to be fixed in #416
**Platform:**
When I tested the mocked response, the TestEngine threw an internal Neo error. Not sure yet if the problem was inside the TestEngine or if there's something wrong with the native OracleContract

Change TestEngine implementation to support Oracle testing

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/summethod.py
boa3_test/test_sc/built_in_methods_test/Sum.py
boa3_test/test_sc/built_in_methods_test/SumMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/SumTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/SumTooManyParameters.py
boa3_test/test_sc/built_in_methods_test/SumWithStart.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#255
Implemented Python's built-in `sum` function 
```python
@public
def main() -> int:
return sum([1, 2, 3, 4], 10)  # expected 1+2+3+4+10 = 20
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/72b213e0b332826f718ed690d29f9ed55696e5ac/boa3_test/tests/compiler_tests/test_builtin_method.py#L1054-L1098
**Platform:**

Convert Python builtin sum

---

boa3/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/itoamethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/binary/Itoa.py
boa3_test/test_sc/interop_test/binary/ItoaDefault.py
boa3_test/test_sc/interop_test/binary/ItoaMismatchedType.py
boa3_test/test_sc/interop_test/binary/ItoaTooFewArguments.py
boa3_test/test_sc/interop_test/binary/ItoaTooManyArguments.py
boa3_test/tests/compiler_tests/test_interop/test_binary.py

#287 
Use `itoa()`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f95beb09ff6dc7e39663e9a9641003bbc07635c4/boa3_test/tests/compiler_tests/test_interop/test_binary.py#L322-L359
**Platform:**

Implement Binary Itoa Interop #287

---

boa3/builtin/interop/blockchain/__init__.py
boa3/builtin/interop/blockchain/block.py
boa3/builtin/interop/contract/__init__.py
boa3/constants.py
boa3/model/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/blocktype.py
boa3/model/builtin/interop/blockchain/getblockmethod.py
boa3/model/builtin/interop/blockchain/getcontractmethod.py
boa3/model/builtin/interop/contract/createmethod.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/nativecontract/ContractManagement/contractmanagementmethod.py
boa3/model/builtin/interop/nativecontract/Ledger/__init__.py
boa3/model/builtin/interop/nativecontract/Ledger/getledgerscripthashmethod.py
boa3/model/builtin/interop/nativecontract/Ledger/ledgermethod.py
boa3/model/builtin/interop/nativecontract/__init__.py
boa3/neo3/contracts/__init__.py
boa3_test/test_sc/built_in_methods_test/SumMismatchedTypes.py
boa3_test/test_sc/interop_test/blockchain/GetBlockByHash.py
boa3_test/test_sc/interop_test/blockchain/GetBlockByIndex.py
boa3_test/test_sc/interop_test/blockchain/GetBlockMismatchedTypes.py
boa3_test/test_sc/interop_test/contract/CallFlagsUsage.py
boa3_test/test_sc/interop_test/contract/CallScriptHashTooManyArguments.py
boa3_test/test_sc/interop_test/contract/CallScriptHashWithFlags.py
boa3_test/tests/compiler_tests/test_interop/test_binary.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/test_classes/testengine.py

#285
Implemented ``get_block`` function
```python
from boa3.builtin.interop.blockchain import Block, get_block
@public
def example():
block_from_index: Block = get_block(10)
if isinstance(block_from_index, Block):
block_from_hash = get_block(block_from_index.hash)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/74bc7ca9b081b781d13f9924354ac12e0a33a0c1/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L63-L104
**Platform:**

Implement Block Interop

---

boa3/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/getcallflagsmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/contract/GetCallFlags.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py

#291 
Call `get_call_flags()` function.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/6f26298130d4e2f92749d659956decc16ea29c98/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L270-L301
**Platform:**

 Implement Contract GetCallFlags Interop #291

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/burngasmethod.py
boa3_test/test_sc/interop_test/runtime/BurnGas.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py

#438 
Call `burn_gas(gas: int)`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4040286be71d61e1e4ddcf7415854362a82fa56c/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L526-L550
**Platform:**

 Implement Runtime BurnGas Interop

---

boa3/analyser/moduleanalyser.py
boa3_test/test_sc/neo_type_test/CastTransactionGetHash.py
boa3_test/test_sc/neo_type_test/CastTransactionGetHashToVariable.py
boa3_test/test_sc/neo_type_test/ImplicitCastTransactionGetHash.py
boa3_test/test_sc/typing_test/CastToTransaction.py
boa3_test/test_sc/typing_test/CastToUInt160.py
boa3_test/tests/compiler_tests/test_neo_types.py
boa3_test/tests/compiler_tests/test_typing.py

#428
Fixed casting to Neo types
```python
x = cast(Transaction, script_container)
y: Block = get_block(block_hash)
```
https://github.com/CityOfZion/neo3-boa/blob/9b7453b696e31f647326d34b6a671342f8dc4004/boa3_test/test_sc/neo_type_test/ImplicitCastTransactionGetHash.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/9b7453b696e31f647326d34b6a671342f8dc4004/boa3_test/tests/compiler_tests/test_neo_types.py#L198-L208
**Platform:**

Fix properties access after casting

---

boa3/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/gettransactionfromblockmethod.py
boa3/model/builtin/interop/blockchain/gettransactionheightmethod.py
boa3/model/builtin/interop/blockchain/gettransactionmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/blockchain/GetTransaction.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockInt.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockUInt256.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionHeight.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py

#288 
Implemented `get_transaction()`, `get_transaction_from_block()` and `get_transaction_height()`.
**Tests**
Tested it verifying the Opcodes.
**Platform:**
The tests aren't finished right now, because there was a problem with the transactions and storage.

Implement Transaction Interops

---

boa3/model/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/gettransactionheightmethod.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/type/typeutils.py
boa3/neo/vm/VMCode.py
boa3_test/test_sc/if_test/IfWithInnerFor.py
boa3_test/test_sc/if_test/IfWithInnerWhile.py
boa3_test/test_sc/interop_test/blockchain/GetTransaction.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockInt.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockUInt256.py
boa3_test/test_sc/neo_type_test/ImplicitCastTransactionGetHash.py
boa3_test/test_sc/typing_test/CastMismatchedType.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/examples_tests/test_amm.py
boa3_test/tests/examples_tests/test_nep5.py

#454 
Fixed the evaluation for changing jump instructions to their larger equivalents.
In #454 the problem was that the compiler was marking the `else` jump to itself.
In the end, the generated .nef didn't have the jump and it was executing the instructions of both `if` and `else` when it should execute `if`'s only
Use a control flow statement with sufficient instructions to change its JMP assembly instruction to the larger JMP_L equivalent
Fo example: the outer else in this code:
https://github.com/CityOfZion/neo3-boa/blob/adc30a15de93958fc967a0a7eb6a351eb2126ac4/boa3_test/test_sc/if_test/IfWithInnerWhile.py#L5-L31
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/adc30a15de93958fc967a0a7eb6a351eb2126ac4/boa3_t …

Fixed logic for changing small jumps to large jumps

---

boa3/compiler/filegenerator.py
boa3_test/test_sc/generation_test/GenerationWithStaticVariables.py
boa3_test/tests/compiler_tests/test_file_generation.py

#433
Included the field `'static-variables'` in the `.nefdbgnfo` file generation to be compatible with [Neo Debug Info v1.2 format](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md#v12-format-draft)
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/32c2ee86adbdc5c00e20bc8ec15bedd65dbc51f9/boa3_test/tests/compiler_tests/test_file_generation.py#L285-L310
**Platform:**

Update debug info file generation

---

boa3/analyser/astoptimizer.py
boa3/analyser/optimizer/Operation.py
boa3/model/operation/binary/arithmetic/addition.py
boa3/model/operation/binary/arithmetic/multiplication.py
boa3/model/operation/binary/binaryoperation.py
boa3_test/test_sc/arithmetic_test/ConcatBytesVariablesAndConstants.py
boa3_test/test_sc/arithmetic_test/ConcatStringVariablesAndConstants.py
boa3_test/tests/compiler_tests/test_arithmetic.py

Fixed the problem in code optimization that was changing the order of the operands in `str` and `bytes` concatenation
https://github.com/CityOfZion/neo3-boa/blob/1484602d45a8f1391a750ff28cdeb38e82ed751c/boa3_test/test_sc/arithmetic_test/ConcatBytesVariablesAndConstants.py#L10-L25
https://github.com/CityOfZion/neo3-boa/blob/1484602d45a8f1391a750ff28cdeb38e82ed751c/boa3_test/test_sc/arithmetic_test/ConcatStringVariablesAndConstants.py#L5-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1484602d45a8f1391a750ff28cdeb38e82ed751c/boa3_test/tests/compiler_tests/test_arithmetic.py#L263-L285
**Platform:**

Fix concat optimization changing order

---

boa3/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/updatemethod.py
boa3_test/test_sc/interop_test/UpdateContract.py
boa3_test/test_sc/interop_test/contract/UpdateContract.py
boa3_test/test_sc/interop_test/contract/UpdateContractTooManyArguments.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py

#276 
Added the `data` parameter in the `update_contract()` function.
The new signature is `update_contract(nef_file: bytes, manifest: bytes, data: Any = None)`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7082b044a478a65939900e45e98d65a8807082f8/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L162-L179
**Platform:**

Add a new signature to update_contract() interop

---

boa3_test/test_sc/bytes_test/UInt160Bytes.py
boa3_test/test_sc/bytes_test/UInt160Int.py
boa3_test/test_sc/bytes_test/UInt256Bytes.py
boa3_test/test_sc/bytes_test/UInt256Int.py
boa3_test/tests/compiler_tests/test_bytes.py

#446 
The issue was already fixed when I tried it. Just added some tests for UInt160 and UInt256.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e89ac3d16483a8296dc08fc0fc722f0ee1296437/boa3_test/tests/compiler_tests/test_bytes.py#L530-L564
**Platform:**

UInt256 not working in runtime

---

boa3/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/createmethod.py
boa3_test/test_sc/interop_test/contract/CreateContract.py
boa3_test/test_sc/interop_test/contract/CreateContractTooManyArguments.py
boa3_test/test_sc/interop_test/contract/NewContract.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py

#277 
Added the `data` parameter in the `create_contract()` function.
The new signature is `create_contract(nef_file: bytes, manifest: bytes, data: Any = None)`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/39dff843aa71df2a8f4f185e3a6d9849d8b873f5/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L137-L159
**Platform:**

Add a new signature to create_contract() interop

---

.circleci/config.yml
boa3/neo/smart_contract/notification.py
boa3_test/examples/wrapped_neo.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/examples_tests/test_HTLC.py
boa3_test/tests/examples_tests/test_NEP17.py
boa3_test/tests/examples_tests/test_wrapped_neo.py
boa3_test/tests/test_classes/block.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_classes/transaction.py

#451
There were an inconsistency between TestEngine transactions output and the conversion of those transactions to the blocks in the TestEngine input. Updated in [simplitech/neo-devpack-dotnet](https://github.com/simplitech/neo-devpack-dotnet/tree/test-engine-executable) and fixed the issues in the boa side.
```
path = 'path/to/a/smart/contract.py'
engine = TestEngine()
engine.increase_block()
self.run_smart_contract(engine, path, 'some_method', 1000)
txs = engine.get_transactions()
self.assertGreater(len(txs), 0)
tx_hash = txs[0].hash
result = self.run_smart_contract(engine, path, 'get_transaction', tx_hash)
```
The last instruction resulted in `None` even though the transaction existed. It was a problem with …

Transactions are not being properly saved in the storage

---

.circleci/config.yml
boa3/analyser/astanalyser.py
boa3/model/type/typingmethod/casttypemethod.py
boa3_test/test_sc/interop_test/contract/CallScriptHashWithCast.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_typing.py
boa3_test/tests/test_classes/testengine.py

#469
Fixed the problem of including more DROP instructions than it should. This was causing runtime errors.
The issue was with the implementation of `CastTypeMethod`, which didn't overwrite the method `args_on_stack` from `Method`, causing an error in the simulation of the evaluation stack during the code generation.
https://github.com/CityOfZion/neo3-boa/blob/843f313643633095e47346036ed67002e628c76a/boa3_test/test_sc/interop_test/contract/CallScriptHashWithCast.py#L9-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/843f313643633095e47346036ed67002e628c76a/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L42-L57
**Platform:**

Fix unexpected double DROPs

---

boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/getblocktimemethod.py
boa3/model/builtin/interop/runtime/getplatformmethod.py
boa3_test/examples/HTLC.py
boa3_test/test_sc/arithmetic_test/ConcatBytesVariablesAndConstants.py
boa3_test/test_sc/interop_test/runtime/BlockTime.py
boa3_test/test_sc/interop_test/runtime/BlockTimeCantAssign.py
boa3_test/test_sc/interop_test/runtime/GetPlatform.py
boa3_test/test_sc/interop_test/runtime/GetPlatformCantAssign.py
boa3_test/test_sc/interop_test/runtime/Platform.py
boa3_test/test_sc/interop_test/runtime/PlatformCantAssign.py
boa3_test/test_sc/interop_test/runtime/RuntimeBoa2Test.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/examples_tests/test_HTLC.py
docs/source/tutorials.rst

#443 
Changed `get_time` and `get_platform` to `time` and `platform`.
**Platform:**

Change get_time and get_platform

---

boa3/analyser/astanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/model/builtin/interop/interop.py
boa3/model/package.py
boa3_test/test_sc/interop_test/binary/ImportBinary.py
boa3_test/test_sc/interop_test/blockchain/ImportBlockchain.py
boa3_test/test_sc/interop_test/contract/ImportContract.py
boa3_test/test_sc/interop_test/crypto/ImportCrypto.py
boa3_test/test_sc/interop_test/iterator/ImportIterator.py
boa3_test/test_sc/interop_test/json/ImportJson.py
boa3_test/test_sc/interop_test/runtime/ImportRuntime.py
boa3_test/test_sc/interop_test/storage/ImportStorage.py
boa3_test/tests/compiler_tests/test_interop/test_binary.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py
boa3_test/tests/compiler_tests/test_interop/test_json.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

#261 
Added a Package class and some extra requirements to make it work on the compiler.
It's now possible to use ` from boa3.builtin.interop import {subpackage}`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/308c606bdd53e883b5fff40230315a8475641f88/boa3_test/tests/compiler_tests/test_interop/test_binary.py#L361-L369
https://github.com/CityOfZion/neo3-boa/blob/308c606bdd53e883b5fff40230315a8475641f88/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L305-L326
https://github.com/CityOfZion/neo3-boa/blob/308c606bdd53e883b5fff40230315a8475641f88/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L363-L381
https://github.com/CityOfZion/neo3-boa/blob/308c606bdd53e883b5fff40230315a8475641f8 …

Import packages from interop packages

---

boa3/builtin/interop/storage/storagecontext.py
boa3/model/builtin/interop/storage/storagecontext/storagecontextasreadonlymethod.py
boa3/model/builtin/interop/storage/storagecontext/storagecontexttype.py
boa3_test/test_sc/interop_test/storage/StorageAsReadOnly.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

#279 
Use the instance method on a Storage Context, e.g., `get_context().as_read_only`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8fb49365680d9e46f9e1d1d600219805499f3182/boa3_test/tests/compiler_tests/test_interop/test_storage.py#L649-L676
**Platform:**

Implement Storage AsReadOnly Interop

---

boa3/analyser/astoptimizer.py
boa3_test/test_sc/string_test/StringWithDoubleQuotes.py
boa3_test/tests/compiler_tests/test_string.py

#447
The main issue that raised the compiler errors reported in #447 was fixed on #457. 
Changed the validation in `parse_to_node` and included a unit test to ensure that the problem is solved
```python
@public
def string_test(str1: str, str2: str) -> str:
return '"' + str1 + '"test_symbol":' + str2 + '}"'
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3ab62446235fc6e1d50da3a215c43966e9cbfa4f/boa3_test/tests/compiler_tests/test_string.py#L198-L209
**Platform:**

Fixed issue with strings in the optimizer

---

.circleci/config.yml
boa3/analyser/astanalyser.py
boa3/model/builtin/method/reversedmethod.py
boa3_test/test_sc/class_test/NotificationGetVariables.py
boa3_test/test_sc/interop_test/runtime/GetNotifications.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/test_classes/binaryserializer/__init__.py
boa3_test/tests/test_classes/storage.py
boa3_test/tests/test_classes/testengine.py

Updated the TestEngine version used for testing to be able to properly test smart contracts that were updated with `update_contract`
Fixed the contract id used by boa's TestEngine interface
**Platform:**

Update TestEngine to test updated contracts

---

boa3/builtin/interop/storage/__init__.py
boa3/builtin/interop/storage/findoptions.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/storage/__init__.py
boa3/model/builtin/interop/storage/findoptionstype.py
boa3/model/builtin/interop/storage/storagefindmethod.py
boa3_test/test_sc/interop_test/storage/StorageFindWithOptions.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

#260
Included an optional arguments `options` to the `storage.find` method
https://github.com/CityOfZion/neo3-boa/blob/0ce7dff16a0e502767ec831dd0c2465ece5b68d2/boa3_test/test_sc/interop_test/storage/StorageFindWithOptions.py#L9-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0ce7dff16a0e502767ec831dd0c2465ece5b68d2/boa3_test/tests/compiler_tests/test_interop/test_storage.py#L535-L540
**Platform:**

Add FindOptions options parameter to find()

---

boa3/builtin/interop/storage/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/storage/__init__.py
boa3/model/builtin/interop/storage/storagegetreadonlycontextmethod.py
boa3_test/test_sc/interop_test/storage/StorageGetReadOnlyContext.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

#280
Implement Storage GetReadOnlyContext Interop.
https://github.com/CityOfZion/neo3-boa/blob/30fab56ed4412ea573aed4b97e184655f4e72f1e/boa3_test/test_sc/interop_test/storage/StorageGetReadOnlyContext.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/30fab56ed4412ea573aed4b97e184655f4e72f1e/boa3_test/tests/compiler_tests/test_interop/test_storage.py#L451-L463
**Platform:**

Implement Storage GetReadOnlyContext Interop

---

boa3/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/__init__.py
boa3/model/builtin/interop/contract/createstandardaccountmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/contract/CreateStandardAccount.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py

#283 
Call `create_standard_account()`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1ba466c7d3bc9fd16e8d523145376a69fed09dd5/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L403-L428
**Platform:**

Implement Contract CreateStandardAccount Interop

---

boa3/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/currentindexmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/blockchain/CurrentIndex.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py

#495 
Call `current_index`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/72b7601e9422064375c322a02d8483e35a46c5e0/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L409-L418
**Platform:**

Implement LedgerContract currentIndex

---

boa3/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/__init__.py
boa3/model/builtin/interop/binary/base58checkdecodemethod.py
boa3/model/builtin/interop/binary/base58checkencodemethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/binary/Base58CheckDecode.py
boa3_test/test_sc/interop_test/binary/Base58CheckDecodeMismatchedType.py
boa3_test/test_sc/interop_test/binary/Base58CheckEncode.py
boa3_test/test_sc/interop_test/binary/Base58CheckEncodeMismatchedType.py
boa3_test/tests/compiler_tests/test_interop/test_binary.py

#499 
Call `base58_check_decode` or base58_check_encode`` .
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/9489388338a5a537c15385f2a823071fbb676ed4/boa3_test/tests/compiler_tests/test_interop/test_binary.py#L134-L191
**Platform:**

Implement StdLib Base58Check Encode and Decode

---

boa3/compiler/codegenerator/codegenerator.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/strsplitmethod.py
boa3_test/test_sc/built_in_methods_test/StrSplit.py
boa3_test/test_sc/built_in_methods_test/StrSplitSeparatorDefault.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#502 
Use `"a string".split()`. 
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1639d5ed98a7a753fa67d3f55ffe4cdb048bf7c2/boa3_test/tests/compiler_tests/test_builtin_method.py#L964-L987
**Platform:**
The maxsplit parameter used on Python3 wasn't implemented in this issue. It will be implemented at #515

Implement str split method

---

boa3/builtin/interop/__init__.py
boa3/builtin/interop/contract/contract.py
boa3/builtin/interop/contract/contractmanifest.py
boa3/builtin/interop/runtime/notification.py
boa3/model/builtin/interop/contract/contractmanifest/__init__.py
boa3/model/builtin/interop/contract/contractmanifest/contractabitype.py
boa3/model/builtin/interop/contract/contractmanifest/contracteventdescriptortype.py
boa3/model/builtin/interop/contract/contractmanifest/contractgrouptype.py
boa3/model/builtin/interop/contract/contractmanifest/contractmanifesttype.py
boa3/model/builtin/interop/contract/contractmanifest/contractmethoddescriptortype.py
boa3/model/builtin/interop/contract/contractmanifest/contractparameterdefinitiontype.py
boa3/model/builtin/interop/contract/contractmanifest/contractparametertype.py
boa3/model/builtin/interop/contract/contractmanifest/contractpermissiondescriptortype.py
boa3/model/builtin/interop/contract/contractmanifest/contractpermissiontype.py
boa3/model/builtin/interop/contract/contracttype.py
boa3/model/builtin/interop/interop.py
boa3/neo/vm/type/ContractParameterType.py
boa3_test/tests/compiler_tests/test_neo_types.py
boa3_test/tests/test_classes/contract/neomethodstruct.py
boa3_test/tests/test_classes/contract/neostruct.py
docs/source/boa3/builtin/interop/contract/boa3-builtin-interop-contract-callflags.rst
docs/source/boa3/builtin/interop/contract/boa3-builtin-interop-contract-contract.rst
docs/source/boa3/builtin/interop/contract/boa3-builtin-interop-contract-contractmanifest.rst
docs/source/boa3/builtin/interop/contract/boa3-builtin-interop-contract.rst

#467
Implemented the ContractManifest classes:
- ContractManifest
- ContractAbi
- ContractPermission
- ContractPermissionDescriptor
- ContractMethodDescriptor
- ContractEventDescriptor
- ContractParameterDefinition
- ContractParameterType
- ContractGroup
https://github.com/CityOfZion/neo3-boa/blob/bfa846c572f13833ffba11094dc4a4419852f2c4/boa3/builtin/interop/contract/contractmanifest.py#L7-L187
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bfa846c572f13833ffba11094dc4a4419852f2c4/boa3_test/tests/compiler_tests/test_neo_types.py#L270-L288
**Platform:**

Implement ContracManifest class and its attributes types

---

boa3/builtin/interop/__init__.py
boa3/model/builtin/interop/oracle/oraclegetpricemethod.py
boa3/model/builtin/interop/oracle/oracletype.py
boa3_test/test_sc/interop_test/native_contracts/OracleGetPrice.py
boa3_test/tests/compiler_tests/test_interop/test_native_contract.py

#496 
Call `Oracle.get_price()`.
**Tests**
A clear and concise description of how you tested it.
**Platform:**

Implement Oracle getPrice

---

boa3/analyser/typeanalyser.py
boa3_test/test_sc/logical_test/AugmentedAssignmentOperators.py
boa3_test/tests/compiler_tests/test_logical.py

#244
The logic that accepts augmented assignment operators was already working, just removed an `if` at the typeanalyser and added a test.
https://github.com/CityOfZion/neo3-boa/blob/8211b41374a7bd97cafd1db6de57e8658d524aa2/boa3_test/test_sc/logical_test/AugmentedAssignmentOperators.py#L1-L31
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8211b41374a7bd97cafd1db6de57e8658d524aa2/boa3_test/tests/compiler_tests/test_logical.py#L437-L474
**Platform:**

Binary logic Augmented assignment operators

---

boa3/analyser/typeanalyser.py
boa3/model/__init__.py
boa3/model/builtin/interop/contract/callmethod.py
boa3/model/builtin/interop/storage/storagedeletemethod.py
boa3/model/builtin/interop/storage/storagefindmethod.py
boa3/model/builtin/interop/storage/storagegetmethod.py
boa3/model/builtin/interop/storage/storageputmethod.py
boa3/model/callable.py
boa3_test/test_sc/built_in_methods_test/PrintNoArgs.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#523
Fixed the issue with varargs defaults values that was raising a mismatched types error
https://github.com/CityOfZion/neo3-boa/blob/a7c133f50e80d9ee59ecb00e7c6bf181900497b3/boa3_test/test_sc/built_in_methods_test/PrintNoArgs.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/a7c133f50e80d9ee59ecb00e7c6bf181900497b3/boa3_test/tests/compiler_tests/test_builtin_method.py#L620-L625
**Platform:**

Fix error when using empty vararg

---

boa3/model/builtin/method/maxmethod.py
boa3_test/test_sc/built_in_methods_test/MaxIntMoreArguments.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#266 
Made it so that it's now possible to use more than 2 ints when using `max`.
Call `max()`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/b10ce14e0c2a3e73798bdb02b480dda8448b8b33/boa3_test/tests/compiler_tests/test_builtin_method.py#L810-L817
**Platform:**
Using `max` with `str` and `bytes` was not implemented in this issue.

Complement max builtin

---

boa3/model/builtin/method/minmethod.py
boa3_test/test_sc/built_in_methods_test/MinIntMoreArguments.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#267 
Made it so that it's now possible to use more than 2 ints when using `min`.
https://github.com/CityOfZion/neo3-boa/blob/f9450660caee691857c386844b6f6b7ef0f23c00/boa3_test/test_sc/built_in_methods_test/MinIntMoreArguments.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f9450660caee691857c386844b6f6b7ef0f23c00/boa3_test/tests/compiler_tests/test_builtin_method.py#L837-L844
**Platform:**
Using `min` with `str` and `bytes` was not implemented in this issue.

Complement min builtin

---

boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator/__init__.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/compiler/codegenerator/initstatementsvisitor.py
boa3/compiler/filegenerator.py
boa3/exception/CompilerError.py
boa3/model/builtin/builtin.py
boa3/model/builtin/internal/innerdeploymethod.py
boa3/model/builtin/internal/internalmethod.py
boa3/model/builtin/interop/contract/__init__.py
boa3/model/type/itype.py
boa3/model/variable.py
boa3_test/test_sc/boa_built_in_methods_test/DeployDef.py
boa3_test/test_sc/boa_built_in_methods_test/DeployDefWrongSignature.py
boa3_test/test_sc/variable_test/GlobalAssignmentInFunctionWithArgument.py
boa3_test/test_sc/variable_test/GlobalMultipleAssignments.py
boa3_test/tests/compiler_tests/test_boa_builtin_method.py
boa3_test/tests/compiler_tests/test_variable.py

#265
Changed the instructions related to module variables that are modified by functions to be able to persist the updated values, binding them with the contract storage.
https://github.com/CityOfZion/neo3-boa/blob/7e30bcc70da6b1ca41a160276ae1c174e6b0406b/boa3_test/test_sc/variable_test/GlobalAssignmentInFunctionWithArgument.py#L4-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7e30bcc70da6b1ca41a160276ae1c174e6b0406b/boa3_test/tests/compiler_tests/test_variable.py#L629-L646
https://github.com/CityOfZion/neo3-boa/blob/7e30bcc70da6b1ca41a160276ae1c174e6b0406b/boa3_test/tests/compiler_tests/test_variable.py#L481-L495
**Platform:**

Bind storage to module variables

---

boa3/model/builtin/interop/runtime/getnotificationsmethod.py
boa3/model/imports/builtin.py

#539
The issue was in the internal symbols search logic.
When the symbol is not in a package and the parent package has also been fully searched, it was raising an error because it tried to continue the search in the parent
**Tests**
Rerun all unit tests using the latest commits from [development](https://github.com/CityOfZion/neo3-boa/tree/5edeb1ac0a5d5ce05f89df58680900753bb81f77) and [#506](https://github.com/CityOfZion/neo3-boa/tree/d733012d32feba8060110be5526d1957213867db) branches.
**Platform:**

Fixed search for internal symbols

---

boa3/builtin/interop/crypto/__init__.py
boa3/model/builtin/interop/crypto/__init__.py
boa3/model/builtin/interop/crypto/checksigmethod.py
boa3/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/crypto/CheckMultisig.py
boa3_test/test_sc/interop_test/crypto/CheckSig.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py

#491 
https://github.com/CityOfZion/neo3-boa/blob/02c7d8a24a3c1ed0a60d8126e289c513d689dc0d/boa3_test/test_sc/interop_test/crypto/CheckSig.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/02c7d8a24a3c1ed0a60d8126e289c513d689dc0d/boa3_test/tests/compiler_tests/test_interop/test_crypto.py#L169-L201
**Platform:**
Also changed the syscall at [checkmultisigmethod.py](https://github.com/CityOfZion/neo3-boa/blob/02c7d8a24a3c1ed0a60d8126e289c513d689dc0d/boa3/model/builtin/interop/crypto/checkmultisigmethod.py) and its test.

Implement Crypto CheckSig Interop

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/countmethod.py
boa3_test/test_sc/built_in_methods_test/CountListBytes.py
boa3_test/test_sc/built_in_methods_test/CountListDifferentNonPrimitiveTypes.py
boa3_test/test_sc/built_in_methods_test/CountListDifferentTypes.py
boa3_test/test_sc/built_in_methods_test/CountListEmpty.py
boa3_test/test_sc/built_in_methods_test/CountListInt.py
boa3_test/test_sc/built_in_methods_test/CountListStr.py
boa3_test/test_sc/built_in_methods_test/CountRange.py
boa3_test/test_sc/built_in_methods_test/CountStr.py
boa3_test/test_sc/built_in_methods_test/CountTupleBytes.py
boa3_test/test_sc/built_in_methods_test/CountTupleDifferentNonPrimitiveTypes.py
boa3_test/test_sc/built_in_methods_test/CountTupleDifferentTypes.py
boa3_test/test_sc/built_in_methods_test/CountTupleEmpty.py
boa3_test/test_sc/built_in_methods_test/CountTupleInt.py
boa3_test/test_sc/built_in_methods_test/CountTupleStr.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#256 
Use `.count(value)` in a list, tuple or range.
https://github.com/CityOfZion/neo3-boa/blob/87207cd11e5111e5e72c58112ef14587e10fa648/boa3_test/test_sc/built_in_methods_test/CountListInt.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/87207cd11e5111e5e72c58112ef14587e10fa648/boa3_test/tests/compiler_tests/test_builtin_method.py#L1014-L1136
**Platform:**
The method currently does not work for `str.count()` or when using to count non-primitive types in the sequence.

Implement Sequence count for list and tuple 

---

boa3/model/operation/binary/relational/identity.py
boa3/model/operation/binary/relational/notidentity.py
boa3_test/test_sc/relational_test/BoolIdentity.py
boa3_test/test_sc/relational_test/BoolNotIdentity.py
boa3_test/test_sc/relational_test/ListIdentity.py
boa3_test/test_sc/relational_test/ListNotIdentity.py
boa3_test/test_sc/relational_test/MixedIdentity.py
boa3_test/test_sc/relational_test/NoneIdentity.py
boa3_test/test_sc/relational_test/NoneNotIdentity.py
boa3_test/test_sc/relational_test/NumNotIdentity.py
boa3_test/test_sc/relational_test/StrIdentity.py
boa3_test/test_sc/relational_test/StrNotIdentity.py
boa3_test/test_sc/relational_test/TupleIdentity.py
boa3_test/test_sc/relational_test/TupleNotIdentity.py
boa3_test/tests/compiler_tests/test_relational.py

#388 
Added support to `is` and `is not` keywords.
https://github.com/CityOfZion/neo3-boa/blob/d0e8d4a7b28d884d5ea6829b0f5fd26b96123b07/boa3_test/test_sc/relational_test/ListIdentity.py#L1-L17
https://github.com/CityOfZion/neo3-boa/blob/d0e8d4a7b28d884d5ea6829b0f5fd26b96123b07/boa3_test/test_sc/relational_test/ListNotIdentity.py#L1-L17
**Tests**
Tested them at boa3_test/tests/compiler_tests/[test_relational.py](https://github.com/CityOfZion/neo3-boa/blob/d0e8d4a7b28d884d5ea6829b0f5fd26b96123b07/boa3_test/tests/compiler_tests/test_relational.py).
**Platform:**

 Add support to the 'is' keyword

---

.circleci/config.yml
boa3/builtin/interop/blockchain/block.py
boa3/model/builtin/interop/blockchain/blocktype.py
boa3_test/test_sc/interop_test/blockchain/Block.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py

#547 
Included `nonce` to the Block class.
https://github.com/CityOfZion/neo3-boa/blob/8839208ac3ee09d7f02bc84a8fd645abaa257b89/boa3_test/test_sc/interop_test/blockchain/Block.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8839208ac3ee09d7f02bc84a8fd645abaa257b89/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L20-L39
**Platform:**
Also changed the commit targeted for the checkout.

Include variable to Block class

---

boa3/builtin/interop/__init__.py
boa3/builtin/interop/oracle/__init__.py
boa3/builtin/interop/oracle/oracleresponsecode.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/oracle/__init__.py
boa3/model/builtin/interop/oracle/oraclerequestmethod.py
boa3/model/builtin/interop/oracle/oracleresponsecodetype.py
boa3/model/builtin/interop/oracle/oracletype.py
boa3/neo3/network/payloads/__init__.py
boa3/neo3/network/payloads/oracleresponsecode.py
boa3_test/test_sc/interop_test/oracle/ImportInteropOracle.py
boa3_test/test_sc/interop_test/oracle/OracleGetPrice.py
boa3_test/test_sc/interop_test/oracle/OracleRequestCall.py
boa3_test/test_sc/interop_test/oracle/OracleRequestCallCallbackMismatchedType.py
boa3_test/test_sc/interop_test/oracle/OracleRequestFilterMismatchedType.py
boa3_test/test_sc/interop_test/oracle/OracleRequestGasMismatchedType.py
boa3_test/test_sc/interop_test/oracle/OracleRequestUrlMismatchedType.py
boa3_test/tests/compiler_tests/test_interop/test_oracle.py

#543 
Import OracleResponseCode from boa3.builtin.interop.oracle.
**Platform:**
Also added a new folder called `oracle`, because they reference a NativeContract

Implement OracleRequestCode enum

---

boa3/builtin/interop/__init__.py
boa3/builtin/interop/oracle/__init__.py
boa3_test/test_sc/interop_test/oracle/ImportOracle.py
boa3_test/test_sc/interop_test/policy/ImportInteropPolicy.py
boa3_test/test_sc/interop_test/policy/ImportPolicy.py
boa3_test/test_sc/interop_test/role/ImportInteropRole.py
boa3_test/test_sc/interop_test/role/ImportRole.py
boa3_test/tests/compiler_tests/test_interop/test_oracle.py
boa3_test/tests/compiler_tests/test_interop/test_policy.py
boa3_test/tests/compiler_tests/test_interop/test_role.py

#568 
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/a0026eda1919be1d1a336ddbe7cd0c0cfae4a7df/boa3_test/tests/compiler_tests/test_interop/test_role.py#L45-L101
https://github.com/CityOfZion/neo3-boa/blob/a0026eda1919be1d1a336ddbe7cd0c0cfae4a7df/boa3_test/tests/compiler_tests/test_interop/test_policy.py#L68-L80
**Platform:**
Also added a `ImportOracle` test.

Create unit tests when importing role and policy interops from interop

---

boa3/compiler/filegenerator.py

`features` should be an empty object according to NEP-15, instead of an array
https://github.com/CityOfZion/neo3-boa/issues/578
Changed `features` to be an empty object instead of an array
Steps to reproduce the behaviour:
Compile any contract
Examine the manifest to see `features` is an array
**Tests**
Manually compiled contract to verify `features` in manifest is now an object
None
**Platform:**
All

change features to empty object

---

boa3/analyser/astoptimizer.py
boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/type/classes/userclass.py
boa3_test/test_sc/class_test/UserClassWithStaticMethodFromClassWithSameNameMethod.py
boa3_test/test_sc/function_test/CallFunctionsWithSameNameInDifferentScopes.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_function.py

#581 
Fixed the issue caused when naming functions in different scopes with the same name
```python
class Example:
@staticmethod
def test() -> int:
return 10
@public
def test() -> int:
return 20
@public
def result() -> Tuple[int, int]:
a = Example.test()
b = test()
c = (a, b)
return c
```
This example compiles, but both `a` and `b` calls the same method.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/b569c5a24e57d7bae5e71ac5f0fd20d8a371f3fc/boa3_test/tests/compiler_tests/test_function.py#L1031-L1036
https://github.com/CityOfZion/neo3-boa/blob/b569c5a24e57d7bae5e71ac5f0fd20d8a371f3fc/boa3_test/tests/compiler_tests/test_class.py#L106-L112
**Platform:**

Functions with same name not working

---

boa3_test/tests/test_classes/testengine.py

#593
Changed the TestEngine run to filter `bytes` values to `UInt160` to generate correctly TestEngine executable input.
```python
neo_script_hash = b'\xf5c\xea@\xbc(=M\x0e\x05\xc4\x8e\xa3\x05\xb3\xf2\xa0s@\xef'
engine = TestEngine()
result = engine.run(neo_script_hash, 'some_method', arg0, arg1, arg2)
```
**Tests**
Rerun the unit tests
**Platform:**

Investigate NullPointerException when using TestEngine to call Neo registerCandidates

---

boa3/builtin/interop/stdlib/__init__.py

#589 
Added parameters and return to `base58_check_encode` and `base58_check_decode` descriptions.
**Platform:**
Also corrected the descriptions on `base58encode` and `base58decode`.

Update base58_check_encode and base58_check_decode's descriptions

---

boa3/builtin/nativecontract/rolemanagement.py
boa3/model/builtin/native/__init__.py
boa3/model/builtin/native/nativecontract.py
boa3/model/builtin/native/rolemanagementclass.py
boa3_test/test_sc/interop_test/role/GetDesignatedByRoleTooFewArguments.py
boa3_test/test_sc/interop_test/role/GetDesignatedByRoleTooManyArguments.py
boa3_test/test_sc/native_test/rolemanagement/GetDesignatedByRole.py
boa3_test/test_sc/native_test/rolemanagement/GetDesignatedByRoleTooFewArguments.py
boa3_test/test_sc/native_test/rolemanagement/GetDesignatedByRoleTooManyArguments.py
boa3_test/tests/compiler_tests/test_interop/test_role.py
boa3_test/tests/compiler_tests/test_native/test_rolemanagement.py

#611 
Implemented an interface for interacting with the RoleManagement native contract in a clearer way.
https://github.com/CityOfZion/neo3-boa/blob/2810402ac0111c632e0835bb8c14a1ff0eae15a1/boa3/builtin/nativecontract/rolemanagement.py#L1-L23
https://github.com/CityOfZion/neo3-boa/blob/2810402ac0111c632e0835bb8c14a1ff0eae15a1/boa3_test/test_sc/native_test/rolemanagement/GetDesignatedByRole.py#L1-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/2810402ac0111c632e0835bb8c14a1ff0eae15a1/boa3_test/tests/compiler_tests/test_native/test_rolemanagement.py#L1-L51
**Platform:**
Also added more tests to the role interop.

Implement interface for RoleManagement native contract

---

boa3/builtin/nativecontract/contractmanagement.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/builtin/native/__init__.py
boa3/model/builtin/native/contractmanagementclass.py
boa3/model/builtin/native/nativecontract.py
boa3_test/test_sc/native_test/contractmanagement/DeployContract.py
boa3_test/test_sc/native_test/contractmanagement/DeployContractTooFewArguments.py
boa3_test/test_sc/native_test/contractmanagement/DeployContractTooManyArguments.py
boa3_test/test_sc/native_test/contractmanagement/DestroyContract.py
boa3_test/test_sc/native_test/contractmanagement/DestroyContractTooManyArguments.py
boa3_test/test_sc/native_test/contractmanagement/GetContract.py
boa3_test/test_sc/native_test/contractmanagement/GetMinimumDeploymentFee.py
boa3_test/test_sc/native_test/contractmanagement/GetMinimumDeploymentFeeTooManyArguments.py
boa3_test/test_sc/native_test/contractmanagement/UpdateContract.py
boa3_test/test_sc/native_test/contractmanagement/UpdateContractTooFewArguments.py
boa3_test/test_sc/native_test/contractmanagement/UpdateContractTooManyArguments.py
boa3_test/tests/compiler_tests/test_native/test_contract_management.py
boa3_test/tests/compiler_tests/test_native/test_policy.py

#602
Implemented an interface for interacting with the ContractManagement native contract in a clearer way.
https://github.com/CityOfZion/neo3-boa/blob/b9800cdaf82e606f2bdb77b0fc63d3905356e018/boa3/builtin/nativecontract/contractmanagement.py#L7-L26
https://github.com/CityOfZion/neo3-boa/blob/b9800cdaf82e606f2bdb77b0fc63d3905356e018/boa3_test/test_sc/native_test/contractmanagement/DeployContract.py#L8-L10
https://github.com/CityOfZion/neo3-boa/blob/b9800cdaf82e606f2bdb77b0fc63d3905356e018/boa3_test/test_sc/native_test/contractmanagement/GetContract.py#L7-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/b9800cdaf82e606f2bdb77b0fc63d3905356e018/boa3_test/tests/compiler_tests/test_native/test_contract_managemen …

Implement interface for ContractManagement native contract

---

.circleci/config.yml

#625 
Fixed issue with CircleCI's Python 3.8 workflow that didn't even begin the tests
**Platform:**

Investigate Circle CI errors with Python 3.8

---

boa3/analyser/typeanalyser.py
boa3/builtin/contract/__init__.py
boa3/builtin/nativecontract/neo.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/maxbytestringmethod.py
boa3/model/builtin/method/maxintmethod.py
boa3/model/builtin/method/maxmethod.py
boa3/model/builtin/native/neo_contract_methods/getcandidatesmethod.py
boa3_test/test_sc/built_in_methods_test/MaxBytes.py
boa3_test/test_sc/built_in_methods_test/MaxBytesMoreArguments.py
boa3_test/test_sc/built_in_methods_test/MaxStr.py
boa3_test/test_sc/built_in_methods_test/MaxStrMoreArguments.py
boa3_test/test_sc/native_test/neo/GetCandidates.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#522
Included `str` and `bytes` as valid types for `max` builtin function
https://github.com/CityOfZion/neo3-boa/blob/0052c941b6523b917b131427c39e6d6c97b8352d/boa3_test/test_sc/built_in_methods_test/MaxStr.py#L5-L6
https://github.com/CityOfZion/neo3-boa/blob/0052c941b6523b917b131427c39e6d6c97b8352d/boa3_test/test_sc/built_in_methods_test/MaxBytesMoreArguments.py#L5-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0052c941b6523b917b131427c39e6d6c97b8352d/boa3_test/tests/compiler_tests/test_builtin_method.py#L824-L888
**Platform:**

Complement max builtin with str and bytes values

---

boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/bytes_test/SliceOmittedWithNegativeStride.py
boa3_test/test_sc/bytes_test/SliceOmittedWithStride.py
boa3_test/test_sc/bytes_test/SliceWithNegativeStride.py
boa3_test/test_sc/bytes_test/SliceWithStride.py
boa3_test/test_sc/list_test/ListSlicingOmittedWithNegativeStride.py
boa3_test/test_sc/list_test/ListSlicingOmittedWithStride.py
boa3_test/test_sc/list_test/ListSlicingWithNegativeStride.py
boa3_test/test_sc/list_test/ListSlicingWithStride.py
boa3_test/test_sc/range_test/RangeSlicingOmittedWithNegativeStride.py
boa3_test/test_sc/range_test/RangeSlicingOmittedWithStride.py
boa3_test/test_sc/range_test/RangeSlicingWithNegativeStride.py
boa3_test/test_sc/range_test/RangeSlicingWithStride.py
boa3_test/test_sc/string_test/StringSlicingOmittedWithNegativeStride.py
boa3_test/test_sc/string_test/StringSlicingOmittedWithStride.py
boa3_test/test_sc/string_test/StringSlicingWithNegativeStride.py
boa3_test/test_sc/string_test/StringSlicingWithStride.py
boa3_test/test_sc/tuple_test/TupleSlicingOmittedWithNegativeStride.py
boa3_test/test_sc/tuple_test/TupleSlicingOmittedWithStride.py
boa3_test/test_sc/tuple_test/TupleSlicingWithNegativeStride.py
boa3_test/test_sc/tuple_test/TupleSlicingWithStride.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_range.py
boa3_test/tests/compiler_tests/test_string.py
boa3_test/tests/compiler_tests/test_tuple.py

#594 
Correctly implemented slicing with negative stride.
https://github.com/CityOfZion/neo3-boa/blob/0da8d1f0d279cc3e56732803673682e8aba92350/boa3_test/test_sc/list_test/ListSlicingWithNegativeStride.py#L1-L61
**Tests**
Bytes:
https://github.com/CityOfZion/neo3-boa/blob/0da8d1f0d279cc3e56732803673682e8aba92350/boa3_test/tests/compiler_tests/test_bytes.py#L242-L484
List:
https://github.com/CityOfZion/neo3-boa/blob/0da8d1f0d279cc3e56732803673682e8aba92350/boa3_test/tests/compiler_tests/test_list.py#L422-L626
Range:
https://github.com/CityOfZion/neo3-boa/blob/0da8d1f0d279cc3e56732803673682e8aba92350/boa3_test/tests/compiler_tests/test_range.py#L363-L572
String: …

Implement sequence slicing with negative stride with start and end

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/minbytestringmethod.py
boa3/model/builtin/method/minintmethod.py
boa3/model/builtin/method/minmethod.py
boa3_test/test_sc/built_in_methods_test/MaxMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/MaxTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/MinBytes.py
boa3_test/test_sc/built_in_methods_test/MinBytesMoreArguments.py
boa3_test/test_sc/built_in_methods_test/MinMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/MinStr.py
boa3_test/test_sc/built_in_methods_test/MinStrMoreArguments.py
boa3_test/test_sc/built_in_methods_test/MinTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/SumMismatchedTypes.py
boa3_test/test_sc/built_in_methods_test/SumTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/SumTooManyParameters.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#529 
Included `str` and `bytes` as valid types for `min` builtin function.
Bytes:
https://github.com/CityOfZion/neo3-boa/blob/25d933879697a5e461850e24738ad2d9168cbeff/boa3_test/test_sc/built_in_methods_test/MinBytes.py#L1-L6
Str:
https://github.com/CityOfZion/neo3-boa/blob/25d933879697a5e461850e24738ad2d9168cbeff/boa3_test/test_sc/built_in_methods_test/MinStr.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/25d933879697a5e461850e24738ad2d9168cbeff/boa3_test/tests/compiler_tests/test_builtin_method.py#L914-L987
**Platform:**
Also removed some unnecessary lines of code on some tests and smart contract tests.

Complement min builtin with str and bytes values

---

boa3/builtin/interop/json/__init__.py
boa3/builtin/nativecontract/stdlib.py
boa3/model/builtin/interop/json/jsondeserializemethod.py
boa3/model/builtin/interop/json/jsonserializemethod.py
boa3_test/test_sc/interop_test/json/JsonDeserialize.py
boa3_test/test_sc/interop_test/json/JsonSerialize.py
boa3_test/test_sc/interop_test/json/JsonSerializeBool.py
boa3_test/test_sc/interop_test/json/JsonSerializeBytes.py
boa3_test/test_sc/interop_test/json/JsonSerializeInt.py
boa3_test/test_sc/interop_test/json/JsonSerializeStr.py
boa3_test/test_sc/native_test/stdlib/JsonDeserialize.py
boa3_test/test_sc/native_test/stdlib/JsonSerialize.py
boa3_test/test_sc/native_test/stdlib/JsonSerializeBool.py
boa3_test/test_sc/native_test/stdlib/JsonSerializeBytes.py
boa3_test/test_sc/native_test/stdlib/JsonSerializeInt.py
boa3_test/test_sc/native_test/stdlib/JsonSerializeStr.py
boa3_test/tests/compiler_tests/test_interop/test_json.py
boa3_test/tests/compiler_tests/test_native/test_stdlib.py

#635 
Change `json_serialize` and `json_deserialize` to:
https://github.com/CityOfZion/neo3-boa/blob/3e974e715f6c17af9b4a2ec5f7273ec36917d039/boa3/builtin/interop/json/__init__.py#L4-L30
https://github.com/CityOfZion/neo3-boa/blob/3e974e715f6c17af9b4a2ec5f7273ec36917d039/boa3_test/test_sc/interop_test/json/JsonSerialize.py#L7-L9
https://github.com/CityOfZion/neo3-boa/blob/3e974e715f6c17af9b4a2ec5f7273ec36917d039/boa3_test/test_sc/interop_test/json/JsonDeserialize.py#L7-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3e974e715f6c17af9b4a2ec5f7273ec36917d039/boa3_test/tests/compiler_tests/test_native/test_stdlib.py#L286-L352
**Platform:**

Change json_serialize and json_deserialize bytes parameters and return to str

---

boa3_test/examples/README.md

#567 
Added a simple description on how to build/test the smart contracts on the examples README.
**Platform:**
Since neo3-boas documentation already explains in full length how to do both tasks, the instructions on this README were deliberately made shorter and simpler, and the documentation was linked if more guidance is needed.

Add details on how to build/test each smart contract example to the new README

---

.circleci/config.yml
boa3_test/tests/test_classes/signer.py
boa3_test/tests/test_classes/testengine.py
boa3_test/tests/test_classes/witnessscope.py

#642
Updated TestEngine interface to include signers with different witness scopes
https://github.com/CityOfZion/neo3-boa/blob/f265cdd91aa486b8bfaece2172d4925e4386f6cc/boa3_test/tests/test_classes/witnessscope.py#L6-L23
```python
from boa3_test.tests.test_classes.witnessscope import WitnessScope
engine = TestEngine()
engine.add_signer_account(account1, WitnessScope.CalledByEntry)
engine.add_signer_account(account2, WitnessScope.Global)
result = engine.run(path, 'Main', account)
```
**Platform:**

Update TestEngine to support different witness scopes

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/uppermethod.py
boa3_test/test_sc/bytes_test/UpperMethod.py
boa3_test/test_sc/string_test/UpperMethod.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_string.py

#670 
Implemented `string.upper()` for ASCII symbols. Extended ASCII symbols such as `áàãâ` were not implemented in this issue.
`bytes.upper()` was also implemented.
https://github.com/CityOfZion/neo3-boa/blob/944f4500f23a97df17027868adb39dcdf8d01ae7/boa3_test/test_sc/string_test/UpperMethod.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/944f4500f23a97df17027868adb39dcdf8d01ae7/boa3_test/tests/compiler_tests/test_string.py#L375-L396
**Platform:**

Add support to String upper method for ASCII symbols

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/popdictmethod.py
boa3/model/builtin/classmethod/popmethod.py
boa3/model/builtin/classmethod/popsequencemethod.py
boa3_test/test_sc/dict_test/DictPop.py
boa3_test/tests/compiler_tests/test_dict.py

#686 
Added support to `dict.pop()` method, however, the `default` parameter was not implemented.
https://github.com/CityOfZion/neo3-boa/blob/d14c598600f29b26765b9b730c71d7dbf36bf354/boa3_test/test_sc/dict_test/DictPop.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d14c598600f29b26765b9b730c71d7dbf36bf354/boa3_test/tests/compiler_tests/test_dict.py#L522-L541
**Platform:**

Add support to Dict pop method

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/startswithmethod.py
boa3_test/test_sc/bytes_test/StartswithBytesMethod.py
boa3_test/test_sc/bytes_test/StartswithBytesMethodDefaultEnd.py
boa3_test/test_sc/bytes_test/StartswithBytesMethodDefaults.py
boa3_test/test_sc/string_test/StartswithStringMethod.py
boa3_test/test_sc/string_test/StartswithStringMethodDefaultEnd.py
boa3_test/test_sc/string_test/StartswithStringMethodDefaults.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_string.py

#673 
Implemented `string.startswith()` and `bytes.startswith()`.
https://github.com/CityOfZion/neo3-boa/blob/f8e2e3b497ca3f2045a80ef49f772377cf25eb29/boa3_test/test_sc/string_test/StartswithStringMethod.py#L1-L6
The `start` and `end` parameters are optionals.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f8e2e3b497ca3f2045a80ef49f772377cf25eb29/boa3_test/tests/compiler_tests/test_string.py#L421-L560
**Platform:**

Add support to String startswith method

---

.circleci/config.yml
README.md
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/compiler/compiler.py
boa3/constants.py
boa3/model/builtin/classmethod/copydictmethod.py
boa3/model/builtin/classmethod/indexmethod.py
boa3_test/test_sc/class_test/UserClassWithPropertyUsingInstanceVariablesFromObject.py
boa3_test/test_sc/dict_test/DictCopy.py
boa3_test/test_sc/dict_test/DictPop.py
boa3_test/test_sc/list_test/Copy.py
boa3_test/test_sc/list_test/CopyBool.py
boa3_test/test_sc/list_test/CopyBytes.py
boa3_test/test_sc/list_test/CopyInt.py
boa3_test/test_sc/list_test/CopyStr.py
docs/source/getting-started.rst

#697
Fixed issues that happened when running boa with Python 3.9.0 and included running the unit tests with Python 3.9.0 in the CircleCI workflow. Also included the current Python and Boa versions in the log for better validation.
Run the unit tests using Python 3.9.0
**Platform:**
- Python version: Python 3.9.0

Support to Python 3.9 

---

boa3/analyser/astanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/builtin/classmethod/appendmethod.py
boa3/model/builtin/interop/contract/callflagstype.py
boa3/model/builtin/interop/contract/contractmanifest/contractparametertype.py
boa3/model/builtin/interop/crypto/namedcurvetype.py
boa3/model/builtin/interop/iterator/iteratortype.py
boa3/model/builtin/interop/oracle/oracleresponsecodetype.py
boa3/model/builtin/interop/role/roletype.py
boa3/model/builtin/interop/runtime/triggertype.py
boa3/model/builtin/interop/storage/findoptionstype.py
boa3/model/builtin/method/isinstancemethod.py
boa3/model/type/classes/classtype.py
boa3/model/type/classes/pythonclass.py
boa3/model/type/collection/icollection.py
boa3/model/type/collection/mapping/mutable/dicttype.py
boa3/model/type/collection/sequence/ecpointtype.py
boa3/model/type/collection/sequence/mutable/mutablesequencetype.py
boa3/model/type/collection/sequence/uint160type.py
boa3/model/type/collection/sequence/uint256type.py
boa3/model/type/primitive/bytestringtype.py
boa3/model/type/primitive/bytestype.py
boa3/model/type/primitive/inttype.py
boa3/model/type/primitive/nonetype.py
boa3/model/type/primitive/primitivetype.py
boa3/model/type/primitive/strtype.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#700
Refactored the native Python types implementations to compile the same way as other classes.
Blocker for class inheritance feature
**Tests**
Rerun the existing unit tests
**Platform:**

Change native types implementation to work with classes

---

boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/callable.py
boa3/model/type/classes/classinitmethoddefault.py
boa3_test/test_sc/class_test/UserClassWithCascadeCreatedBase.py
boa3_test/tests/compiler_tests/test_class.py

#722
Changed the implementation of generated ``__init__`` methods for user-created classes. They were converted to inline assembly code in the same block they were called. Changed to be a separated method in the class block of assembly code.
It fixed the issue with inheritance using classes that inherit others.
https://github.com/CityOfZion/neo3-boa/blob/c9544fec36d58a72de3f44e356dcb333bb1ce424/boa3_test/test_sc/class_test/UserClassWithCascadeCreatedBase.py#L4-L24
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c9544fec36d58a72de3f44e356dcb333bb1ce424/boa3_test/tests/compiler_tests/test_class.py#L303-L368
**Platform:**

Change implementation of implicit class init

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/class_test/UserClassWithClassMethodFromVariable.py
boa3_test/test_sc/class_test/UserClassWithClassVariableFromVariable.py
boa3_test/test_sc/class_test/UserClassWithInstanceMethodFromVariable.py
boa3_test/test_sc/class_test/UserClassWithInstanceVariableFromVariable.py
boa3_test/tests/compiler_tests/test_class.py

#719
Fixed bug with methods called from an user-defined class object stored in a variable
https://github.com/CityOfZion/neo3-boa/blob/19b42533508dff31d27ff71f42256d664c6ff275/boa3_test/test_sc/class_test/UserClassWithInstanceMethodFromVariable.py#L4-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/19b42533508dff31d27ff71f42256d664c6ff275/boa3_test/tests/compiler_tests/test_class.py#L175-L181
https://github.com/CityOfZion/neo3-boa/blob/19b42533508dff31d27ff71f42256d664c6ff275/boa3_test/tests/compiler_tests/test_class.py#L275-L307
**Platform:**

Call methods does not work with variable objects

---

boa3/analyser/astanalyser.py
boa3/analyser/model/functionarguments.py
boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3_test/test_sc/import_test/NotImportedBuiltinFromTypingInArgs.py
boa3_test/test_sc/import_test/NotImportedBuiltinFromTypingInReturn.py
boa3_test/test_sc/import_test/NotImportedBuiltinFromTypingInSubscript.py
boa3_test/test_sc/import_test/NotImportedBuiltinFromTypingInVariable.py
boa3_test/test_sc/import_test/NotImportedBuiltinPublic.py
boa3_test/test_sc/logical_test/MismatchedOperandLogicNot.py
boa3_test/test_sc/logical_test/MismatchedOperandLogicOr.py
boa3_test/tests/compiler_tests/test_import.py

#724 
Added the UnresolvedReference compiler error when trying to use builtins without importing them.
https://github.com/CityOfZion/neo3-boa/blob/35cd39747153836949fa83b6702732fb8341c95e/boa3_test/test_sc/import_test/NotImportedBuiltinPublic.py#L1-L3
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/35cd39747153836949fa83b6702732fb8341c95e/boa3_test/tests/compiler_tests/test_import.py#L319-L330
**Platform:**
Also changed a little bit of the kwargs on FunctionArguments.

Builtin missing imports are not being logged

---

boa3_test/test_sc/interop_test/stdlib/SerializationUserClass.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_interop/test_stdlib.py

#727
Included unit tests to test `serialize` and `deserialize` objects from user-defined classes.
https://github.com/CityOfZion/neo3-boa/blob/534690bebf2441cc0503d38207e0883f76b5b29c/boa3_test/test_sc/interop_test/stdlib/SerializationUserClass.py#L4-L37
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/534690bebf2441cc0503d38207e0883f76b5b29c/boa3_test/tests/compiler_tests/test_interop/test_stdlib.py#L310-L328
**Platform:**

Verify support to user-defined class serialization

---

boa3/analyser/analyser.py
boa3/analyser/astanalyser.py
boa3/analyser/importanalyser.py
boa3/analyser/moduleanalyser.py
boa3/analyser/supportedstandard/standardanalyser.py
boa3/analyser/typeanalyser.py
boa3/exception/CompilerError.py
boa3/exception/CompilerWarning.py
boa3_test/tests/compiler_tests/test_class.py

#734
Fixed the import from packages outside `boa3` package
```python
from objects.example import Example
@public
def new_example() -> Example:
return Example()
```
**Platform:**

Fix issue with importing modules from different packages than current compiling file

---

boa3/model/operation/binary/arithmetic/__init__.py
boa3/model/operation/binary/arithmetic/strbytesmultiplication.py
boa3/model/operation/binaryop.py
boa3_test/test_sc/arithmetic_test/BytesMultiplication.py
boa3_test/test_sc/arithmetic_test/BytesMultiplicationAugmentedAssignment.py
boa3_test/test_sc/arithmetic_test/BytesMultiplicationBuiltinType.py
boa3_test/tests/compiler_tests/test_arithmetic.py

#735 
Changed `strmultiplication.py` to also permit bytes multiplication.
https://github.com/CityOfZion/neo3-boa/blob/69b422e9ddd47e20872fa29fb29b9f77015b8891/boa3_test/test_sc/arithmetic_test/BytesMultiplication.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/69b422e9ddd47e20872fa29fb29b9f77015b8891/boa3_test/tests/compiler_tests/test_arithmetic.py#L661-L712
**Platform:**

UInt160, UInt256, ECPoint only accept int, not bytes

---

boa3/analyser/moduleanalyser.py
boa3_test/test_sc/function_test/NoneFunction.py
boa3_test/test_sc/function_test/NoneFunctionChangingValuesWithReturn.py
boa3_test/test_sc/function_test/NoneFunctionChangingValuesWithoutReturn.py
boa3_test/test_sc/function_test/NoneFunctionPass.py
boa3_test/test_sc/function_test/NoneFunctionReturnNone.py
boa3_test/tests/compiler_tests/test_function.py

#736 
Removed a piece of code to let it be possible to compile a function returning `None` and added some more tests.
https://github.com/CityOfZion/neo3-boa/blob/d3aa84ddcd99f137c7e66055612fd0a77d672235/boa3_test/test_sc/function_test/NoneFunctionChangingValuesWithReturn.py#L1-L15
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d3aa84ddcd99f137c7e66055612fd0a77d672235/boa3_test/tests/compiler_tests/test_function.py#L65-L91
**Platform:**

Function with no return value does not compile

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/exception/CompilerError.py
boa3/model/builtin/method/supermethod.py
boa3/model/callable.py
boa3_test/test_sc/built_in_methods_test/SuperCallMethod.py
boa3_test/test_sc/built_in_methods_test/SuperWithArgs.py
boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithInitWithArgs.py
boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithMoreVariables.py
boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithMoreVariablesWithoutSuperInit.py
boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_class.py

#723
Implemented `super()` calls to support more usages of inheritance. Only `super()` call without arguments is implemented
https://github.com/CityOfZion/neo3-boa/blob/95095ff6a2278d2e80fce42d71a782db3e67fdc2/boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithInitWithArgs.py#L4-L11
https://github.com/CityOfZion/neo3-boa/blob/95095ff6a2278d2e80fce42d71a782db3e67fdc2/boa3_test/test_sc/built_in_methods_test/SuperCallMethod.py#L12-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/95095ff6a2278d2e80fce42d71a782db3e67fdc2/boa3_test/tests/compiler_tests/test_class.py#L404-L430
https://github.com/CityOfZion/neo3-boa/blob/95095ff6a2278d2e80fce42d71a782db3e67fdc2/boa3_test/tests/compiler_tests/test_builtin_meth …

Support to super()

---

boa3/model/operation/binary/arithmetic/__init__.py
boa3/model/operation/binary/arithmetic/listaddition.py
boa3/model/operation/binaryop.py
boa3_test/test_sc/arithmetic_test/ListAddition.py
boa3_test/tests/compiler_tests/test_arithmetic.py

#685 
Added another binary operation to make list addition possible.
https://github.com/CityOfZion/neo3-boa/blob/f3cfbf84fec477197508bbfd45e9d468f111897d/boa3_test/test_sc/arithmetic_test/ListAddition.py#L1-L23
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f3cfbf84fec477197508bbfd45e9d468f111897d/boa3_test/tests/compiler_tests/test_arithmetic.py#L374-L385
**Platform:**

Add support to the + operator using lists

---

boa3/builtin/math.py
boa3/model/builtin/builtin.py
boa3/model/builtin/math/__init__.py
boa3/model/builtin/math/decimalfloor.py
boa3/model/operation/binary/arithmetic/modulo.py
boa3/model/type/math.py
boa3_test/test_sc/arithmetic_test/ModuloAugmentedAssignment.py
boa3_test/test_sc/boa_built_in_methods_test/DecimalFloor.py
boa3_test/test_sc/boa_built_in_methods_test/Sqrt.py
boa3_test/test_sc/boa_built_in_methods_test/SqrtFromMath.py
boa3_test/tests/compiler_tests/test_arithmetic.py
boa3_test/tests/compiler_tests/test_boa_builtin_method.py
boa3_test/tests/compiler_tests/test_for.py
boa3_test/tests/compiler_tests/test_function.py
boa3_test/tests/compiler_tests/test_while.py
docs/source/boa3/builtin/boa3-builtin-math.rst
docs/source/boa3/builtin/boa3-builtins.rst

#663
Implemented an integer alternative for `math.floor` method. This method receives two int arguments, the first being the integer representation of a decimal number and the second the number of decimals to be considered. The number of decimals cannot be negative.
https://github.com/CityOfZion/neo3-boa/blob/f6487a2fafa6218f8363ebaaf048ff3664eb8af5/boa3/builtin/math.py#L1-L14
Also fixed the modulo operation (`%`) which results were different from Python depending on the signs of the operands.
https://github.com/CityOfZion/neo3-boa/blob/f6487a2fafa6218f8363ebaaf048ff3664eb8af5/boa3_test/test_sc/boa_built_in_methods_test/DecimalFloor.py#L6-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f6487a2fafa6218f8363e …

Add support to floor

---

boa3/builtin/math.py
boa3/model/builtin/builtin.py
boa3/model/builtin/math/__init__.py
boa3/model/builtin/math/decimalceil.py
boa3_test/test_sc/boa_built_in_methods_test/DecimalCeiling.py
boa3_test/tests/compiler_tests/test_boa_builtin_method.py
boa3_test/tests/compiler_tests/test_for.py

#661 
Implemented an integer alternative for `math.ceil` method. This method receives two int arguments, the first being the integer representation of a decimal number and the second the number of decimals to be considered. The number of decimals cannot be negative.
https://github.com/CityOfZion/neo3-boa/blob/fe26132b60d0e62f0375e40728a62d4e187c9151/boa3/builtin/math.py#L1-L15
https://github.com/CityOfZion/neo3-boa/blob/fe26132b60d0e62f0375e40728a62d4e187c9151/boa3_test/test_sc/boa_built_in_methods_test/DecimalCeiling.py#L6-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fe26132b60d0e62f0375e40728a62d4e187c9151/boa3_test/tests/compiler_tests/test_boa_builtin_method.py#L116-L149
**Platform:**
- OS: Windows …

Add support to ceil

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/intbytestringmethod.py
boa3/model/builtin/method/intintmethod.py
boa3/model/builtin/method/intmethod.py
boa3/model/type/primitive/inttype.py
boa3_test/test_sc/built_in_methods_test/IntBytes.py
boa3_test/test_sc/built_in_methods_test/IntInt.py
boa3_test/test_sc/built_in_methods_test/IntIntTooManyParameters.py
boa3_test/test_sc/built_in_methods_test/IntNoParameters.py
boa3_test/test_sc/built_in_methods_test/IntStr.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#754 
Added a constructor to int.
https://github.com/CityOfZion/neo3-boa/blob/36d4aa36211f77ec99267a4e59adfd6ed153b29b/boa3_test/test_sc/built_in_methods_test/IntInt.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/36d4aa36211f77ec99267a4e59adfd6ed153b29b/boa3_test/tests/compiler_tests/test_builtin_method.py#L1598-L1619
**Platform:**
- Python version: Python 3.7]
Even though the int method with str or bytes was implemented, it was not possible to use it together with the int method with int.

Add support to int constructor with integer values

---

boa3/model/builtin/math/__init__.py
boa3/model/builtin/math/powmethod.py
boa3/model/type/math.py
boa3_test/test_sc/math_test/Pow.py
boa3_test/test_sc/math_test/PowFromMath.py
boa3_test/tests/compiler_tests/test_math.py

#664 
Added the pow method from the math module.
https://github.com/CityOfZion/neo3-boa/blob/0cdc1126df20ce0a8ae6387f352a9a415bb3433d/boa3_test/test_sc/math_test/Pow.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0cdc1126df20ce0a8ae6387f352a9a415bb3433d/boa3_test/tests/compiler_tests/test_math.py#L17-L57
**Platform:**

Add support to pow

---

boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_tuple.py

#653
Reincluded the skipped tests of the array of arrays feature and changed due to limitations of the TestEngine.
https://github.com/CityOfZion/neo3-boa/blob/65fb0ae23e53dcfb75450f8a312dd9e76b87d27a/boa3_test/test_sc/list_test/ListOfList.py#L6-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/65fb0ae23e53dcfb75450f8a312dd9e76b87d27a/boa3_test/tests/compiler_tests/test_list.py#L307-L324
**Platform:**

Fix creating a list of lists

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/if_test/IfImplicitBoolean.py
boa3_test/test_sc/if_test/IfImplicitBooleanLiteral.py
boa3_test/test_sc/if_test/MismatchedTypeCondition.py
boa3_test/tests/compiler_tests/test_if.py

#679 
It's now possible to use any type of value in the if condition.
https://github.com/CityOfZion/neo3-boa/blob/9e8bedb4cb1a7d856a0ca384678752e53e0904f3/boa3_test/test_sc/if_test/IfImplicitBoolean.py#L1-L12
**Tests**
[A clear and concise description of how you tested it.](https://github.com/CityOfZion/neo3-boa/blob/9e8bedb4cb1a7d856a0ca384678752e53e0904f3/boa3_test/tests/compiler_tests/test_if.py#L595-L634)
**Platform:**

Add support to implicit boolean conversion

---

boa3/boa3.py
boa3/cli.py
boa3/compiler/compiler.py
boa3_test/tests/compiler_tests/test_file_generation.py

#787 
Added an extra argument to verify whether the debug info should be generated or not.
via command line:
`neo3-boa path/to/your/file.py --debug` or `neo3-boa path/to/your/file.py -db`
via script:
```python
from boa3.boa3 import Boa3
Boa3.compile_and_save('path/to/your/file.py', debug=True)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/2531423bd0a9d913316206f418662af0a845bd47/boa3_test/tests/compiler_tests/test_file_generation.py#L19-L37
**Platform:**

Change nef debug file generation to be optional

---

boa3/analyser/moduleanalyser.py
boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/builtin/decorator/builtindecorator.py
boa3/model/builtin/decorator/contractdecorator.py
boa3/model/builtin/decorator/publicdecorator.py
boa3/model/callable.py
boa3/model/method.py
boa3_test/test_sc/generation_test/MetadataMethodName.py
boa3_test/test_sc/generation_test/MetadataMethodNameArg.py
boa3_test/test_sc/generation_test/MetadataMethodNameMismatchedType.py
boa3_test/test_sc/generation_test/MetadataMethodSafe.py
boa3_test/test_sc/generation_test/MetadataMethodSafeArg.py
boa3_test/test_sc/generation_test/MetadataMethodSafeMismatchedType.py
boa3_test/tests/compiler_tests/test_file_generation.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_tuple.py

#786
Included arguments to the `public` decorator to support manifest abi methods modifiers
https://github.com/CityOfZion/neo3-boa/blob/393e94aa4e4250183297dc635d5fdb87bbac7d14/boa3_test/test_sc/generation_test/MetadataMethodName.py#L4-L7
https://github.com/CityOfZion/neo3-boa/blob/393e94aa4e4250183297dc635d5fdb87bbac7d14/boa3_test/test_sc/generation_test/MetadataMethodSafe.py#L4-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/393e94aa4e4250183297dc635d5fdb87bbac7d14/boa3_test/tests/compiler_tests/test_file_generation.py#L197-L273
**Platform:**

Enhance 'public' decorator to support more manifest modifiers

---

boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3_test/test_sc/metadata_test/MetadataInfoTrusts.py
boa3_test/test_sc/metadata_test/MetadataInfoTrustsDefault.py
boa3_test/test_sc/metadata_test/MetadataInfoTrustsMismatchedTypes.py
boa3_test/test_sc/metadata_test/MetadataInfoTrustsWildcard.py
boa3_test/tests/compiler_tests/test_metadata.py

#783 
Added the possibility to the user add contract hash or public key into the trust modifier on the manifest.
https://github.com/CityOfZion/neo3-boa/blob/bd6e2ed57a6cb27144dbf53c3304b70a652fd224/boa3_test/test_sc/metadata_test/MetadataInfoTrusts.py#L8-L25
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bd6e2ed57a6cb27144dbf53c3304b70a652fd224/boa3_test/tests/compiler_tests/test_metadata.py#L177-L196
**Platform:**

Implement manifest 'trusts' modifier

---

boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3_test/test_sc/metadata_test/MetadataInfoPermissions.py
boa3_test/test_sc/metadata_test/MetadataInfoPermissionsDefault.py
boa3_test/test_sc/metadata_test/MetadataInfoPermissionsMismatchedType.py
boa3_test/test_sc/metadata_test/MetadataInfoPermissionsWildcard.py
boa3_test/tests/compiler_tests/test_metadata.py

#784 
Added the possibility to the user add a `Permission` on the manifest.
https://github.com/CityOfZion/neo3-boa/blob/59b9f9e3c5a8e9736c9ed12f2309bfbbb86fc596/boa3_test/test_sc/metadata_test/MetadataInfoPermissions.py#L1-L21
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/59b9f9e3c5a8e9736c9ed12f2309bfbbb86fc596/boa3_test/tests/compiler_tests/test_metadata.py#L215-L251
**Platform:**

Implement manifest 'permissions' modifier

---

boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3_test/test_sc/metadata_test/MetadataInfoName.py
boa3_test/test_sc/metadata_test/MetadataInfoNameDefault.py
boa3_test/test_sc/metadata_test/MetadataInfoNameMismatchedType.py
boa3_test/tests/compiler_tests/test_metadata.py

#782 
Added a way to the user specify the name of the smart contract.
https://github.com/CityOfZion/neo3-boa/blob/8befad5e1380dc21c0807b8d81aaa51b96bb3fe1/boa3_test/test_sc/metadata_test/MetadataInfoName.py#L1-L14
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8befad5e1380dc21c0807b8d81aaa51b96bb3fe1/boa3_test/tests/compiler_tests/test_metadata.py#L215-L235
**Platform:**

Implement manifest 'name' modifier

---

boa3/analyser/moduleanalyser.py
boa3/builtin/__init__.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3/model/builtin/decorator/__init__.py
boa3/model/builtin/decorator/contractdecorator.py
boa3/model/builtin/decorator/displaynamedecorator.py
boa3/model/callable.py
boa3/model/method.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameKeywordArgument.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameRegularArgument.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameTooFewArguments.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameTooManyArguments.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameVariableArgument.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceDisplayNameWithoutCall.py
boa3_test/test_sc/contract_interface_test/Nep17InterfaceWithDisplayName.py
boa3_test/tests/compiler_tests/test_contract_interface.py

#788
Implemented a decorator to identify methods in a contract interface which identifiers are different in the contract's manifest.
https://github.com/CityOfZion/neo3-boa/blob/2787f29e1892f0b8068dafc2ba2655e3091be27d/boa3_test/test_sc/contract_interface_test/Nep17InterfaceWithDisplayName.py#L7-L35
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/2787f29e1892f0b8068dafc2ba2655e3091be27d/boa3_test/tests/compiler_tests/test_contract_interface.py#L57-L90
**Platform:**

Implement a decorator to annotate when the contract method name is different

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3/model/variable.py
boa3_test/test_sc/interop_test/iterator/IteratorImplicitTyping.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py

#809
Fixed issue with implicit typing not detecting the type attributes
https://github.com/CityOfZion/neo3-boa/blob/0363b1bda4615af79e2e26d18087dfc541f91193/boa3_test/test_sc/interop_test/iterator/IteratorImplicitTyping.py#L14-L25
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0363b1bda4615af79e2e26d18087dfc541f91193/boa3_test/tests/compiler_tests/test_interop/test_iterator.py#L56-L72
**Platform:**

Attribute type validation in module analyser is raising errors with dynamic type validation

---

boa3/cli.py
boa3/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/variable_test/InstanceVariableAndVariableWithSameName.py
boa3_test/tests/compiler_tests/test_variable.py

#800 
Fixed a bug, where, if an instance variable and a variable had the same name, the program would not run properly.
https://github.com/CityOfZion/neo3-boa/blob/df34c193310bad490bb2a5fbaee771a0391834e2/boa3_test/test_sc/variable_test/InstanceVariableAndVariableWithSameName.py#L1-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/df34c193310bad490bb2a5fbaee771a0391834e2/boa3_test/tests/compiler_tests/test_variable.py#L680-L684
**Platform:**
Also fixed a error at `cli.py`.

Assigning a value to a object variable with the same as another variable doesn't run

---

boa3/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/interop_test/iterator/IteratorValueAccess.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py

#808
The error reported in the issue wasn't caused by the `Iterator.value`, but by `Nep11Contract` contract interface method `properties` call.
There was a bug in the internal result stack simulation that removed more values than expected when calling contract interface methods in-line with other methods.
```python
result = json_serialize(Nep11Contract.properties(cast(bytes, token.value)))
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/20d4270b21f3cf1246776f6dea22db3192c0720c/boa3_test/tests/compiler_tests/test_interop/test_iterator.py#L74-L90
**Platform:**

Fix stack simulation during code generation when calling contract interface methods

---

boa3/analyser/supportedstandard/standardanalyser.py
boa3/exception/CompilerError.py
boa3/model/callable.py
boa3/model/standards/neostandard.py
boa3/model/standards/nep17standard.py
boa3/model/standards/standardmethod.py
boa3_test/examples/amm.py
boa3_test/examples/auxiliary_contracts/update_contract.py
boa3_test/examples/ico.py
boa3_test/examples/nep17.py
boa3_test/examples/update_contract.py
boa3_test/examples/wrapped_gas.py
boa3_test/examples/wrapped_neo.py
boa3_test/test_sc/contract_interface_test/Nep17Interface.py
docs/source/tutorials.rst

#801
Changed the NEP-17 validator to search the methods by the manifest name to check if the standard is implemented correctly.
`totalSupply` and `balanceOf` have different names in the Python definition, but it's the name that's on the manifest that matters
https://github.com/CityOfZion/neo3-boa/blob/6a1e982118ffb87c1c1966b283ed2ebda8b48846/boa3_test/examples/nep17.py#L94-L118
**Tests**
Changed the NEP-17 contracts in the examples folders and rerun their 'test_compile'
https://github.com/CityOfZion/neo3-boa/blob/6a1e982118ffb87c1c1966b283ed2ebda8b48846/boa3_test/tests/examples_tests/test_nep17.py#L17-L24
**Platform:**

Update NEP-17 standard validation to verify the methods by the manifest name

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/assert_test/AssertWithBoolMessage.py
boa3_test/test_sc/assert_test/AssertWithBytesMessage.py
boa3_test/test_sc/assert_test/AssertWithIntMessage.py
boa3_test/test_sc/assert_test/AssertWithListMessage.py
boa3_test/test_sc/assert_test/AssertWithStrFunctionMessage.py
boa3_test/test_sc/assert_test/AssertWithStrVarMessage.py
boa3_test/tests/compiler_tests/test_assert.py

#807
Now, when an assert fails and there is a message, it will log the message.
https://github.com/CityOfZion/neo3-boa/blob/5bf3b181eb2fd9c919bfe2dcb4a3185d38bb3fec/boa3_test/test_sc/assert_test/AssertWithMessage.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5bf3b181eb2fd9c919bfe2dcb4a3185d38bb3fec/boa3_test/tests/compiler_tests/test_assert.py#L62-L74
**Platform:**
Python accepts any type in the message, but since the `str` constructor is not implemented, `assert` only accepts strings for now.
#820

Update assert to log message when specified

---

boa3/builtin/__init__.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/compiler/codegenerator/vmcodemapping.py
boa3_test/test_sc/variable_test/ListGlobalAssignment.py
boa3_test/tests/compiler_tests/test_variable.py

#737 
The previous fix (#745) had tests using the value in return statement, which didn't completely fix the issue since calling class methods without using their results were still broken.
Refined the existing unit test to check if the expressions with class method calls work at runtime.
https://github.com/CityOfZion/neo3-boa/blob/21abe48d7683dfa4490efadcbe194c974daef708/boa3_test/test_sc/variable_test/ListGlobalAssignment.py#L29-L32
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/21abe48d7683dfa4490efadcbe194c974daef708/boa3_test/tests/compiler_tests/test_variable.py#L538-L550
**Platform:**

User defined class methods error without using returned value

---

boa3/analyser/analyser.py
boa3/analyser/astoptimizer.py
boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/exception/CompilerWarning.py
boa3/model/builtin/method/builtinmethod.py
boa3/model/builtin/method/uint160method.py
boa3/model/builtin/method/uint256method.py
boa3_test/test_sc/contract_interface_test/Nep17Interface.py
boa3_test/test_sc/contract_interface_test/Nep17InterfaceWithDisplayName.py
boa3_test/tests/compiler_tests/test_constant.py
boa3_test/tests/compiler_tests/test_contract_interface.py

#815
Fixed multiple issues related to calling methods and casting types in-line and importing symbols from different files.
All of them related to not finding imported symbols from different files during code generation.
From #815:
> **How to Reproduce** 
> The attached zip contains 3 contracts for reproduction.
> 
> 1. Deploy the contract in the folder `1_target_contract` and note the script hash
> 2. Update the contract hash in the file `/2_entry_contract_fails/sample/samplecontract.py` with the hash noted in step 1
> 3. Compile `/2_entry_contract_fails/mycontract.py` , deploy and note the hash
> 4. Call the function `test` on the contract deployed in step 3.
> 
> The 3rd contract in the script is the result of …

Invalid contract created

---

boa3/analyser/typeanalyser.py
boa3_test/test_sc/list_test/AppendInClassVariable.py
boa3_test/tests/compiler_tests/test_list.py
setup.cfg

#827
Fixed the internal error caused by calling instance methods from inner variables.
It was caused by a recent refactoring that unified all the types in the compiler under the ``ClassType`` interface.
https://github.com/CityOfZion/neo3-boa/blob/fa6c2b87c168dda33293051a2004ba564614ad3e/boa3_test/test_sc/list_test/AppendInClassVariable.py#L6-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fa6c2b87c168dda33293051a2004ba564614ad3e/boa3_test/tests/compiler_tests/test_list.py#L766-L770
**Platform:**
- Python version: Python 3.7.0

Using in-line methods with class variables raises Internal compiler error

---

boa3/analyser/moduleanalyser.py
boa3/exception/CompilerError.py
boa3/exception/CompilerWarning.py
boa3/model/module.py
boa3/model/type/classes/userclass.py
boa3_test/test_sc/function_test/FunctionsWithDuplicatedName.py
boa3_test/tests/compiler_tests/test_function.py

#846
Included a new compiler warning to warn when multiple symbols are defined using the same identifier. The warning doesn't stop the compilation.
https://github.com/CityOfZion/neo3-boa/blob/247a3a46e421e055410edf90b2a7f955d4f8069c/boa3_test/test_sc/function_test/FunctionsWithDuplicatedName.py#L6-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/247a3a46e421e055410edf90b2a7f955d4f8069c/boa3_test/tests/compiler_tests/test_function.py#L1067-L1069
**Platform:**

Log a compiler warning when symbols with the same identifier are used

---

boa3/analyser/analyser.py
boa3/analyser/moduleanalyser.py
boa3/boa3.py
boa3/cli.py
boa3/compiler/compiler.py
boa3_test/test_sc/generation_test/GenerationWithUserModuleImportsFromProjectRoot.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_file_generation.py

#840
Included a new argument to the compiler for setting the project root path for improving importing analysis. 
If not given, the default value is the contract path.
With this smart contract:
https://github.com/CityOfZion/neo3-boa/blob/5aaf8156346e5cde15216bbe5a2a91dd60d7842b/boa3_test/test_sc/generation_test/GenerationWithUserModuleImportsFromProjectRoot.py#L1-L13
Compiling without passing the proper project root will fail.
https://github.com/CityOfZion/neo3-boa/blob/5aaf8156346e5cde15216bbe5a2a91dd60d7842b/boa3_test/tests/compiler_tests/test_file_generation.py#L652-L657
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5aaf8156346e5cde15216bbe5a2a91dd60d7842b/boa3_test/tests/compiler_tests/test_file_generati …

Include an option to set the project root for better evaluate local imports

---

boa3/builtin/type/__init__.py

#837
Updated `ByteString` interface with its supported methods.
Also included docstrings to update the documentation.
https://github.com/CityOfZion/neo3-boa/blob/404f97d109be3bf289d1396f36b6db134498baa7/boa3/builtin/type/__init__.py#L36-L120
**Platform:**

Include ByteString methods in the interface #837

---

boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/for_test/ForPass.py
boa3_test/test_sc/if_test/ElsePass.py
boa3_test/test_sc/if_test/IfElsePass.py
boa3_test/test_sc/if_test/IfPass.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_for.py
boa3_test/tests/compiler_tests/test_function.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_variable.py

#831
Added the opcode NOP when `pass` is being used on the smart contract.
https://github.com/CityOfZion/neo3-boa/blob/97e225cb16ead49f5ae7a7554a09c5766078378f/boa3_test/test_sc/function_test/NoReturnFunction.py#L1-L6
https://github.com/CityOfZion/neo3-boa/blob/97e225cb16ead49f5ae7a7554a09c5766078378f/boa3_test/test_sc/for_test/ForPass.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/97e225cb16ead49f5ae7a7554a09c5766078378f/boa3_test/tests/compiler_tests/test_function.py#L137-L152
https://github.com/CityOfZion/neo3-boa/blob/97e225cb16ead49f5ae7a7554a09c5766078378f/boa3_test/tests/compiler_tests/test_for.py#L308-L316
**Platform:**

Validate pass keyword #831

---

boa3/analyser/moduleanalyser.py
boa3/analyser/supportedstandard/standardanalyser.py
boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/imports/importsymbol.py
boa3_test/test_sc/generation_test/GenerationWithImportedEvent.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsImportedEvent.py
boa3_test/tests/compiler_tests/test_file_generation.py
boa3_test/tests/compiler_tests/test_metadata.py

#866
Changed to include all events in the manifest, even the ones that are not imported in the smart contract main file.
Also changed the standard validators to check imported events.
https://github.com/CityOfZion/neo3-boa/blob/205cacc5226477cf85aebb5575614fcb7a3ab621/boa3_test/test_sc/generation_test/GenerationWithImportedEvent.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/205cacc5226477cf85aebb5575614fcb7a3ab621/boa3_test/tests/compiler_tests/test_file_generation.py#L206-L237
**Platform:**

Standard validators don't recognize imported events #866

---

boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/import_test/variable_import/GenerateImportedVariable.py
boa3_test/test_sc/import_test/variable_import/StaticVariables.py
boa3_test/test_sc/import_test/variable_import/VariableFromImportedModule.py
boa3_test/tests/compiler_tests/test_import.py

#869
A clear and concise description of what you made in this change.
https://github.com/CityOfZion/neo3-boa/blob/7fb60af5ced06032cb5e9b8c5109f65591269f8f/boa3_test/test_sc/import_test/variable_import/StaticVariables.py#L1-L2
https://github.com/CityOfZion/neo3-boa/blob/7fb60af5ced06032cb5e9b8c5109f65591269f8f/boa3_test/test_sc/import_test/variable_import/GenerateImportedVariable.py#L1-L9
https://github.com/CityOfZion/neo3-boa/blob/7fb60af5ced06032cb5e9b8c5109f65591269f8f/boa3_test/test_sc/import_test/variable_import/VariableFromImportedModule.py#L1-L15
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7fb60af5ced06032cb5e9b8c5109f65591269f8f/boa3_test/tests/compiler_tests/test_import.py#L125-L133
**Platform:** …

Directly importing variables from custom module is not working in runtime #869

---

boa3/model/standards/nep11standard.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsMissingImplementationNEP11OptionalMethods.py

#864 
Corrected the `arg` type in `nep11standard`.
https://github.com/CityOfZion/neo3-boa/blob/037db9039baae75581dfae4c156e8accaa3f4f99/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsMissingImplementationNEP11OptionalMethods.py#L19-L21
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/037db9039baae75581dfae4c156e8accaa3f4f99/boa3_test/tests/compiler_tests/test_metadata.py#L191-L193
**Platform:**

NEP-11 properties validator doesn't accept bytes or ByteString

---

boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/class_test/UserClassWithAugmentedAssignmentOperatorWithVariable.py
boa3_test/tests/compiler_tests/test_class.py

#854 
Added an `if` in `visit_AugAssign` to verify if the augmented assignment is being used with an instance variable. If it is then the object is duplicated in the stack.
https://github.com/CityOfZion/neo3-boa/blob/f976bf6c006bf63c6422e20493c7c1f835d88622/boa3_test/test_sc/class_test/UserClassWithAugmentedAssignmentOperatorWithVariable.py#L1-L83
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f976bf6c006bf63c6422e20493c7c1f835d88622/boa3_test/tests/compiler_tests/test_class.py#L481-L501
**Platform:**

Arithmetic augmented assignment operator not working on instance methods

---

boa3/analyser/importanalyser.py
boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/model/imports/package.py
boa3_test/test_sc/import_test/ImportModuleWithInit.py
boa3_test/test_sc/import_test/package_with_import/Module.py
boa3_test/tests/compiler_tests/test_import.py

#863
Fixed the incorrect error raised when using symbols from an imported module.
https://github.com/CityOfZion/neo3-boa/blob/43642e351f9c4d9842d52044e1762f613410abf7/boa3_test/test_sc/import_test/ImportModuleWithInit.py#L3-L14
https://github.com/CityOfZion/neo3-boa/blob/43642e351f9c4d9842d52044e1762f613410abf7/boa3_test/test_sc/import_test/package_with_import/Module.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/43642e351f9c4d9842d52044e1762f613410abf7/boa3_test/tests/compiler_tests/test_import.py#L348-L357
**Platform:**

Unresolved reference raised when importing a created module with from import

---

boa3/analyser/importanalyser.py
boa3/analyser/moduleanalyser.py
boa3_test/test_sc/import_test/ImportUserClassInnerFiles.py
boa3_test/test_sc/import_test/class_import/ImportUserClass.py
boa3_test/test_sc/import_test/class_import/example.py
boa3_test/tests/compiler_tests/test_import.py

Fixed the bug related to class constructors raising stack size errors during runtime.
The error only happened with classes that weren't imported by the main contract file.
https://github.com/CityOfZion/neo3-boa/blob/593eec45f39321727d303d970fdf295dbf1df5b8/boa3_test/test_sc/import_test/ImportUserClassInnerFiles.py#L2-L10
https://github.com/CityOfZion/neo3-boa/blob/593eec45f39321727d303d970fdf295dbf1df5b8/boa3_test/test_sc/import_test/class_import/ImportUserClass.py#L3-L8
https://github.com/CityOfZion/neo3-boa/blob/593eec45f39321727d303d970fdf295dbf1df5b8/boa3_test/test_sc/import_test/class_import/example.py#L1-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/593eec45f39321727d303d970fdf295dbf1df5b8/boa3_test/tests/compiler_te …

Runtime error raised when invoking user-created class constructor

---

boa3/analyser/analyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/compiler.py
boa3/compiler/filegenerator.py
boa3/model/callable.py

#867 
Debug info file wasn't mapping all functions due to internal code inconsistencies that happened because of the manipulation of the symbol table during the code generation. Solved it by cloning the analyser before the code generation.
There were also errors with methods that weren't called and not generated but were being included in the debug info file, causing errors due to missing information.
**Platform:**

Generate debug map when using multiple files

---

boa3/analyser/typeanalyser.py
boa3_test/test_sc/import_test/FromImportNotExistingMethod.py
boa3_test/test_sc/import_test/ImportNotExistingMethod.py
boa3_test/tests/compiler_tests/test_import.py

#865 
Added a condition to check if an attribute is a method and exists inside the origin.
https://github.com/CityOfZion/neo3-boa/blob/0ca6f1e265890bfe46e5badaf2d0a2f5ea68b0f3/boa3_test/test_sc/import_test/FromImportNotExistingMethod.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0ca6f1e265890bfe46e5badaf2d0a2f5ea68b0f3/boa3_test/tests/compiler_tests/test_import.py#L370-L376
**Platform:**

Compilation succeeds when it should raise an unresolved reference from importing #2ewe99p

---

boa3/analyser/astanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/variable_test/GlobalVariableInClassMethod.py
boa3_test/tests/compiler_tests/test_variable.py

Using global variable in class methods were not working as expected when both the variable and the class are written in the same file. Fixed by keeping the reference to the original file during code generation.
https://github.com/CityOfZion/neo3-boa/blob/adfdf01fc67c1a46cdd5fc77fe353234fa46fac0/boa3_test/test_sc/variable_test/GlobalVariableInClassMethod.py#L3-L21
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/adfdf01fc67c1a46cdd5fc77fe353234fa46fac0/boa3_test/tests/compiler_tests/test_variable.py#L579-L587
**Platform:**

Global variable not working in class methods

---

boa3/analyser/analyser.py
boa3/analyser/importanalyser.py
boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/filegenerator.py
boa3_test/test_sc/import_test/ImportUserClassInnerFiles.py
boa3_test/test_sc/import_test/variable_import/VariableFromImportedModule.py
boa3_test/tests/compiler_tests/test_import.py

Refactored the importing process so that the Code Analyser of the entry file has access to all the imported files accessed during the compilation.
https://github.com/CityOfZion/neo3-boa/blob/014d6f7b4a704821b97bede84296409b6cafa870/boa3_test/test_sc/import_test/variable_import/VariableFromImportedModule.py#L1-L12
https://github.com/CityOfZion/neo3-boa/blob/014d6f7b4a704821b97bede84296409b6cafa870/boa3_test/test_sc/import_test/ImportUserClassInnerFiles.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/014d6f7b4a704821b97bede84296409b6cafa870/boa3_test/tests/compiler_tests/test_import.py#L125-L143
https://github.com/CityOfZion/neo3-boa/blob/014d6f7b4a704821b97bede84296409b6cafa870/boa3_test/tests/compiler_tests/test_import …

#2kwg0wf Global variables don't initialize from modules that are not imported in the main file

---

boa3/neo3/core/utils.py
boa3_test/tests/test_classes/contract/neopermissionsstruct.py

The issue was an import that doesn't exist in Python 3.10 anymore.
There is a SyntaxWarning as well that is raised by Python 3.10 only that was fixed.
**Tests**
Run the unit tests using Python 3.10
**Platform:**
- Python version: Python 3.10.4
We're going to include Python 3.10 in the CircleCI workflow in another pull request

Error using Python 3.10

---

boa3/analyser/typeanalyser.py
boa3_test/examples/amm.py
boa3_test/examples/htlc.py
boa3_test/examples/ico.py
boa3_test/examples/nep17.py
boa3_test/examples/wrapped_gas.py
boa3_test/examples/wrapped_neo.py
boa3_test/test_sc/if_test/IfIsNone.py
boa3_test/test_sc/if_test/IfIsNotNone.py
boa3_test/tests/compiler_tests/test_if.py
docs/source/tutorials.rst

Made `x is None` and `x is not None` have the same behaviour as `isinstance(x, None)` and `not isinstance(x, None)`.
https://github.com/CityOfZion/neo3-boa/blob/3d55492bb6ee826e2dcd1dfe08a923f579c56fff/boa3_test/test_sc/if_test/IfIsNone.py#L1-L15
https://github.com/CityOfZion/neo3-boa/blob/3d55492bb6ee826e2dcd1dfe08a923f579c56fff/boa3_test/test_sc/if_test/IfIsNotNone.py#L1-L15
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3d55492bb6ee826e2dcd1dfe08a923f579c56fff/boa3_test/tests/compiler_tests/test_if.py#L674-L690
**Platform:**
Bugs regarding `isinstance(x, None)` and `not isinstance(x, None)` were not fixed and identity operations now have …

`is not None` is not working properly

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/model/builtin/method/bytearraymethod.py
boa3/model/type/primitive/bytearraytype.py
boa3/neo/vm/opcode/Opcode.py
boa3_test/test_sc/bytes_test/BytearraySetValue.py
boa3_test/test_sc/bytes_test/BytearraySetValueNegativeIndex.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceCodeOptimization.py
boa3_test/test_sc/contract_interface_test/Nep17Interface.py
boa3_test/test_sc/contract_interface_test/Nep17InterfaceWithDisplayName.py
boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_constant.py
boa3_test/tests/compiler_tests/test_contract_interface.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py
boa3_test/tests/compiler_tests/test_relational.py
boa3_test/tests/compiler_tests/test_union.py

#903
`bytearray` is being generated as a `ByteString` instead of `Buffer` and this is causing errors in the Neo VM.
https://github.com/CityOfZion/neo3-boa/blob/8bd1e207f883ecadb3c66968158fe6159497b7cc/boa3_test/test_sc/bytes_test/BytearraySetValue.py#L5-L8
**Tests**
The unit tests already existed, but they were being skipped in the test workflow
https://github.com/CityOfZion/neo3-boa/blob/8bd1e207f883ecadb3c66968158fe6159497b7cc/boa3_test/tests/compiler_tests/test_bytes.py#L570-L576
**Platform:**

Invalid type for SETITEM: ByteString when assigning value at index in bytearray

---

boa3/analyser/importanalyser.py
boa3/constants.py
boa3_test/test_sc/import_test/ImportBoaInvalidPackage.py
boa3_test/tests/compiler_tests/test_import.py

#895
The only package in `boa3` package designed to be used in smart contracts is the `boa3.builtin` package.
The compiler was using the same process used to validate user-created modules to try to import the other `boa3` packages.
Included a filter to ignore these packages and always rais `UnresolvedReference` error.
https://github.com/CityOfZion/neo3-boa/blob/35dbab129377f62d708bb68622d74f55af8ab3b5/boa3_test/test_sc/import_test/ImportBoaInvalidPackage.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/35dbab129377f62d708bb68622d74f55af8ab3b5/boa3_test/tests/compiler_tests/test_import.py#L399-L401
**Platform:**
The …

Only boa3.builtin package should be imported by contracts

---

boa3/analyser/astoptimizer.py
boa3_test/test_sc/interop_test/runtime/AddressVersionCantAssign.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py

The ast visitor implement for optimizations wasn't checking `else` branches of `try except`
https://github.com/CityOfZion/neo3-boa/blob/84d2a06393003d4ee5f5d9b885b4fd53785c5436/boa3_test/test_sc/exception_test/TryExceptElse.py#L5-L13
**Tests**
Rerun all `except` unit tests
https://github.com/CityOfZion/neo3-boa/blob/84d2a06393003d4ee5f5d9b885b4fd53785c5436/boa3_test/tests/compiler_tests/test_exception.py#L192-L415
**Platform:**

Implement the optional keyword `else` when handling exceptions/errors in optimization

---

boa3/builtin/interop/blockchain/__init__.py
boa3/builtin/interop/blockchain/vmstate.py
boa3/builtin/nativecontract/ledger.py
boa3/model/builtin/interop/blockchain/__init__.py
boa3/model/builtin/interop/blockchain/gettransactionvmstatemethod.py
boa3/model/builtin/interop/blockchain/vmstatetype.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/native/ledgerclass.py
boa3/neo3/vm/vmstate.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionVMState.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionVMStateMismatchedType.py
boa3_test/test_sc/native_test/ledger/GetTransactionVMState.py
boa3_test/test_sc/native_test/ledger/GetTransactionVMStateMismatchedType.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_native/test_ledger.py
boa3_test/tests/test_classes/testengine.py
test_runner/neo_test_runner.py

Implemented Ledger native contract method getTransactionVMState
https://github.com/CityOfZion/neo3-boa/blob/da94d291e3eecb02e25e27ad75ffe14378595af3/boa3/builtin/nativecontract/ledger.py#L70-L78
Also accessible in `boa3.builtin.interop.blockchain`
https://github.com/CityOfZion/neo3-boa/blob/da94d291e3eecb02e25e27ad75ffe14378595af3/boa3/builtin/interop/blockchain/__init__.py#L71-L79
https://github.com/CityOfZion/neo3-boa/blob/da94d291e3eecb02e25e27ad75ffe14378595af3/boa3_test/test_sc/native_test/ledger/GetTransactionVMState.py#L8-L9
https://github.com/CityOfZion/neo3-boa/blob/da94d291e3eecb02e25e27ad75ffe14378595af3/boa3_test/test_sc/interop_test/blockchain/GetTransactionVMState.py#L7-L8
**Tests** …

Implement Ledger Native Contract method `getTransactionVMState`

---

boa3/compiler/codegenerator/codegenerator.py
boa3/model/builtin/classmethod/tobytesmethod.py
boa3_test/test_sc/function_test/FunctionAsArg.py
boa3_test/test_sc/function_test/FunctionWithArgAsArg.py
boa3_test/test_sc/function_test/FunctionWithArgsAsArg.py
boa3_test/tests/compiler_tests/test_function.py

Added a `_update_codes_with_target` on `convert_method_call`.
https://github.com/CityOfZion/neo3-boa/blob/111a0417ae212c1cb4abb0a860a92cdcb75afaea/boa3_test/test_sc/function_test/FunctionAsArg.py#L1-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/111a0417ae212c1cb4abb0a860a92cdcb75afaea/boa3_test/tests/compiler_tests/test_function.py#L1075-L1080
**Platform:**

Method call is falling when calling other methods as arguments

---

boa3/compiler/codegenerator/codegenerator.py

The builtin MinMethod accepts more than 2 arguments, so instead of adding another dummy value on the stack it will be better to just use OpcodeMin directly instead
**Platform:**

Min method error

---

boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3_test/test_sc/metadata_test/MetadataInfoGroups.py
boa3_test/test_sc/metadata_test/MetadataInfoGroupsDefault.py
boa3_test/tests/compiler_tests/test_metadata.py
boa3_test/tests/test_classes/contract/neomanifeststruct.py

Added a NeoMetadata method to add groups in the metadata.
https://github.com/CityOfZion/neo3-boa/blob/5d2116fb02eccf3c1b34ac6d2ee94c9eca67be49/boa3_test/test_sc/metadata_test/MetadataInfoGroups.py#L1-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5d2116fb02eccf3c1b34ac6d2ee94c9eca67be49/boa3_test/tests/compiler_tests/test_metadata.py#L313-L355
**Platform:**
The Csharp version doesn't seem to have a way to add groups in the metadata using the smart contract, it's only done manually.

Implement manifest groups

---

boa3_test/test_sc/metadata_test/MetadataInfoTrusts.py
boa3_test/tests/compiler_tests/test_metadata.py
boa3_test/tests/test_classes/contract/neomanifeststruct.py

Added tests to verify NeoManifestStruct trusts
https://github.com/CityOfZion/neo3-boa/blob/0af0f65d5c5e4b6bb64e3992c24bf7d8a8ab6139/boa3_test/test_sc/metadata_test/MetadataInfoTrusts.py#L1-L26
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0af0f65d5c5e4b6bb64e3992c24bf7d8a8ab6139/boa3_test/tests/compiler_tests/test_metadata.py#L216-L284
**Platform:**
The TestEngine is probably not returning the correct value when the wildcard is being used

Implement manifest trusts

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/popdictdefaultmethod.py
boa3/model/builtin/classmethod/popdictmethod.py
boa3/model/builtin/classmethod/popmethod.py
boa3/model/type/collection/mapping/mutable/dicttype.py
boa3_test/test_sc/dict_test/DictPopDefault.py
boa3_test/tests/compiler_tests/test_dict.py

Added another variation of pop for dict with 3 args instead of 2.
https://github.com/CityOfZion/neo3-boa/blob/1d3f3710f290aa73cd5e8b6c77ba7e8d368c77e6/boa3_test/test_sc/dict_test/DictPopDefault.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1d3f3710f290aa73cd5e8b6c77ba7e8d368c77e6/boa3_test/tests/compiler_tests/test_dict.py#L550-L580
**Platform:**
- OS:  Windows 10 x64

Add default argument to dict.pop() method | #2kq1z1b

---

boa3/analyser/supportedstandard/standardanalyser.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsFilter.py
boa3_test/tests/compiler_tests/test_metadata.py

Changed the regex to permit using standards like `NEP-17.1`
https://github.com/CityOfZion/neo3-boa/blob/ca3b7994d1fd83d88fab0edf251fb3bc86ad8f7d/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsFilter.py#L15-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/ca3b7994d1fd83d88fab0edf251fb3bc86ad8f7d/boa3_test/tests/compiler_tests/test_metadata.py#L200-L218
**Platform:**

Fix standard name changing during compilation

---

boa3/analyser/typeanalyser.py
boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/bytearrayencodingmethod.py
boa3/model/builtin/method/bytearraymethod.py
boa3_test/test_sc/bytes_test/BytearrayFromStringWithEncoding.py
boa3_test/tests/compiler_tests/test_bytes.py

A clear and concise description of what you made in this change.
https://github.com/CityOfZion/neo3-boa/blob/5570cd87b599c4b7d9724fc2da55a6780039d08e/boa3_test/test_sc/bytes_test/BytearrayFromString.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5570cd87b599c4b7d9724fc2da55a6780039d08e/boa3_test/tests/compiler_tests/test_bytes.py#L726-L741
**Platform:**
It was changed from `elif` to `if` because it wouldn't look for ByteArrayEncondingMethod otherwise and would be stuck with only ByteArrayMethod. This could be related to that `IntMethod` problem that has the tests skipped.
https://github.com/CityOfZion/neo3-boa/blob/5570cd87b599c4b7d972 …

Implement building bytearray from string

---

boa3/model/builtin/classmethod/__init__.py
boa3/model/operation/unary/logicnot.py
boa3_test/test_sc/dict_test/DictPopDefault.py
boa3_test/test_sc/logical_test/LogicNotBool.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_native/test_neo.py
boa3_test/tests/test_classes/contractcollection.py
boa3_test/tests/test_classes/testcontract.py
boa3_test/tests/test_classes/testengine.py

Updated TestEngine interface to convert the execution result to the expected type given the contract manifest.
**Platform:**

Convert the result to the return type of the function in the manifest

---

boa3/model/builtin/builtin.py
boa3/model/builtin/classmethod/__init__.py
boa3/model/builtin/classmethod/indexbytesstringmethod.py
boa3/model/builtin/classmethod/indexmethod.py
boa3/model/type/primitive/strtype.py
boa3_test/test_sc/bytes_test/IndexBytes.py
boa3_test/test_sc/bytes_test/IndexBytesDefaults.py
boa3_test/test_sc/bytes_test/IndexBytesEndDefault.py
boa3_test/test_sc/bytes_test/IndexBytesMismatchedType.py
boa3_test/tests/compiler_tests/test_bytes.py

Changed IndexStrMethod to accept bytes too.
https://github.com/CityOfZion/neo3-boa/blob/7d022080a998d359d213430196680ad631158e99/boa3_test/test_sc/bytes_test/IndexBytes.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7d022080a998d359d213430196680ad631158e99/boa3_test/tests/compiler_tests/test_bytes.py#L1166-L1262
**Platform:**

Add support to Bytes index method

---

boa3/analyser/supportedstandard/standardanalyser.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNotExplicit.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNotExplicitIncompleteEvents.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNotExplicitIncompleteMethods.py
boa3_test/tests/compiler_tests/test_metadata.py

Standards will now be added to the `supportedstandards` field on the manifest event if it wasn't explicitly added on the MetadataInfo.
https://github.com/CityOfZion/neo3-boa/blob/5543e88cc9add8937000c50d9c28430b74495c40/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNotExplicit.py#L1-L37
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5543e88cc9add8937000c50d9c28430b74495c40/boa3_test/tests/compiler_tests/test_metadata.py#L222-L230
**Platform:**

Detect standards from implemented methods and events | #2kq0v7d

---

.circleci/config.yml
boa3/model/builtin/interop/blockchain/signertype.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_native/test_ledger.py
boa3_test/tests/compiler_tests/test_tuple.py

Updating CircleCI workflow to run the tests using the updated version of the TestEngine

Update CircleCI to use TestEngine v3.3.1

---

boa3/analyser/moduleanalyser.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_dict.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_variable.py

Shadow naming warning was raised when setting values in variable sequences from outer scopes.
https://github.com/CityOfZion/neo3-boa/blob/db29cb6cb09dd2e3560fc93131a9a0cb374894e1/boa3_test/test_sc/list_test/SetValue.py#L6-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/db29cb6cb09dd2e3560fc93131a9a0cb374894e1/boa3_test/tests/compiler_tests/test_list.py#L208-L232
https://github.com/CityOfZion/neo3-boa/blob/db29cb6cb09dd2e3560fc93131a9a0cb374894e1/boa3_test/tests/compiler_tests/test_dict.py#L279-L285
**Platform:**

Bug fix - False shadow naming warning

---

.circleci/config.yml

Updating CircleCI workflow to run the tests using the updated version of the TestEngine

Update CircleCI to use TestEngine v3.4.0

---

boa3/model/builtin/builtin.py
boa3/model/builtin/method/__init__.py
boa3/model/builtin/method/strboolmethod.py
boa3/model/builtin/method/strbytestringmethod.py
boa3/model/builtin/method/strintmethod.py
boa3/model/builtin/method/strmethod.py
boa3/model/type/primitive/strtype.py
boa3_test/test_sc/built_in_methods_test/StrBool.py
boa3_test/test_sc/built_in_methods_test/StrByteString.py
boa3_test/test_sc/built_in_methods_test/StrInt.py
boa3_test/test_sc/built_in_methods_test/StrTooManyParameters.py
boa3_test/tests/compiler_tests/test_builtin_method.py

Added support to `str()`, however it only accepts only one argument (Python can accept up to 3).
https://github.com/CityOfZion/neo3-boa/blob/08d7c99f1b9bd8a691a371415991899d141da18e/boa3_test/test_sc/built_in_methods_test/StrInt.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/08d7c99f1b9bd8a691a371415991899d141da18e/boa3_test/tests/compiler_tests/test_builtin_method.py#L1910-L1920
**Platform:**
Since bytes and string is the same in Neo, the constructor with a bytes value as a parameter is not returning the same value as the return in Python.

Add support to str constructor

---

boa3/builtin/__init__.py
boa3/compiler/filegenerator.py
boa3/model/builtin/builtin.py
boa3/neo/contracts/neffile.py
boa3_test/examples/nep11_non_divisible.py
boa3_test/test_sc/metadata_test/MetadataInfoSource.py
boa3_test/test_sc/metadata_test/MetadataInfoSourceDefault.py
boa3_test/test_sc/metadata_test/MetadataInfoSourceMismatchedType.py
boa3_test/tests/compiler_tests/test_metadata.py

#771
Included `source` field to NeoMetadata.
https://github.com/CityOfZion/neo3-boa/blob/e5137e4be022e9021025ba162172122cd4766b29/boa3_test/test_sc/metadata_test/MetadataInfoSource.py#L9-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e5137e4be022e9021025ba162172122cd4766b29/boa3_test/tests/compiler_tests/test_metadata.py#L453-L462
**Platform:**

Include source to nef generation

---

boa3/analyser/model/ManifestSymbol.py
boa3/analyser/moduleanalyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/exception/CompilerError.py
boa3_test/test_sc/generation_test/MetadataMethodDuplicatedNameAndArgs.py
boa3_test/test_sc/generation_test/MetadataMethodDuplicatedNameDifferentArgs.py
boa3_test/tests/compiler_tests/test_file_generation.py

We cannot have different methods in the manifest with the same name and the same number of arguments.
Methods with the same name but a different number of arguments are allowed.
https://github.com/CityOfZion/neo3-boa/blob/5e900756697401b46c0b0003d12ff2ee578c432c/boa3_test/test_sc/generation_test/MetadataMethodDuplicatedNameAndArgs.py#L4-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5e900756697401b46c0b0003d12ff2ee578c432c/boa3_test/tests/compiler_tests/test_file_generation.py#L279-L307
**Platform:**

Don't let compile a smart contract that sets two different methods with the same amount of argument and the same name in the manifest

---

boa3/exception/CompilerError.py

Changed the message error to show which methods should also be marked as `safe` to fulfill the standard, to avoid confusions like the following when the methods are implemented correctly
```
ERROR: 'NEP-11': Missing 'symbol' method definition 'public () -> str'
ERROR: 'NEP-11': Missing 'decimals' method definition 'public () -> int'
ERROR: 'NEP-11': Missing 'totalSupply' method definition 'public () -> int'
ERROR: 'NEP-11': Missing 'balanceOf' method definition 'public (UInt160) -> int'
ERROR: 'NEP-11': Missing 'tokensOf' method definition 'public (UInt160) -> Iterator[any, any]'
ERROR: 'NEP-11': Missing 'transfer' method definition 'public (UInt160, ByteString, any) -> bool'
ERROR: 'NEP-11': Missing 'ownerOf' method definition 'public (ByteString) -> …
```

Change missing standard definition error message for clarity

---

boa3/analyser/moduleanalyser.py
boa3/model/event.py
boa3_test/test_sc/event_test/EventWithDuplicatedName.py
boa3_test/tests/compiler_tests/test_event.py

The internal identifier for events was initialized with the event name, which conflicted with other symbols names (i.e. methods with the same name)
https://github.com/CityOfZion/neo3-boa/blob/14a5eaa4fff24e5cad88fa8c8fa92aa76c5f97fa/boa3_test/test_sc/event_test/EventWithDuplicatedName.py#L3-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/14a5eaa4fff24e5cad88fa8c8fa92aa76c5f97fa/boa3_test/tests/compiler_tests/test_event.py#L257-L269
**Platform:**

Couldn't create an event with the same name as a method

---

boa3/analyser/model/symbolscope.py
boa3/analyser/typeanalyser.py
boa3_test/test_sc/typing_test/CastPersistedInScope.py
boa3_test/tests/compiler_tests/test_typing.py

Type casting of variables which ids shadowed the function argument variables was not persisted after the casting, causing compiler error.
https://github.com/CityOfZion/neo3-boa/blob/c9002b30b392553501925654fbf4722fc4e74e68/boa3_test/test_sc/typing_test/CastPersistedInScope.py#L12-L27
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c9002b30b392553501925654fbf4722fc4e74e68/boa3_test/tests/compiler_tests/test_typing.py#L153-L159
**Platform:**

Cast to shadowed variable still fails compilation

---

boa3_test/tests/compiler_tests/test_list.py

It's probably a TestEngine problem, not a Neo3-boa.
**Tests**
I added the smart contract into the TestNet and it worked there.
Smart contract: https://dora.coz.io/contract/neo3/testnet/0x8dcae7549a82fbce77cf4ec0583489e610914ae4
I also sent a transaction with the arg:  [[1,2,3,45], [566,7,8]] and got this back on the tx
txId: 0x67d2b60496846e748622038ce0413f3469d0e5a609643883360365cb50010935
**Platform:**

Fix jagged arrays in neo boa

---

boa3_test/examples/auxiliary_contracts/update_contract.py
boa3_test/examples/update_contract.py

Changed the example that set the update method as `safe`. Cannot update a contract from a read-only method, so calling this method would fail.
https://github.com/CityOfZion/neo3-boa/blob/865b5d3ae38c50a30ff9a9fe8f07bd30c4993530/boa3_test/examples/update_contract.py#L63-L72

cannot update the update_contract.py example

---

boa3/analyser/typeanalyser.py
boa3/builtin/__init__.py
boa3/model/type/classes/contractinterfaceclass.py
boa3/model/type/classes/contractinterfacehash.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHash.py
boa3_test/tests/compiler_tests/test_contract_interface.py

Implemented a property in contract interface classes to access their script hash
https://github.com/CityOfZion/neo3-boa/blob/7143df2be36308c546597227ad18f2deef5178d0/boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHash.py#L5-L15
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7143df2be36308c546597227ad18f2deef5178d0/boa3_test/tests/compiler_tests/test_contract_interface.py#L185-L192
**Platform:**

Include `hash` property to classes with @contract decorator

---

boa3/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/for_test/ForWithContractInterface.py
boa3_test/test_sc/for_test/ForWithContractInterfaceCalled.py
boa3_test/tests/compiler_tests/test_for.py

Using a ContractInterface inside a `for` loop was making it end on the first iteration (this was also probably happening in other instances too).
There was a piece of code on the `codegenerator` that shouldn't be a part of the `ContractInterface` condition.
https://github.com/CityOfZion/neo3-boa/blob/f2e2ce4a655e56ae5f491b5ee6322f19de4b3c8c/boa3_test/test_sc/for_test/ForWithContractInterface.py#L1-L20
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f2e2ce4a655e56ae5f491b5ee6322f19de4b3c8c/boa3_test/tests/compiler_tests/test_for.py#L318-L325
**Platform:**

Internal compiler error raised on `for` statement

---

boa3/analyser/moduleanalyser.py
boa3/analyser/typeanalyser.py
boa3_test/test_sc/variable_test/MismatchedTypeInvalidTypeFormat.py
boa3_test/tests/compiler_tests/test_variable.py

Included additional checks so the compiler doesn't accept `[int]` as a type annotation (should be `List[int]` in this case for example)
https://github.com/CityOfZion/neo3-boa/blob/7b19c579948b333a0dedeb8e713b879cf7feb180/boa3_test/test_sc/variable_test/MismatchedTypeInvalidTypeFormat.py#L6-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7b19c579948b333a0dedeb8e713b879cf7feb180/boa3_test/tests/compiler_tests/test_variable.py#L421-L424
**Platform:**

Don't compile when typechecking doesn't fit Python standard

---

.circleci/config.yml
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_tuple.py

Updated the unit tests that expected failures when passing arrays as arguments
https://github.com/CityOfZion/neo3-boa/blob/d43476809c443a958b3bdda27b2295fd864c3a25/boa3_test/tests/compiler_tests/test_list.py#L314-L322

Problem with jagged arrays as parameter on TestEngine

---

boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/examples_tests/test_amm.py
boa3_test/tests/examples_tests/test_htlc.py
boa3_test/tests/examples_tests/test_nep17.py
boa3_test/tests/examples_tests/test_wrapped_neo.py
boa3_test/tests/test_classes/storage.py
boa3_test/tests/test_classes/testengine.py

`reset_engine` weren't clearing the contract list nor removing the deployed contract data from the mocked storage.
https://github.com/CityOfZion/neo3-boa/blob/514bac7964f91b7a656ecc4f14df9038da01fafa/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L20-L34
**Platform:**

Reset is not resetting contracts on TestEngine

---

boa3/analyser/analyser.py
boa3/compiler/compiledmetadata.py
boa3/compiler/compiler.py
boa3/model/builtin/interop/nativecontract/nativecontractmethod.py
boa3_test/examples/auxiliary_contracts/update_contract.py
boa3_test/examples/htlc.py
boa3_test/examples/wrapped_gas.py
boa3_test/examples/wrapped_neo.py
boa3_test/test_sc/metadata_test/MetadataInfoPermissionsNativeContract.py
boa3_test/tests/compiler_tests/test_metadata.py

When the smart contract called the non-safe methods from native contracts using their boa interfaces, a runtime error would be thrown if those methods weren't explicitly included in the manifest permissions.
This PR changes it so the compiler can detect the native contract methods that the smart contract calls and include then in the manifest
https://github.com/CityOfZion/neo3-boa/blob/e3b2588f72573cb389d1612914a0bf4a3e3dac91/boa3_test/test_sc/metadata_test/MetadataInfoPermissionsNativeContract.py#L2-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e3b2588f72573cb389d1612914a0bf4a3e3dac91/boa3_test/tests/compiler_tests/test_metadata.py#L418-L430
**Platform:**

Detect which native methods are called in the contract and set the permissions in the manifest

---

.circleci/config.yml
boa3/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/interop.py
boa3/model/builtin/interop/runtime/__init__.py
boa3/model/builtin/interop/runtime/loadscriptmethod.py
boa3_test/test_sc/interop_test/runtime/LoadScriptDynamicCall.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py

Added the interop method `runtime.loadScript`
https://github.com/CityOfZion/neo3-boa/blob/02b7f332e62800a89540d1a18d30a88300847d47/boa3/builtin/interop/runtime/__init__.py#L98-L102
https://github.com/CityOfZion/neo3-boa/blob/02b7f332e62800a89540d1a18d30a88300847d47/boa3_test/test_sc/interop_test/runtime/LoadScriptDynamicCall.py#L5-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/02b7f332e62800a89540d1a18d30a88300847d47/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L712-L727
**Platform:**

Implement interop method `loadScript`

---

boa3/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/logical_test/LogicOperationWithReturnAndStackFilled.py
boa3_test/tests/compiler_tests/test_function.py
boa3_test/tests/compiler_tests/test_logical.py

There were some instances where the stack was not empty, but it was considered empty, some values were added and then a Opcode.CLEAN followed next. So CLEAN was removed and a number of DROPs were added.
https://github.com/CityOfZion/neo3-boa/blob/d7a2ff0de70ae3291d6e5623182cca1aaf40555c/boa3_test/test_sc/logical_test/LogicOperationWithReturnAndStackFilled.py#L1-L17
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d7a2ff0de70ae3291d6e5623182cca1aaf40555c/boa3_test/tests/compiler_tests/test_logical.py#L537-L542
**Platform:**

CU-3ccgt1y - Boolean expression is having an odd behavior

---

boa3/compiler/codegenerator/vmcodemap.py
boa3/compiler/codegenerator/vmcodemapping.py
boa3/neo/vm/VMCode.py

The logic to ensure the position and address of each opcode in the generated bytecode was taking too much time with longer smart contracts. 
The logic in mapping each opcode to its address was isolated from the class responsible for changing the bytecode so we can test options to optimize it without a big refactoring. In addition to this isolation, the map iteration was changed to avoid unnecessary iterations and to decrease the compilation time

Isolate position-opcode map logic from the code generator

---

.circleci/config.yml

Updated the TestEngine version used in CI/CD

Update TestEngine to Neo 3.5.0

---

boa3/analyser/typeanalyser.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/compiler/codegenerator/generatordata.py
boa3/compiler/codegenerator/vmcodemapping.py
boa3_test/test_sc/class_test/UserClassUpdateClassVariableOnInit.py
boa3_test/tests/compiler_tests/test_class.py

Reassigning class variables is not implemented yet in boa and so the following shouldn't be compiled:
https://github.com/CityOfZion/neo3-boa/blob/c9ce0aaa7ab92a3b5c6b9f1f241ba3b17964688c/boa3_test/test_sc/class_test/UserClassUpdateClassVariableOnInit.py#L4-L11
But it was being compiled and executing it caused an exception in runtime.
Investigating this, the same exception reported was raised when trying to update instance variables.
Fixed the bug when using instance variables and change the compiler to not accept reassigning class variables in augmented assignments
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c9ce0aaa7ab92a3b5c6b9f1f241ba3b17964688c/boa3_test/tests/compiler_tests/test_class.py#L236-L242
**Platform:**
- …

Could not use class variable inside instance method

---

boa3_test/test_sc/event_test/EventWithAbort.py
boa3_test/tests/compiler_tests/test_event.py

> I tried to use rollback_on_fault=False to get notifications even when the TestEngine would abort or throw an exception, but it's not returning any value 
Notifications aren't emitted on a fault execution, so the TestEngine not returning them when there's an abort or an exception raise is actually the expected behavior. Setting `roll_back_on_fault` as False can't get any notification because the blockchain doesn't return them to the TestEngine.
https://github.com/CityOfZion/neo3-boa/blob/8666dea49f272fb90e5c7c5128f098bf8a94bde7/boa3_test/test_sc/event_test/EventWithAbort.py#L4-L20
**Tests**
Included a test to make sure the expected behavior is executed.
https://github.com/CityOfZion/neo3-boa/blob/8666dea49f272fb90e5c7c5128f098bf8a94 …

Notifications aren't returned with rollback_on_fault=False

---

boa3/model/builtin/method/toscripthashmethod.py
boa3/neo/__init__.py
boa3/neo/vm/opcode/OpcodeHelper.py
boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_constant.py

We had inconsistent behavior with the method `to_script_hash`. There were cases where the results didn't have the length a script hash should have (20 bytes).
https://github.com/CityOfZion/neo3-boa/blob/705c163b9d3180eac66fd9aafb08f33d76a24a29/boa3_test/test_sc/built_in_methods_test/ScriptHashVariable.py#L4-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/705c163b9d3180eac66fd9aafb08f33d76a24a29/boa3_test/tests/compiler_tests/test_builtin_method.py#L414-L477
**Platform:**

Bug fix - Method `to_script_hash` may not work with some values

---

boa3_test/test_drive/model/invoker/neoinvokecollection.py
boa3_test/test_drive/model/invoker/neoinvokeresult.py
boa3_test/test_drive/neoxp/__init__.py
boa3_test/test_drive/neoxp/utils.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/test_sc/arithmetic_test/ConcatBytesVariablesAndConstants.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_arithmetic.py
boa3_test/tests/compiler_tests/test_logical.py
boa3_test/tests/compiler_tests/test_multiple_expressions.py
boa3_test/tests/compiler_tests/test_python_operation.py
boa3_test/tests/compiler_tests/test_relational.py
boa3_test/tests/compiler_tests/test_variable.py

Part of an overall refactoring. Changed the execution tests of the compiled smart contracts to use TestRunner instead of TestEngine
**Tests**

Refactor unit tests to use TestRunner instead of TestEngine

---

boa3/analyser/typeanalyser.py
boa3_test/test_sc/list_test/ListWithEmptyTypedDict.py
boa3_test/tests/compiler_tests/test_list.py

Hinting the type of a `Dict` that has keys and values that are not `Any` inside another type, like `List` and returning an empty dict was not compiling, raising an error `Expected type 'list[dict[str, bool]]', got 'list[dict[any, any]]' instead`.
This was caused because empty dict `{}` is typed by the compiler as `Dict[Any, Any]`, but it should be assigned to any `dict` type, since it's empty. The same error didn't happen when the expected type is `Dict[str, bool]` for example, only when it's encapsulated inside another type (i.e. `List[Dict[str, bool]]`)
https://github.com/CityOfZion/neo3-boa/blob/d82842a2bfd16855b81754d5b44d8b53bee34ed6/boa3_test/test_sc/list_test/ListWithEmptyTypedDict.py#L1-L8
**Tests** …

Can't use an empty dict if the type hint not any is inside another type

---

boa3/analyser/typeanalyser.py
boa3/model/type/annotation/optionaltype.py
boa3/model/type/annotation/uniontype.py
boa3_test/test_sc/optional_test/OptionalArgumentInsideDict.py
boa3_test/tests/compiler_tests/test_optional.py

The compilation would fail when setting a function argument type as a collection of nullable values. Using both `Optional[some_type]` and `Union[None, some_type]` caused an `Internal compiler error`.
https://github.com/CityOfZion/neo3-boa/blob/c2f11f52a4f6c308bcd1f40f2316ef1cc203bd58/boa3_test/test_sc/optional_test/OptionalArgumentInsideDict.py#L6-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c2f11f52a4f6c308bcd1f40f2316ef1cc203bd58/boa3_test/tests/compiler_tests/test_optional.py#L84-L99
**Platform:**

Couldn't use Optional typing to define a Dict

---

boa3/cpm.py
requirements.txt
setup.py

N/A
@lllwvlvwlll mentioned that [CPM](https://github.com/CityOfZion/cpm) installation is one of hurdles for usage. While there are multiple installation options for CPM (`brew` for OSX, `dpkg` for linux and more), non are integrated with boa. Since he's doing workshops with Python/boa it seemed logical to at least integrate it here.
I've looked into making it a pip installable package that could become a simple dependency in the `requirements.txt` file. Apparently I was not the only one who tried packaging a binary on pip (by looking at the google/SO results), but nobody had a solution. The problem is not in packaging it, the problem is in automatically moving it into a location on the user path to allow execution after installation. …

CPM install script

---

boa3_test/test_drive/neoxp/utils.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/test_sc/interop_test/runtime/ImportInteropRuntime.py
boa3_test/test_sc/interop_test/runtime/ImportRuntime.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_interop/test_json.py
boa3_test/tests/compiler_tests/test_interop/test_policy.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/compiler_tests/test_interop/test_stdlib.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py
boa3_test/tests/default.neo-express

Changed the execution tests of the compiled smart contracts related to Neo interop functions to use TestRunner instead of TestEngine
**Tests**

Refactor Neo interop functions unit tests to use test runner

---

boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_dict.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_none.py
boa3_test/tests/compiler_tests/test_optional.py
boa3_test/tests/compiler_tests/test_string.py
boa3_test/tests/compiler_tests/test_tuple.py
boa3_test/tests/compiler_tests/test_typing.py
boa3_test/tests/compiler_tests/test_union.py

Changed the execution tests of the compiled smart contracts related to Python built-in types to use TestRunner instead of TestEngine
**Tests**

Refactor Python built-in types unit tests to use test runner

---

boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/compiler_tests/test_event.py
boa3_test/tests/compiler_tests/test_import.py
boa3_test/tests/compiler_tests/test_neo_types.py

Changed the execution tests of the compiled smart contracts related to Boa built-in types to use TestRunner instead of TestEngine
**Tests**

Refactor Boa built-in types unit tests to use test runner

---

boa3/analyser/analyser.py
boa3/compiler/codegenerator/codegenerator.py
boa3/compiler/codegenerator/codegeneratorvisitor.py
boa3/compiler/compiler.py

When there were unexpected errors during the code generator, the compilation process wouldn't stop. This caused incorrectly generated code that could fail during execution after the contract is compiled.
Changed the code generator specialized class to check if there are new errors logged before generating the output files

Don't compile where there are internal errors during code generation

---

boa3/constants.py
boa3_test/test_drive/model/invoker/invokeresult.py
boa3_test/test_drive/model/invoker/neobatchinvoke.py
boa3_test/test_drive/model/invoker/neoinvokecollection.py
boa3_test/test_drive/neoxp/batch.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py
boa3_test/tests/compiler_tests/test_native/test_contract_management.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py
boa3_test/tests/compiler_tests/test_native/test_gas.py
boa3_test/tests/compiler_tests/test_native/test_ledger.py
boa3_test/tests/compiler_tests/test_native/test_neo.py
boa3_test/tests/compiler_tests/test_native/test_oracle.py
boa3_test/tests/compiler_tests/test_native/test_policy.py
boa3_test/tests/compiler_tests/test_native/test_rolemanagement.py
boa3_test/tests/compiler_tests/test_native/test_stdlib.py
boa3_test/tests/test_app_tests/test_test_runner.py

Changed the execution tests of the compiled smart contracts related to Neo Native Contracts to use TestRunner instead of TestEngine
**Tests**

Refactor native contract unit tests to use test runner

---

boa3/compiler/codegenerator/variablegenerationdata.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/variable_test/VariablesWithSameName.py
boa3_test/test_sc/variable_test/VariablesWithSameNameClassVariableAndLocal.py
boa3_test/test_sc/variable_test/VariablesWithSameNameInstanceAndLocal.py
boa3_test/tests/compiler_tests/test_variable.py

Now `user_class` will only be sent if it's not a method, so it won't try to check if `symbol` is in class when not needed.
https://github.com/CityOfZion/neo3-boa/blob/d9ac69155bb588b89d5239e1fb436af49b2dfa8e/boa3_test/test_sc/variable_test/VariablesWithSameName.py#L1-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d9ac69155bb588b89d5239e1fb436af49b2dfa8e/boa3_test/tests/compiler_tests/test_variable.py#L928-L943
**Platform:**

Using variables with the same name on different scopes is bugged

---

boa3/internal/neo3/contracts/findoptions.py
boa3_test/test_sc/interop_test/storage/FindOptionsMismatchedType.py
boa3_test/test_sc/interop_test/storage/FindOptionsValues.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py

Neo will add a new value for FindOptions (BACKWARDS), so it will also be added to neo3-boa.
https://github.com/CityOfZion/neo3-boa/blob/3d8cf826ca528d76e26d48201c600bb6c7b1fa49/boa3_test/test_sc/interop_test/storage/FindOptionsValues.py#L40-L42
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3d8cf826ca528d76e26d48201c600bb6c7b1fa49/boa3_test/tests/compiler_tests/test_interop/test_storage.py#L1000-L1035
**Platform:**
Since the functionality was not merged on Neo yet, testing the storage won't be possible now

Update Neo enum values in boa builtin package

---

boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/test_drive/testrunner/utils.py
boa3_test/test_sc/interop_test/iterator/IteratorNext.py
boa3_test/test_sc/interop_test/iterator/IteratorValue.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py
boa3_test/tests/compiler_tests/test_native/test_neo.py

Changed the execution tests of the compiled smart contracts related to Iterators to use TestRunner instead of TestEngine
**Tests**
Since there's an issue in the Test Runner (https://github.com/ngdenterprise/neo-test/issues/46) when returning Iterators in the result stack, the most I managed to do is read what it was returned so the json decode doesn't break. Getting the value directly from neo express doesn't return data from the Iterator

Refactor Iterator unit tests to use test runner

---

boa3/builtin/interop/crypto/__init__.py
boa3/internal/model/builtin/interop/crypto/__init__.py
boa3/internal/model/builtin/interop/crypto/bls12381addmethod.py
boa3/internal/model/builtin/interop/crypto/bls12381deserializemethod.py
boa3/internal/model/builtin/interop/crypto/bls12381equalmethod.py
boa3/internal/model/builtin/interop/crypto/bls12381mulmethod.py
boa3/internal/model/builtin/interop/crypto/bls12381pairingmethod.py
boa3/internal/model/builtin/interop/crypto/bls12381serializemethod.py
boa3/internal/model/builtin/interop/interop.py
boa3_test/test_sc/interop_test/crypto/Bls12381Add.py
boa3_test/test_sc/interop_test/crypto/Bls12381Deserialize.py
boa3_test/test_sc/interop_test/crypto/Bls12381Equal.py
boa3_test/test_sc/interop_test/crypto/Bls12381Mul.py
boa3_test/test_sc/interop_test/crypto/Bls12381Pairing.py
boa3_test/test_sc/interop_test/crypto/Bls12381Serialize.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py

Added [CryptoLib.BLS12_381.cs ](https://github.com/neo-ngd/neo/blob/29bc3b21ed1c27b8b11e01d2d61f1b9e75b1acd1/src/Neo/SmartContract/Native/CryptoLib.BLS12_381.cs) methods.
https://github.com/CityOfZion/neo3-boa/blob/49faa0a9ac87324bf008eebc08d33e93563ce4c4/boa3_test/test_sc/interop_test/crypto/Bls12381Mul.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/49faa0a9ac87324bf008eebc08d33e93563ce4c4/boa3_test/tests/compiler_tests/test_interop/test_crypto.py#L712-L814
**Platform:**
This issue is not testing the call, just checking the Opcode generated. To test it, it will be necessary to wait for it to be accepted, merged into Neo, and …

Update Neo Native Contracts interfaces (crypto)

---

boa3/internal/analyser/typeanalyser.py
boa3/internal/model/builtin/method/intmethod.py
boa3_test/tests/compiler_tests/test_builtin_method.py

#770
It fixed incorrect type-checking validation that caused this implementation of the int constructor not to compile.
https://github.com/CityOfZion/neo3-boa/blob/499b46534aad1d244df0793baf82d210ef8c2d6f/boa3_test/test_sc/built_in_methods_test/IntStr.py#L4-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/499b46534aad1d244df0793baf82d210ef8c2d6f/boa3_test/tests/compiler_tests/test_builtin_method.py#L2270-L2476
**Platform:**

Add support to int constructor with str and bytes values

---

boa3/internal/neo/smart_contract/notification.py
boa3_test/examples/nep11_non_divisible.py
boa3_test/test_drive/model/network/payloads/testtransaction.py
boa3_test/test_drive/neoxp/utils.py
boa3_test/test_drive/testrunner/blockchain/notification.py
boa3_test/test_drive/testrunner/blockchain/transactionlog.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/boa_test.py
boa3_test/tests/examples_tests/test_nep11_non_divisible.py
boa3_test/tests/run_unit_tests.py

Changed the execution tests of the NEP-11 example to use TestRunner instead of TestEngine
**Tests**

Refactor NEP-11 unit tests to use Test Runner

---

boa3/boa3.py
boa3/builtin/__init__.py
boa3/internal/analyser/analyser.py
boa3/internal/analyser/importanalyser.py
boa3/internal/cli_commands/build_command.py
boa3/internal/compiler/compiler.py
boa3/internal/constants.py
boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/builtincallable.py
boa3/internal/model/builtin/builtinproperty.py
boa3/internal/model/builtin/builtinsymbol.py
boa3/internal/model/builtin/internal/__init__.py
boa3/internal/model/builtin/internal/getenvmethod.py
boa3/internal/model/imports/builtin.py
boa3/internal/model/imports/package.py
boa3_test/test_sc/boa_built_in_methods_test/Env.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_boa_builtin_method.py
boa3_test/tests/compiler_tests/test_variable.py

Included an optional argument to the compiler to be able to pass a given environment identifier to the smart contract. This allows specific environment validations to be easily included in the smart contract logic without the need to rewrite anything before compiling (i.e. changes in smart contracts hashes between testnet and mainnet)
https://github.com/CityOfZion/neo3-boa/blob/edaed98f7c082ca4c8e1b261eb9ee6788d30cab4/boa3_test/test_sc/boa_built_in_methods_test/Env.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/edaed98f7c082ca4c8e1b261eb9ee6788d30cab4/boa3_test/tests/compiler_tests/test_boa_builtin_method.py#L33-L57
**Platform:**

Configure an environment argument to be passed to the compiler and accessible from the smart contract

---

boa3_test/examples/wrapped_neo.py

`burn` was marked as `safe`, however its implementation modifies storage. Storage cannot be modified when a method is marked safe. ([ref](https://github.com/neo-project/neo/blob/718fc9ff4063ea19cff5818627aff4d908995b8d/src/Neo/SmartContract/ApplicationEngine.cs#L217) this effectively says "safe == READ_ONLY")
removed the safe flag

Fix burn() permission on wrapped_neo example

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/model/type/annotation/metatype.py
boa3_test/test_sc/event_test/MismatchedTypeCreateEventWithInteropInterface.py
boa3_test/tests/compiler_tests/test_event.py

Trying to use InteropInterfaces as event arguments failed when executing the smart contract in the blockchain, but neo3-boa allowed it to compile. Changed to not compile when trying to create an event with an InteropInterface argument type.
https://github.com/CityOfZion/neo3-boa/blob/3cab3ddcc0372e5523ba8d263238795e4ee8f64f/boa3_test/test_sc/event_test/MismatchedTypeCreateEventWithInteropInterface.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3cab3ddcc0372e5523ba8d263238795e4ee8f64f/boa3_test/tests/compiler_tests/test_event.py#L351-L354
**Platform:**

Can't create an event with a InteropInterface parameter

---

boa3/builtin/compile_time/__init__.py
boa3/internal/analyser/moduleanalyser.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHashOnMetadata.py
boa3_test/tests/compiler_tests/test_contract_interface.py

Setting permissions on NeoMetadata object only accepted literal string representations of smart contracts script hashes. Modified to also accept bytes data and fixed the missed symbol error raised when trying to use user-implemented contract interface to get its script hash.
https://github.com/CityOfZion/neo3-boa/blob/0aa0410c59facf82960e3456000580bbccdbff9d/boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHashOnMetadata.py#L5-L18
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0aa0410c59facf82960e3456000580bbccdbff9d/boa3_test/tests/compiler_tests/test_contract_interface.py#L248-L274
**Platform:**

Access hash property of classes annotated with @contract in the metadata definition function

---

boa3/internal/cli_commands/build_command.py

Added the option to choose where the compiled files will be generated and its name.
```cli
neo3-boa compile .\path\to\sc.py -op .\another\path\here.nef
```
```cli
neo3-boa compile .\path\to\sc.py --output-path .\another\path\here.nef
```
**Tests**
Was tested locally, another issue will implement cli tests on this project.
**Platform:**

Include output option to cli compile command

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/compiledmetadata.py
boa3_test/examples/wrapped_gas.py
boa3_test/tests/compiler_tests/test_contract_interface.py
boa3_test/tests/examples_tests/test_htlc.py
boa3_test/tests/examples_tests/test_update_contract.py

Changed code generation to include the called methods from implemented contract interfaces to the manifest permissions, having the same behavior as the called native contract methods
https://github.com/CityOfZion/neo3-boa/blob/a51b934775d2bcc500558d6efe53d163d75204ce/boa3_test/test_sc/contract_interface_test/ContractInterfaceCodeOptimization.py#L7-L35
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/a51b934775d2bcc500558d6efe53d163d75204ce/boa3_test/tests/compiler_tests/test_contract_interface.py#L123-L151
**Platform:**

Include methods from contract interfaces to manifest permissions

---

boa3/builtin/interop/crypto/__init__.py
boa3/builtin/nativecontract/cryptolib.py
boa3/internal/model/builtin/interop/crypto/verifywithecdsa.py
boa3_test/test_sc/interop_test/crypto/VerifyWithECDsa.py
boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Bool.py
boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Int.py
boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Bool.py
boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Int.py
boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsa.py
boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsaSecp256k1Bool.py
boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsaSecp256k1Int.py
boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsaSecp256r1Bool.py
boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsaSecp256r1Int.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py

Changed the `verify_with_ecdsa` first parameter type to be the same as the signature parameter type
https://github.com/CityOfZion/neo3-boa/blob/2a87a32d8ec7e9900368cc232a8d65aa6a14f54d/boa3_test/test_sc/interop_test/crypto/VerifyWithECDsa.py#L1C1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/2a87a32d8ec7e9900368cc232a8d65aa6a14f54d/boa3_test/tests/compiler_tests/test_interop/test_crypto.py#L428-L430
**Platform:**

verify_with_ecdsa of cryptolib has message param as "Any" instead of byte[], like on C#

---

boa3/internal/analyser/astanalyser.py

Stopped code from compiling when pressing Crtl+C
**Platform:**
- Python version: 3.8
Had to use the `from None` to [suppress exception context](https://peps.python.org/pep-0409/), otherwise it would print a lot of tracebacks

Compilation should stop with KeyboardInterrupt

---

boa3/internal/compiler/filegenerator.py
boa3_test/test_sc/interop_test/contract/CallScriptHash.py
boa3_test/test_sc/interop_test/contract/CallScriptHashWithCast.py
boa3_test/test_sc/interop_test/contract/CallScriptHashWithFlags.py
boa3_test/test_sc/interop_test/contract/CallScriptHashWithoutArgs.py
boa3_test/test_sc/interop_test/contract/ImportContract.py
boa3_test/test_sc/interop_test/contract/ImportInteropContract.py
boa3_test/tests/compiler_tests/test_metadata.py

The default permissions value on metadata was implemented as the wildcard, but now will be empty
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5f01fb1d1d88b7fec130ff80bfa1e63f807dc690/boa3_test/tests/compiler_tests/test_metadata.py#L401-L407
**Platform:**
- Python version:Python 3.8

Fix default permissions value on metadata

---

boa3/cli.py
boa3/internal/cli_commands/__init__.py
boa3/internal/cli_commands/compile_command.py

When using `neo3-boa` on the terminal it shows the help, also a `-v` and `--version` flags for version were added.
`neo3-boa` to show the help
`neo3-boa -v` to show the version
`neo3-boa --version` to show the version
**Platform:**
Also changed the name of the `build_command` and `BuildCommand` to `compile_command` and `CompileCommand`. (The CLI command was already `compile`, I just renamed the files/class)

Boa cli commands should show help message by default

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/compiler/compiler.py
boa3/internal/compiler/filegenerator/filegenerator.py
boa3/internal/compiler/filegenerator/importdata.py
boa3/internal/model/debuginstruction.py
boa3/internal/model/method.py
boa3/internal/model/type/classes/classtype.py
boa3_test/test_sc/generation_test/GenerationWithUserModuleNameImports.py
boa3_test/tests/boa_test.py
boa3_test/tests/compiler_tests/test_file_generation.py
docs/ContractExamplesTest.md

Fixed debug info generation when there are files importing user modules instead of directly importing methods or variables.
https://github.com/CityOfZion/neo3-boa/blob/2b626a84d7c0a954736222949ce2e7c51cf8b63c/boa3_test/test_sc/import_test/ImportModuleWithoutInit.py#L1-L14
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/2b626a84d7c0a954736222949ce2e7c51cf8b63c/boa3_test/tests/compiler_tests/test_file_generation.py#L575-L600
**Platform:**
- OS: tested on Windows 10 x64

Add all smart contract related files paths and fix file indexes in sequence point on debug file

---

boa3/internal/analyser/importanalyser.py

https://app.clickup.com/t/864emdffj
`site-packages` modules took precedence over project modules during compilation. If there is a name collision this can lead to confusing import errors because an IDE will not show any errors and will correctly resolve imports, whereas the `importanalyser` will not. This PR makes sure that the project root is the first place searched for instead of the last place
The problematic area was this
https://github.com/CityOfZion/neo3-boa/blob/580de6156cf6acebe18896a6ead3711f535a641c/boa3/internal/analyser/importanalyser.py#L56-L62
Then take a project with a package called `events` but also a 3rd party package installed in the same environment (in this case `neo-mamba`) that happens to have a dependency on a …

Fix import error due to incorrect sys.path

---

boa3/internal/compiler/codegenerator/codegenerator.py

The code generator was generating different static slots for the same static variable that is used in different files due to failing to get the internal unique id of this variable.

Fix incorrect code generated for statics

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/model/builtin/interop/interop.py

There was an error in `CodeGenerator` `get_symbol` that didn't find interop symbols in class methods even when those symbols are imported in the file. Replicated the logic used to ensure built-in symbols are properly generated

Fix storage.find FindOptions are ignored and generates incorrect code

---

boa3/internal/analyser/analyser.py
boa3/internal/analyser/supportedstandard/standardanalyser.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsEventFromPackage.py
boa3_test/test_sc/metadata_test/aux_package/internal_package/__init__.py
boa3_test/tests/compiler_tests/test_metadata.py

When importing a package, the verification would not try and check the events inside the package.
https://github.com/CityOfZion/neo3-boa/blob/29eefdeb992db284e87ce438cb78b218316fbd52/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsEventFromPackage.py#L1-L43
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/29eefdeb992db284e87ce438cb78b218316fbd52/boa3_test/tests/compiler_tests/test_metadata.py#L193-L218
**Platform:**

false error on missing NEP-11 transfer event

---

boa3/internal/cli_commands/compile_command.py

Removed the piece of code that used the shell path instead of the smart contract path.
`neo3-boa compile path/to/smartcontract.py` now has the same behaviour as `neo3-boa compile path/to/smartcontract.py  --project-path path/to` 
**Platform:**
Add any other context about the problem here.

Default the execution path to the execution directory

---

boa3/internal/analyser/analyser.py
boa3/internal/analyser/astoptimizer.py
boa3/internal/analyser/builtinfunctioncallanalyser.py
boa3/internal/analyser/constructanalyser.py
boa3/internal/analyser/supportedstandard/standardanalyser.py
boa3/internal/analyser/typeanalyser.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py

The root folder wasn't being used when initializing some classes that inherited `IAstAnalyser`.
**Platform:**

investigate and fix project-path / root_folder correctness

---

boa3/builtin/interop/storage/__init__.py
boa3/internal/compiler/filegenerator/filegenerator.py

> The signature of find  is defined as
> ```python
> def find(prefix: ByteString,
>          context: StorageContext = None,
>          options: FindOptions = FindOptions.NONE) -> Iterator:
> ```
> This suggests that you can call find with something like this
> ```python
> return find(mk_token_index_key(self._account_id), None, FindOptions.VALUES_ONLY)
> ```
> which actually gives a compilation error
> ```bash
> ERROR: 49:58 - Expected type 'StorageContext', got 'none' instead	 </home/erik/code/props-item-clean/contract/models/user.py>
> ```
The same thing happened with all the storage methods has a StorageContext argument. Fixed by changing the default value in interfaces of those methods to `get_context()`. …

Incorrect type for StorageContext on storage methods

---

boa3/internal/model/standards/neostandard.py
boa3/internal/model/standards/nep11standard.py
boa3/internal/model/standards/standardmethod.py
boa3_test/examples/nep11_non_divisible.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsBytes.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsStr.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsMissingImplementationNEP11OptionalMethods.py
boa3_test/tests/compiler_tests/test_metadata.py

It's now possible to use just `bytes` or `str` when trying to implement a `ByteString` parameter.
https://github.com/CityOfZion/neo3-boa/blob/9e242717637d5045ab069f454134691e183921f2/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsBytes.py#L51C1-L54
https://github.com/CityOfZion/neo3-boa/blob/9e242717637d5045ab069f454134691e183921f2/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsStr.py#L51-L54
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/9e242717637d5045ab069f454134691e183921f2/boa3_test/tests/compiler_tests/test_metadata.py#L295-L311
**Platform:**

Change types for NEP-11 standards checking

---

boa3/builtin/compile_time/__init__.py
boa3_test/test_sc/metadata_test/MetadataImportingExternalContractBeforeMetadataMethod.py
boa3_test/test_sc/metadata_test/aux_package/internal_package/external_contract.py
boa3_test/tests/compiler_tests/test_metadata.py

When the **ModuleAnalyser** tried to read the metadata object, it would try to compile and execute the code from top to bottom, so the imports will be executed before the `@metadata` function on the main file, however, the decorator `display_name` on `boa3/builtin/compile_time/__init__.py` was returning None instead of a function, thus raising an error and stopping the execution before reaching the `@metadata` function.
https://github.com/CityOfZion/neo3-boa/blob/7eca426d30621d27551bd874cb13fdf21d9c76cf/boa3/internal/analyser/moduleanalyser.py#L367-L399
https://github.com/CityOfZion/neo3-boa/blob/7eca426d30621d27551bd874cb13fdf21d9c76cf/boa3_test/test_sc/metadata_test/aux_package/internal_package/external_contract.py#L1-L22 …

Can't compile smart contract with metadata function

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/function_test/CallExternalContractWithReturnNone.py
boa3_test/tests/compiler_tests/test_function.py

The `Opcode.SYSCALL` returns a value even if the return of the method is None. 
Currently, Neo3-boa will only DROP the unused value if the return type is not None. 
So, now, whenever a SYSCALL is being used it will always be followed with a DROP if it's unused
https://github.com/CityOfZion/neo3-boa/blob/e27d57603e1ab75108b1e00cc259dcf841ecf521/boa3_test/test_sc/function_test/NoReturnFunction.py#L1-L6
https://github.com/CityOfZion/neo3-boa/blob/e27d57603e1ab75108b1e00cc259dcf841ecf521/boa3_test/test_sc/function_test/CallExternalContractWithReturnNone.py#L1-L14
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e27d57603e1ab75108b1e00cc259dcf841ecf521/boa3_test/tests/compiler_tests/test_function.py#L1647-L1659
**Platform:**
- OS: …

Incorrect result stack size with methods with no return after a call_contract

---

Makefile

Seems like building documentation with `make docs` outputs the documentation in `/docs/build/` not `/docs/_build/`. The browser that automatically opens will fail. This fixes the path that the browser opens.

Fix make docs browser url

---

boa3/builtin/interop/contract/__init__.py

The signature of `call_contract()` specifies args as `args: Sequence = ()`, the example in the docstrings does not provide a sequence.

Fix example in docstring

---

boa3/builtin/interop/blockchain/__init__.py
boa3/builtin/nativecontract/contractmanagement.py
boa3/builtin/nativecontract/ledger.py
boa3/internal/model/builtin/interop/blockchain/getblockmethod.py
boa3/internal/model/builtin/interop/blockchain/getcontractmethod.py
boa3/internal/model/builtin/interop/blockchain/gettransactionfromblockmethod.py
boa3/internal/model/builtin/interop/blockchain/gettransactionmethod.py
boa3_test/examples/nep11_non_divisible.py
boa3_test/test_sc/interop_test/blockchain/GetBlockByHash.py
boa3_test/test_sc/interop_test/blockchain/GetBlockByIndex.py
boa3_test/test_sc/interop_test/blockchain/GetContract.py
boa3_test/test_sc/interop_test/blockchain/GetTransaction.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockInt.py
boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockUInt256.py
boa3_test/test_sc/interop_test/blockchain/ImportBlockchain.py
boa3_test/test_sc/interop_test/blockchain/ImportInteropBlockchain.py
boa3_test/test_sc/native_test/contractmanagement/GetContract.py
boa3_test/test_sc/native_test/ledger/GetBlockByHash.py
boa3_test/test_sc/native_test/ledger/GetBlockByIndex.py
boa3_test/test_sc/native_test/ledger/GetBlockMismatchedTypes.py
boa3_test/test_sc/native_test/ledger/GetTransaction.py
boa3_test/test_sc/native_test/ledger/GetTransactionFromBlockInt.py
boa3_test/test_sc/native_test/ledger/GetTransactionFromBlockUInt256.py
boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
boa3_test/tests/compiler_tests/test_native/test_ledger.py

Some functions on interop.blockchain were not properly indicating that they had an Optional return type. Changed the return type and added some more docstring examples
https://github.com/CityOfZion/neo3-boa/blob/3bfe91adb9218995c92a08e4e52a95f8e6c8647b/boa3_test/test_sc/interop_test/blockchain/GetContract.py#L1-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3bfe91adb9218995c92a08e4e52a95f8e6c8647b/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L45-L76
**Platform:**

fix return types of interop.blockchain functions

---

boa3_test/tests/boa_test.py
boa3_test/tests/cli_tests/cli_test.py
boa3_test/tests/cli_tests/test_cli.py
boa3_test/tests/cli_tests/test_compile.py
boa3_test/tests/cli_tests/utils.py

Transformed the `cli_tests` folder into a Python package with the `__init__.py` file and separated the tests into different classes for each command. Also added _COMPILER_LOCK on the compiler tests
**Platform:**

fix CLI tests

---

boa3/boa3.py
boa3/internal/analyser/analyser.py
boa3/internal/analyser/astanalyser.py
boa3/internal/analyser/astoptimizer.py
boa3/internal/analyser/builtinfunctioncallanalyser.py
boa3/internal/analyser/constructanalyser.py
boa3/internal/analyser/importanalyser.py
boa3/internal/analyser/moduleanalyser.py
boa3/internal/analyser/supportedstandard/standardanalyser.py
boa3/internal/analyser/typeanalyser.py
boa3/internal/cli_commands/compile_command.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3/internal/compiler/codegenerator/initstatementsvisitor.py
boa3/internal/compiler/compiler.py
boa3_test/test_sc/import_test/ImportFailInnerNotExistingMethod.py
boa3_test/tests/boa_test.py
boa3_test/tests/cli_tests/cli_test.py
boa3_test/tests/cli_tests/test_cli.py
boa3_test/tests/cli_tests/test_compile.py
boa3_test/tests/compiler_tests/test_logger.py

Changed to stop the compilation on the first error found.
The previous behavior of trying to get all errors weren't removed to ensure the correct behavior on unit tests that expect a specific compiler error.
Added a flag on cli to disable fail fast. It's true by default.
```python
from boa3.boa3 import Boa3
Boa3.compile('path/to/smart/contract.py', fail_fast=True)
Boa3.compile_and_save('path/to/smart/contract.py')  # fail fast is True by default
Boa3.compile_and_save('path/to/smart/contract.py', fail_fast=False)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/cae5c9ad1c2eb07c1be9e891358eaf3c318e9710/boa3_test/tests/compiler_tests/test_logger.py#L5-L13
**Platform:** …

Fail fast on compilation error

---

boa3_test/examples/simple_nep17.py
boa3_test/tests/examples_tests/test_simple_nep17.py

Added a simpler NEP-17 example smart contract without mint. This smart contract will be referenced on the [Neo Tutorials ](https://developers.neo.org/tutorials) page
**Tests**
Created a `test_simple_nep17.py` file
**Platform:**

Add a simpler NEP-17 token

---

boa3/boa3.py
boa3/internal/cli_commands/compile_command.py
boa3/internal/compiler/compiler.py
boa3_test/tests/boa_test.py
boa3_test/tests/cli_tests/test_compile.py

Included `log_level` argument to `compile` and `compile_and_save` and `--log-level` flag to cli `compile` command to change which message are shown on log. Default log level is set to `ERROR`
```python
from boa3.boa3 import Boa3
Boa3.compile('path/to/smart/contract.py', log_level='INFO')
Boa3.compile_and_save('path/to/smart/contract.py')  # log level is set to ERROR by default
Boa3.compile_and_save('path/to/smart/contract.py', fail_fast='WARN')
```
```shell
neo3-boa compile path/to/smart/contract.py --log-level INFO
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/cae5c9ad1c2eb07c1be9e891358eaf3c318e9710/boa3_test/tests/compiler_tests/test_logger.py#L5-L13
**Platform:**

"Info" log messages to be shown depending on different log levels

---

boa3/internal/model/builtin/classmethod/indexbytesstringmethod.py
boa3/internal/model/builtin/classmethod/indexsequencemethod.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_string.py

Refactored `index` built-in method.
**Tests**
The previously written tests (had to change one that was failing when it shouldn't).
**Platform:**
- OS: Windows 11x64

Refactor index implementation to improve readability

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3_test/test_sc/bytes_test/BytesClassVariableSlicing.py
boa3_test/test_sc/bytes_test/BytesInstanceVariableSlicing.py
boa3_test/test_sc/bytes_test/BytesPropertySlicing.py
boa3_test/test_sc/string_test/StringClassVariableSlicing.py
boa3_test/test_sc/string_test/StringInstanceVariableSlicing.py
boa3_test/test_sc/string_test/StringPropertySlicing.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_string.py

Internally, the function that is used to get an instance variable is the same that gets an element from an array, but by itself, it can't get the type of the instance variable from a class, so it will be changed to the correct value after the function is over.
In other words, inside `codegenerator.py`, on `convert_get_item`, it won't be possible to find the `value_type` inside it, because it's a class, not an array.
https://github.com/CityOfZion/neo3-boa/blob/8341a68b4d0ec62a9e7150869aadea1e3539275f/boa3/internal/compiler/codegenerator/codegenerator.py#L1208-L1211
So, on `convert_class_variable`, it will change to the correct value if it's not `any`.
https://github.com/CityOfZion/neo3-boa/blob/8341a68b4d0ec62a9e7150869aadea1e3539275f/boa3/internal/compil …

String slice is incorrectly generated

---

boa3/internal/analyser/moduleanalyser.py
boa3_test/test_sc/list_test/ListComprehensionStr.py
boa3_test/tests/compiler_tests/test_list.py

List comprehension is not supported, but the compiler doesn't raise any errors when it is used in a smart contract script.
Changed to raise compiler error when list comprehension is used. It's going to be implemented in future tasks.
https://github.com/CityOfZion/neo3-boa/blob/3d257251d5991ac2c5c9f45d226d9181f0f3c928/boa3_test/test_sc/list_test/ListComprehensionStr.py#L4-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3d257251d5991ac2c5c9f45d226d9181f0f3c928/boa3_test/tests/compiler_tests/test_list.py#L2107-L2112
**Platform:**

Compilation should fail with not supported feature

---

boa3/builtin/compile_time/__init__.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHash.py
boa3_test/test_sc/contract_interface_test/ContractInterfaceGetHashOnMetadata.py
docs/source/calling-smart-contracts.md

Some IDEs were giving a warning that `hash` did not exist, even tho it exists when you use the `@contract` decorator.
So, the `hash: UInt160` variable was added on contract interfaces when it was being used. 
**Platform:**
Changed import, because I think it should have been done on https://github.com/CityOfZion/neo3-boa/commit/5fa9250d874ddc4a27bd38c8459b9be1716fe009
https://github.com/CityOfZion/neo3-boa/blob/9e304af862361f8b91a4846b08e01281ad1cf1c5/docs/source/calling-smart-contracts.md?plain=1#L71

Change the documentation to avoid IDE errors - ContractInterface has no attribute "hash"

---

boa3/builtin/contract/__init__.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/method/__init__.py
boa3/internal/model/builtin/method/minmethod.py
boa3/internal/model/builtin/method/tohexstrmethod.py
boa3_test/test_sc/built_in_methods_test/HexStr.py
boa3_test/test_sc/built_in_methods_test/HexStrMismatchedType.py
boa3_test/test_sc/built_in_methods_test/HexStrTooFewParameters.py
boa3_test/test_sc/built_in_methods_test/HexStrTooManyParameters.py
boa3_test/test_sc/built_in_methods_test/HexStrVariable.py
boa3_test/tests/compiler_tests/test_builtin_method.py

Logging bytes data has runtime errors when the data have non-printable bytes values. Included `to_hex_str` method to convert data objects to its readable hex string equivalent.
https://github.com/CityOfZion/neo3-boa/blob/659a244f5fec5f2bae6963129d3dca5e99e2f38a/boa3_test/test_sc/built_in_methods_test/HexStr.py#L2-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/659a244f5fec5f2bae6963129d3dca5e99e2f38a/boa3_test/tests/compiler_tests/test_builtin_method.py#L609-L677
**Platform:**

Create a bytes to hextring converter so it can be printed on log

---

boa3_test/test_drive/model/network/payloads/testblock.py
boa3_test/test_drive/model/network/payloads/testtransaction.py
boa3_test/test_drive/neoxp/batch.py
boa3_test/test_drive/neoxp/utils.py
boa3_test/test_drive/testrunner/blockchain/block.py
boa3_test/test_drive/testrunner/blockchain/transaction.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/test_drive/neoxp/utils.py
boa3_test/tests/test_drive/testrunner/boa_test_runner.py

Fix #1100 
`neoxp.utils` package had a `NEOXP_CONFIG` object that was created using the neo express config from boa3 unit tests by default, but this file is not included in the boa3 package install and the object wasn't updated when other neo express config files were used to initialize the TestRunner.
Moved this default config object to the boa3 unit test specific package.
Use NeoTestRunner with a neo express config file different from boa3's

Test runner uses incorrect neo-express path resolving

---

boa3_test/test_drive/neoxp/batch.py
boa3_test/test_drive/neoxp/executor.py
boa3_test/test_drive/neoxp/utils.py
boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/test_drive/neoxp/utils.py
boa3_test/tests/test_drive/testrunner/boa_neoxp_batch.py
boa3_test/tests/test_drive/testrunner/boa_test_runner.py

`filelock` package is used to speed up boa3 unit test by running them parallelly, but this shouldn't be required to use NeoTestRunner.
Removed all code that uses filelock in its logic from `boa3_test.test_drive` packages and moved to the packaged related to boa3 unit tests

No module name 'filelock' error raised when trying to use NeoTestRunner interface

---

boa3/internal/analyser/moduleanalyser.py
boa3_test/test_sc/class_test/DelClass.py
boa3_test/test_sc/dict_test/DelPair.py
boa3_test/test_sc/list_test/DelItem.py
boa3_test/test_sc/variable_test/DelVariable.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/compiler_tests/test_dict.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_variable.py

The `del` keyword is not supported, but the smart contract would still be compiled when using it. Now it won't.
https://github.com/CityOfZion/neo3-boa/blob/582f702bc0e4969c7f84c209653793e65175db46/boa3_test/test_sc/variable_test/DelVariable.py#L1-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/582f702bc0e4969c7f84c209653793e65175db46/boa3_test/tests/compiler_tests/test_variable.py#L958-L960
**Platform:**

Add an error when using the del keyword

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/set_test/SetConstructor.py
boa3_test/test_sc/set_test/SetLiteral.py
boa3_test/test_sc/set_test/SetTyping.py
boa3_test/tests/compiler_tests/test_set.py

Importing Set from typing or using the `set` keyword throws an error, but implicitly using a Set was not throwing. Not it does throw an error.
https://github.com/CityOfZion/neo3-boa/blob/1033863af5f3a5eabbb08962c734bb55f8f214a7/boa3_test/test_sc/set_test/SetLiteral.py#L1-L8
**Tests**
Created tests for other circumstances that would already throw an error
https://github.com/CityOfZion/neo3-boa/blob/1033863af5f3a5eabbb08962c734bb55f8f214a7/boa3_test/tests/compiler_tests/test_set.py#L1-L19
**Platform:**

Add an error when implicitly using Sets

---

boa3/internal/analyser/moduleanalyser.py
boa3_test/test_sc/list_test/SetListIntoListSlice.py
boa3_test/tests/compiler_tests/test_list.py

When doing a slice attribution, the compiler would not stop compiling. Now it does
https://github.com/CityOfZion/neo3-boa/blob/11772837c5ab8ede350574722bcb35c809277366/boa3_test/test_sc/list_test/SetListIntoListSlice.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/11772837c5ab8ede350574722bcb35c809277366/boa3_test/tests/compiler_tests/test_list.py#L282-L284
**Platform:**
- OS:  Windows 10 x64

Add an error when using the list slice assignment

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/variable_test/AssignFunction.py
boa3_test/tests/compiler_tests/test_variable.py

The compilation did not stop when you tried to attribute a function to a variable, only when you were trying to call it later.
Now you get a NotSupported error.
https://github.com/CityOfZion/neo3-boa/blob/fbbb3c7edfc163c87a01ad3489b096305c4b9231/boa3_test/test_sc/variable_test/AssignFunction.py#L1-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fbbb3c7edfc163c87a01ad3489b096305c4b9231/boa3_test/tests/compiler_tests/test_variable.py#L962-L964
**Platform:**

Add an error when trying to attribute a function to a variable

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/function_test/InnerFunction.py
boa3_test/tests/compiler_tests/test_function.py

You'll get a Not Supported error when you try to create inner functions.
https://github.com/CityOfZion/neo3-boa/blob/f8f849c53ac2b301c8fb4de32ce587b4f382d20c/boa3_test/test_sc/function_test/InnerFunction.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f8f849c53ac2b301c8fb4de32ce587b4f382d20c/boa3_test/tests/compiler_tests/test_function.py#L1661-L1663
**Platform:**
- Python version:  Python 3.7

Add a new error when trying to create inner function

---

boa3_test/test_drive/testrunner/neo_test_runner.py
boa3_test/tests/test_app_tests/test_test_runner.py

Added a validation on `deploy_contract` to throw a FileNotFoundError, if the `.nef` doesn't exist.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8ae79f919bc6c7bb753b34d99023d50745e69802/boa3_test/tests/test_app_tests/test_test_runner.py#L121-L145
**Platform:**

test-runner deploy_contract should validate NEF exists

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/function_test/LambdaFunction.py
boa3_test/tests/compiler_tests/test_function.py

Added a NotSupportedOperation error when trying to use lambda functions.
https://github.com/CityOfZion/neo3-boa/blob/d92558e52338cc73aa6cb35e79e519289a25f984/boa3_test/test_sc/function_test/LambdaFunction.py#L1-L3
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d92558e52338cc73aa6cb35e79e519289a25f984/boa3_test/tests/compiler_tests/test_function.py#L1665-L1667
**Platform:**

Add another error when using lambda functions

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/string_test/FormattedStringLiteral.py
boa3_test/tests/compiler_tests/test_string.py

The previous error was: `Expected type 'str', got 'none' instead`, now it's a NotSupported error.
https://github.com/CityOfZion/neo3-boa/blob/81bf9754420d61b4bd2d317b8c14b19aedd080fe/boa3_test/test_sc/string_test/FormattedStringLiteral.py#L1-L3
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/81bf9754420d61b4bd2d317b8c14b19aedd080fe/boa3_test/tests/compiler_tests/test_string.py#L1480-L1482
**Platform:**

Change the error when trying to use f-string

---

boa3/internal/analyser/typeanalyser.py
boa3_test/test_sc/class_test/UserClassWithInstanceMethodFromClass.py
boa3_test/tests/compiler_tests/test_class.py

The error was `The following operation is not supported: 'Example.some_method'`, now it is `The following operation is not supported: Calling instance method from class: 'Example.some_method'`
https://github.com/CityOfZion/neo3-boa/blob/6687308eadbb2cf20caef508da8d357b978da5a8/boa3_test/test_sc/class_test/UserClassWithInstanceMethodFromClass.py#L1-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/6687308eadbb2cf20caef508da8d357b978da5a8/boa3_test/tests/compiler_tests/test_class.py#L476-L479
**Platform:**

Add more information on the error when calling an instance method from a class

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/class_test/ClassPropertyAndParameterWithSameName.py
boa3_test/tests/compiler_tests/test_class.py

There was an internal problem when creating a class property and a parameter with the same names.
https://github.com/CityOfZion/neo3-boa/blob/e81de1c65e84bb11a74d3a917cd134b9d7de06ff/boa3_test/test_sc/class_test/ClassPropertyAndParameterWithSameName.py#L1-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e81de1c65e84bb11a74d3a917cd134b9d7de06ff/boa3_test/tests/compiler_tests/test_class.py#L877-L891
**Platform:**

Property and parameter with same name error

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/model/builtin/decorator/displaynamedecorator.py
boa3_test/test_sc/function_test/BuiltinContractDecoratorWithFunction.py
boa3_test/test_sc/function_test/CustomDecoratorWithGlobalFunction.py
boa3_test/tests/compiler_tests/test_function.py

Added an error when a user tries to use a function they created as a decorator, and another error when using `contract` decorator on a function
https://github.com/CityOfZion/neo3-boa/blob/c4efb526cbfd394c79f27c1b365990129b93d54d/boa3_test/test_sc/function_test/CustomDecoratorWithGlobalFunction.py#L1-L11
https://github.com/CityOfZion/neo3-boa/blob/c4efb526cbfd394c79f27c1b365990129b93d54d/boa3_test/test_sc/function_test/BuiltinContractDecoratorWithFunction.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c4efb526cbfd394c79f27c1b365990129b93d54d/boa3_test/tests/compiler_tests/test_function.py#L1661-L1667
**Platform:**

Add an error when trying to use decorators with functions other than the builtin ones

---

boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/variable_test/GetGlobalSameIdFromImport.py
boa3_test/tests/compiler_tests/test_variable.py

There was an error in the code generator when using multiple files with variables having the same name, even when the variables weren't imported. When importing a package with a variable with the same name as another variable in the root file the generator incorrectly uses the same value as if they were the same variable.
https://github.com/CityOfZion/neo3-boa/blob/b901d246d44274a2fa79d1404c81ba2dd3b9cae8/boa3_test/test_sc/variable_test/GetGlobalSameIdFromImport.py#L4-L16
https://github.com/CityOfZion/neo3-boa/blob/b901d246d44274a2fa79d1404c81ba2dd3b9cae8/boa3_test/test_sc/variable_test/ListGlobalAssignment.py#L3-L21
It was using the value from the root file for the `a` variable in the above example, returning `42` instead of `[1, …

Incorrect value when using variables in different module with the same name

---

setup.py

While testing the mypy extension for VSCode we found some problems with the mypy recognizing of boa3 packages.
Changed the package data on setup to fix those problems
Install [Mypy Type Checker](https://marketplace.visualstudio.com/items?itemName=ms-python.mypy-type-checker) for VSCode and write a smart contract script importing `boa3.builtin` packages
**Tests**
A clear and concise description of how you tested it.
how it was:
after the change on setup:
**Platform:**

Change setup.py configuration to generate typing information

---

boa3/internal/analyser/supportedstandard/__init__.py
boa3/internal/analyser/supportedstandard/standardanalyser.py
boa3/internal/model/standards/nep11divisiblestandard.py
boa3/internal/model/standards/nep11nondivisiblestandard.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsMissingEventNEP11.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsMissingImplementationNEP11Divisible.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11Divisible.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11DivisibleOptionalMethods.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11NonDivisible.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11NonDivisibleOptionalMethods.py
boa3_test/tests/compiler_tests/test_metadata.py

Previously, only non-divisible NEP-11 tokens were being validated (if it were a divisible it would raise an error), now there is a divisible NEP-11 validator too.
https://github.com/CityOfZion/neo3-boa/blob/cf775d7d1c949244c1c2f9f697f7d8b28ab57b87/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11Divisible.py#L1-L60
https://github.com/CityOfZion/neo3-boa/blob/cf775d7d1c949244c1c2f9f697f7d8b28ab57b87/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsNEP11NonDivisible.py#L1-L50
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/cf775d7d1c949244c1c2f9f697f7d8b28ab57b87/boa3_test/tests/compiler_tests/test_metadata.py#L283-L291
https://github.com/CityOfZion/neo3-boa/blob/cf775d7d1c949244c1c2f9f697f7d8b28ab5 …

Implement NEP-11 standard validator for divisible NFTs

---

boa3/builtin/interop/iterator/__init__.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3/internal/model/builtin/interop/interop.py
boa3/internal/model/builtin/interop/iterator/__init__.py
boa3_test/test_sc/for_test/IteratorCondition.py
boa3_test/tests/compiler_tests/test_for.py

The default `for` loop is generated by internally saving the current iterating index and using it to access the next value, but that's not how the value in an `Iterator` is accessed, which causes runtime exceptions. Fixed to properly access `Iterator` `value` and `next`.
https://github.com/CityOfZion/neo3-boa/blob/bc9fd9ce3507f7d003fb0c28a5b72cb11988c233/boa3_test/test_sc/for_test/IteratorCondition.py#L8-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bc9fd9ce3507f7d003fb0c28a5b72cb11988c233/boa3_test/tests/compiler_tests/test_for.py#L96-L159
**Platform:**

Fix for loop generation when iterating Iterator class

---

.circleci/config.yml
boa3_test/tests/boa_test.py
boa3_test/tests/cli_tests/cli_test.py
boa3_test/tests/cli_tests/test_compile.py
boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_constant.py
boa3_test/tests/compiler_tests/test_file_generation.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py
boa3_test/tests/compiler_tests/test_neo_types.py
boa3_test/tests/examples_tests/test_htlc.py
boa3_test/tests/neo_tests/smart_contract/test_neffile.py

Updated dotnet installation on CircleCI config file to properly install dotnet for testing. There was some conflict with the dotnet folders after the `apt get`, it was solved by removing any possible folder related to dotnet before installing it.
Updated circleci/python orb to a version where the problem happened with Python 3.10

Investigate problem related to dotnet installation on CircleCI orbs

---

boa3/builtin/contract/Nep17Contract.py
boa3/builtin/contract/__init__.py
boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/contract/__init__.py
boa3/internal/model/builtin/contract/nep17_interface_methods/__init__.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacebalanceofmethod.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacedecimalsmethod.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacemethod.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacesymbolmethod.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacetotalsupplymethod.py
boa3/internal/model/builtin/contract/nep17_interface_methods/nep17interfacetransfermethod.py
boa3/internal/model/builtin/contract/nep17contract.py
boa3_test/test_sc/nep17_contract_interface_test/Nep17BalanceOf.py
boa3_test/test_sc/nep17_contract_interface_test/Nep17Decimals.py
boa3_test/test_sc/nep17_contract_interface_test/Nep17Symbol.py
boa3_test/test_sc/nep17_contract_interface_test/Nep17TotalSupply.py
boa3_test/test_sc/nep17_contract_interface_test/Nep17Transfer.py
boa3_test/tests/compiler_tests/test_nep17_contract_interface.py

Added a class that has the NEP-17 methods that can be called be the user.
https://github.com/CityOfZion/neo3-boa/blob/b23d1c18862b7664bb6bdaedd5dd58585fe9c7b7/boa3_test/test_sc/nep17_contract_interface_test/Nep17BalanceOf.py#L1-L12
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/b23d1c18862b7664bb6bdaedd5dd58585fe9c7b7/boa3_test/tests/compiler_tests/test_nep17_contract_interface.py#L10-L21
**Platform:**
- Python version: Python 3.10
The contract hash and methods name were not added to the permission field on the manifest.json in this issue.

Implement an interface for NEP-17 smart contracts

---

pyproject.toml

`find_packages` did not detect `boa3_test` as a package including only its sub-packages `boa3_test.tests` and `boa3_test.test_drive`. Included it explicitly in the setup packages
**Additional context**
This PR will have conflicts when compared with #1141. It's better to wait for it to be merged before merging this one.

boa3_test folder not included in distribution for python 3.11

---

boa3/internal/analyser/astoptimizer.py
boa3/internal/analyser/moduleanalyser.py
boa3/internal/analyser/typeanalyser.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/match_case_test/AnyTypeMatchCase.py
boa3_test/test_sc/match_case_test/BoolTypeMatchCase.py
boa3_test/test_sc/match_case_test/IntTypeMatchCase.py
boa3_test/test_sc/match_case_test/OuterVariableInsideMatch.py
boa3_test/test_sc/match_case_test/StrTypeMatchCase.py
boa3_test/test_sc/match_case_test/UnsupportedCase.py
boa3_test/test_sc/match_case_test/VarExistingInAllCases.py
boa3_test/tests/compiler_tests/test_match_case.py

Added support to basic match-case operations
https://github.com/CityOfZion/neo3-boa/blob/5acaf9c75f4c35e14b559bd12882d4f6632b1e5e/boa3_test/test_sc/match_case_test/VarExistingInAllCases.py#L1-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5acaf9c75f4c35e14b559bd12882d4f6632b1e5e/boa3_test/tests/compiler_tests/test_match_case.py#L11-L35
**Platform:**
- Python version: Python 3.10

Add support to match-case (switch) with bool, int and str

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/analyser/typeanalyser.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/method/__init__.py
boa3/internal/model/builtin/method/printclassmethod.py
boa3/internal/model/builtin/method/printsequencemethod.py
boa3/internal/model/builtin/method/strclassmethod.py
boa3/internal/model/builtin/method/strmethod.py
boa3/internal/model/builtin/method/strsequencemethod.py
boa3_test/test_sc/string_test/FStringAnyVar.py
boa3_test/test_sc/string_test/FStringBoolVar.py
boa3_test/test_sc/string_test/FStringBytesVar.py
boa3_test/test_sc/string_test/FStringIntVar.py
boa3_test/test_sc/string_test/FStringLiteral.py
boa3_test/test_sc/string_test/FStringSequenceVar.py
boa3_test/test_sc/string_test/FStringStringVar.py
boa3_test/test_sc/string_test/FStringUnionVar.py
boa3_test/test_sc/string_test/FStringUserClassVar.py
boa3_test/test_sc/string_test/FormattedStringLiteral.py
boa3_test/tests/compiler_tests/test_string.py

Added support to f-string using str, int, bool, bytes, list, and class type variables.
https://github.com/CityOfZion/neo3-boa/blob/967debd0f2d1101a49c3d32d60a42534f2614bd7/boa3_test/test_sc/string_test/FStringStringVar.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/967debd0f2d1101a49c3d32d60a42534f2614bd7/boa3_test/tests/compiler_tests/test_string.py#L1492-L1510
**Platform:**
Other type verifications will be implemented on another issue

CU-2ewf14b - Add support to String Interpolation (f-string)

---

boa3/internal/analyser/typeanalyser.py
boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/classmethod/__init__.py
boa3/internal/model/builtin/classmethod/sortmethod.py
boa3/internal/model/callable.py
boa3/internal/model/type/collection/sequence/mutable/listtype.py
boa3_test/test_sc/list_test/SortArgsList.py
boa3_test/test_sc/list_test/SortKeyList.py
boa3_test/test_sc/list_test/SortList.py
boa3_test/test_sc/list_test/SortListAny.py
boa3_test/test_sc/list_test/SortListOfList.py
boa3_test/test_sc/list_test/SortReverseFalseList.py
boa3_test/test_sc/list_test/SortReverseTrueList.py
boa3_test/tests/compiler_tests/test_list.py

Implemented `list.sort` method with insertion sort algorithm
https://github.com/CityOfZion/neo3-boa/blob/923328ead94af0f5b828d0aeaa0c204024623d46/boa3_test/test_sc/list_test/SortList.py#L5-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/923328ead94af0f5b828d0aeaa0c204024623d46/boa3_test/tests/compiler_tests/test_list.py#L2196-L2274
**Platform:**
- Python version: Python 3.10+
Since `sort` has keyword-only arguments, which are not supported by boa yet, the code may be changed when we work on supporting it.

Add support to List sort method

---

boa3_test/test_sc/for_test/ForWithContractInterface.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_for.py

Started using `BoaTestCase` on `TestFor`
**Platform:**

Refactor test_for.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_any.py

Refactored `test_any` file to use `boatestconstructor` in place of `TestRunner` for unit testing

Refactor test_any.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_optional.py

Refactored test_optional file to use boatestconstructor in place of TestRunner for unit testing

CU-86a1hurr1 - Refactor test_optional.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_neo_types.py

Refactored `test_neo_types` file to use `boatestconstructor` in place of `TestRunner` for unit testing

CU-86a1hurbv - Refactor test_neo_types.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_bytes.py
pyproject.toml

Refactored `test_bytes` file to use `boatestconstructor` in place of `TestRunner` for unit testing
Some tests were left as is, but the refactored version was left commented, because there are some issues with `Buffer` results when converting to `string` or `bytes`.

Cu 86a1hunew

---

.circleci/config.yml
boa3/internal/neo/vm/type/ContractParameterType.py
boa3_test/tests/run_unit_tests.py
pyproject.toml

Fixed manifest json deserialization.
Enum changes on Python 3.12 broke `Enum.__getattr__`.

CU-86a1hepnw - Fix tests using Python 3.12 (parsing manifest JSON)

---

boa3_test/tests/compiler_tests/test_reversed.py

Refactored `test_reversed` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

CU-86a1hur68 - Refactor test_reversed.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_variable.py

Refactored `test_variable` file to use `boatestconstructor` in place of `TestRunner` for unit testing.
Some refactored tests were left commented and the original left as is, because the storage isn't working properly, but they are mapped to be fixed by #86a1z5xy9

CU-86a1huqre - Refactor test_variable.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_class.py
boa3_test/tests/run_unit_tests.py

Refactored `test_class` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

CU-86a1hunm9 - Refactor test_class.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_boa_builtin_method.py

Refactored `test_boa_builtin_method` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

CU-86a1hun58 - Refactor test_boa_builtin_method.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_import.py

Refactored `test_import` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

CU-86a1huq5p - Refactor test_import.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_constant.py

Refactored `test_constant` file to use `boatestconstructor` in place of TestRunner for unit testing.

Refactor test_constant.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_types.py

Refactored `test_types` file to use `boatestconstructor` in place of TestRunner for unit testing.

Refactor test_types.py to use BoaTestConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_event.py
boa3_test/tests/compiler_tests/test_while.py

Refactored `test_event` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

CU-86a1hupaq - Refactor test_event.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_exception.py

Refactored `test_exception` file to use `boatestconstructor` in place of `TestRunner` for unit testing.

Refactor test_exception.py to use BoaTestConstructor

---

boa3/internal/model/operation/binary/relational/__init__.py
boa3/internal/model/operation/binary/relational/greaterthan.py
boa3/internal/model/operation/binary/relational/greaterthanorequal.py
boa3/internal/model/operation/binary/relational/lessthan.py
boa3/internal/model/operation/binary/relational/lessthanorequal.py
boa3/internal/model/operation/binary/relational/strbytesgreaterthan.py
boa3/internal/model/operation/binary/relational/strbytesgreaterthanorequal.py
boa3/internal/model/operation/binary/relational/strbyteslessthan.py
boa3/internal/model/operation/binary/relational/strbyteslessthanorequal.py
boa3/internal/model/operation/binaryop.py
boa3_test/tests/compiler_tests/test_relational.py

Refactored `test_relational` file to use `BoaTestCase `in place of BoaTest for unit testing.
Also fixed a bug on Gt, GtE, Lt, LtE operations when using str/bytes arguments

CU-86a1hur7f - Refactor test_relational.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_dict.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_logger.py
boa3_test/tests/compiler_tests/test_range.py
boa3_test/tests/compiler_tests/test_string.py

Refactored `test_logger` file to use `BoaTestCase` in place of `BoaTest` for unit testing.
Also removed `FaultException` imports when `boatestcase` was already imported

Refactor test_logger.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_set.py

Refactored `test_set.py` file to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_set.py to use BoaTestConstructor

---

boa3_test/test_sc/metadata_test/MetadataInfoGroups.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_metadata.py

Refactored `test_metadata` file to use `BoaTestCase` in place of `BoaTest` for unit testing.

Refactor test_metadata.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_typing.py

Refactored `test_typing.py `file to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_typing.py to use BoaTestConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_policy.py

Refactored `test_interop/test_policy.py `file to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_interop/test_policy.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_role.py

Refactored `test_interop/test_role.py `file to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_interop/test_role.py to use BoaConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/examples_tests/test_nep17.py
boa3_test/tests/examples_tests/test_simple_nep17.py

Refactored `test_nep17.py` and `test_simple_nep17.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpnc78 - Refactor test_nep17.py and test_simple_nep17.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_native/test_cryptolib.py

Refactored `test_native/test_cryptolib.py `files to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_native/test_cryptolib.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_native/test_stdlib.py

Refactored `test_native/test_stdlib.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86drpndra - Refactor test_interop/test_stdlib.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_stdlib.py

Refactored `test_interop/test_stdlib.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86drpnc88 - Refactor test_native/test_stdlib.py to use BoaConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_native/test_oracle.py
boa3_test/tests/compiler_tests/test_while.py
boa3_test/tests/examples_tests/test_nep17.py
boa3_test/tests/examples_tests/test_simple_nep17.py

Refactored `test_native/test_oracle.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.
Couldn't make Send Oracle Response to work, so I kept the tests related to this as they are. There's another task to work on these later

Refactor test_native/test_oracle.py to use BoaConstructor

---

boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py

Refactored `test_interop/test_iterator.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

Refactor test_interop/test_iterator.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_json.py

Refactored `test_interop/test_json.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpnc8k - Refactor test_interop/test_json.py to use BoaConstructor

---

boa3_test/tests/annotation.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_import.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py

Refactored `test_interop/test_runtime.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpnc7w - Refactor test_interop/test_runtime.py to use BoaConstructor

---

boa3_test/tests/annotation.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_interop/test_iterator.py
boa3_test/tests/compiler_tests/test_native/test_contract_management.py

Refactored `test_native/test_contract_management.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpnc8v - Refactor test_native/test_contract_management.py to use BoaConstructor

---

boa3_test/tests/annotation.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_native/test_contract_management.py
boa3_test/tests/compiler_tests/test_native/test_ledger.py
boa3_test/tests/stackitem.py

Refactored `test_native/test_ledger.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpnc9h - Refactor test_native/test_ledger.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_native/test_rolemanagement.py

Refactored `test_native/test_rolemanagement.py `files to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_native/test_rolemanagement.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_crypto.py

Refactored `test_interop/test_crypto.py `files to use `BoaTestCase `in place of `BoaTest `for unit testing.

Refactor test_interop/test_crypto.py to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_interop/test_contract.py
boa3_test/tests/compiler_tests/test_native/test_contract_management.py
boa3_test/tests/event.py

Refactored `test_interop/test_contract.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpndpe - Refactor test_interop/test_contract.py to use BoaConstructor

---

boa3/builtin/contract/__init__.py
boa3/internal/model/builtin/contract/neoaccountstatetype.py
boa3_test/tests/annotation.py
boa3_test/tests/compiler_tests/test_native/test_neo.py

Refactored `test_native/test_neo.py `files to use `BoaTestCase `in place of `BoaTest `for unit testing.
Another value (`LastGasPerVote`) was added [to NeoAccountState ](https://github.com/neo-project/neo/commit/df534f6b0c700e1c7b3eb1315c4560fedce793b8).

CU-86drpnc9a - Refactor test_native/test_neo.py to use BoaConstructor

---

boa3_test/examples/nep11_non_divisible.py
boa3_test/tests/boatestcase.py
boa3_test/tests/compiler_tests/test_interop/test_storage.py
boa3_test/tests/examples_tests/test_nep11_non_divisible.py

Refactored `examples_tests/test_nep11_non_divisible.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

CU-86drpncqn - Refactor example_tests/test_nep11_non_divisible.py to use BoaConstructor

---

boa3_test/examples/htlc.py
boa3_test/tests/examples_tests/test_htlc.py

Refactored `example_tests/test_htlc.py` files to use `BoaTestCase `in place of `BoaTest `for unit testing.

CU-86drpncjw - Refactor example_tests/test_htlc.py to use BoaConstructor

---

boa3_test/examples/ico.py
boa3_test/tests/examples_tests/test_ico.py

Refactored `example_tests/test_ico.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86drpnd2j - Refactor example_tests/test_ico.py to use BoaConstructor

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/analyser/typeanalyser.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3/internal/model/callable.py
boa3/internal/model/type/annotation/ellipsistype.py
boa3/internal/model/type/collection/icollection.py
boa3/internal/model/type/collection/sequence/tupletype.py
boa3/internal/model/type/type.py
boa3_test/test_sc/any_test/AnyTuple.py
boa3_test/test_sc/class_test/NotificationSetVariables.py
boa3_test/test_sc/dict_test/MismatchedTypeKeysDict.py
boa3_test/test_sc/dict_test/MismatchedTypeValuesDict.py
boa3_test/test_sc/for_test/ForElse.py
boa3_test/test_sc/for_test/NestedFor.py
boa3_test/test_sc/logical_test/LogicMismatchedOperandLogicOr.py
boa3_test/test_sc/native_test/neo/GetCandidates.py
boa3_test/test_sc/tuple_test/EmptyTupleAssignment.py
boa3_test/test_sc/tuple_test/IndexTuple.py
boa3_test/test_sc/tuple_test/IndexTupleDefaults.py
boa3_test/test_sc/tuple_test/IndexTupleEndDefault.py
boa3_test/test_sc/tuple_test/MultipleExpressionsInLine.py
boa3_test/test_sc/tuple_test/TupleGetValue.py
boa3_test/test_sc/tuple_test/TupleGetValueMismatchedType.py
boa3_test/test_sc/tuple_test/TupleGetValueTypedTuple.py
boa3_test/test_sc/tuple_test/TupleIndexMismatchedType.py
boa3_test/test_sc/tuple_test/TupleSetValue.py
boa3_test/tests/compiler_tests/test_tuple.py
boa3_test/tests/compiler_tests/test_types.py

Changed how the compiler handles tuple annotations to have the expected Python behavior.
Before it was handled the same way as list annotations, making `tuple[int]`, `tuple[int, int]`, `tuple[int, ...]`, `tuple[int, int, int]` and similar to be handled as the same.
Also added support to ellipsis (`...` annotation) to be able to handle tuples without specific length

CU-86drpncat - Wrong tuple type hint is compiled on Neo3-boa

---

boa3/builtin/contract/__init__.py
boa3/internal/analyser/moduleanalyser.py
boa3/internal/model/builtin/method/createeventmethod.py
boa3_test/examples/auxiliary_contracts/update_contract.py
boa3_test/examples/nep11_non_divisible.py
boa3_test/examples/update_contract.py
boa3_test/test_sc/event_test/EventNep17TransferBuilt.py
boa3_test/test_sc/generation_test/ManifestOptionalUnionEvent.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsBytes.py
boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandardsByteStringAsStr.py
boa3_test/test_sc/metadata_test/aux_package/internal_package/__init__.py
boa3_test/tests/compiler_tests/test_event.py
boa3_test/tests/compiler_tests/test_file_generation.py

Fixed the behavior of `typeA | typeB` to have the same behavior as `Union[typeA, typeB]` on Event definitions.
https://github.com/CityOfZion/neo3-boa/blob/446f3ad102944a780720aaf8d123450874e889a5/boa3_test/test_sc/event_test/EventNep17TransferBuilt.py#L4-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/446f3ad102944a780720aaf8d123450874e889a5/boa3_test/tests/compiler_tests/test_event.py#L158-L239

CU-86dt50abt - Error when compiling using union type notation with | (bitwise or) in Event argument type

---

boa3_test/tests/compiler_tests/test_interop/test_crypto.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py
boa3_test/tests/compiler_tests/test_native/test_neo.py
boa3_test/tests/compiler_tests/test_nep17_contract_interface.py
boa3_test/tests/examples_tests/test_htlc.py
boa3_test/tests/stackitem.py

Refactored `test_nep17_contract_interface.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86dt89pje - Refactor test_nep17_contract_interface.py to use BoaConstructor

---

boa3_test/tests/cli_tests/cli_test.py
boa3_test/tests/cli_tests/test_cli.py
boa3_test/tests/cli_tests/test_compile.py

Refactored `tests/cli_tests` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86dt89kf4 - Refactor BoaCliTest on cli_tests to use BoaConstructor

---

boa3_test/tests/compiler_tests/test_match_case.py

Refactored `test_match_case.py` files to use `BoaTestCase` in place of `BoaTest` for unit testing.

#86dt89p29 - Refactor test_match_case.py to use BoaConstructor

---

docs/make-pdf.py

There was a outdated miktex package, added a check and a verify to see if packages are ok

CU-86dtaf4yf - Fix Sphinx documentation generation

---

boa3/internal/analyser/moduleanalyser.py
boa3_test/tests/compiler_tests/test_bytes.py
boa3_test/tests/compiler_tests/test_variable.py

When assigning a variable and defining the type of said as a constant (like a number or hardcoded string) of a different type, it should throw an error.
**Platform:**

CU-86drpndnn - Throw a compilation error when variable type declaration doesn't match the assigned value type

---

boa3/internal/analyser/moduleanalyser.py
boa3/internal/compiler/codegenerator/codegenerator.py
boa3/internal/compiler/codegenerator/codegeneratorvisitor.py
boa3_test/test_sc/match_case_test/AnyTypeMatchCase.py
boa3_test/test_sc/match_case_test/DictTypeMatchCase.py
boa3_test/tests/compiler_tests/test_match_case.py

Now it's possible to use dictionaries on the match case
```python
from boa3.builtin.compile_time import public
@public
def main(dict_: dict) -> str:
match dict_:
case {
'ccccc': None,
'ab': 'cd',
'12': '34',
'xy': 'zy',
'00': '55',
}:
return "big dictionary"
case {'key': 'value'}:
return "key and value"
case {}:
return "empty dict"
case _:
return "default return"
```
**Tests**
```python
async def test_dict_type_match_case(self):
await self.set_up_contract('DictTypeMatchCase.py')
def match_case(dict_: dict) -> str:
match dict_:
case {
'ccccc': None,
'ab': 'cd',
'12': '34',
'xy': 'zy',
'00': '55',
}:
return "big dictionary"
case {'key': 'value'}:
return "key and value"
case {}:
return "empty dict"
case _:
return "default return"
arg = …
```

Add support to match-case (switch) with dict without conditionals

---

boa3_test/test_sc/dict_test/DictValueWithMethodReturn.py
boa3_test/tests/compiler_tests/test_dict.py

Couldn't reproduce the bug, I think it was fixed in other issues. Included in the unit tests to make sure it works properly.
https://github.com/CityOfZion/neo3-boa/blob/14586f005b856f5ebd83a0094ae48a453cb83558/boa3_test/test_sc/dict_test/DictValueWithMethodReturn.py#L9-L21
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/14586f005b856f5ebd83a0094ae48a453cb83558/boa3_test/tests/compiler_tests/test_dict.py#L596-L615

#86drpnca2 - Compilation error when trying to attribute an operation directly into the value of a dictionary

---

boa3/internal/model/builtin/native/neo_contract_methods/__init__.py
boa3/internal/model/builtin/native/neo_contract_methods/getcommitteeaddressmethod.py
boa3/internal/model/builtin/native/neo_contract_methods/getregisterpricemethod.py
boa3/internal/model/builtin/native/neoclass.py
boa3/sc/contracts/neotoken.py
boa3_test/test_sc/native_test/neo/GetCommitteeAddress.py
boa3_test/test_sc/native_test/neo/GetRegisterPrice.py
boa3_test/tests/compiler_tests/test_native/test_neo.py

Added `get_committee_address` and `get_register_price` to the NeoToken native contract interface at `boa3.sc.contracts`
```python
from boa3.sc.compiletime import public
from boa3.sc.contracts import NeoToken
@public
def main() -> int:
return NeoToken.get_register_price()
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/570584a03508d808c4b37633206bce2b6c805f80/boa3_test/tests/compiler_tests/test_native/test_neo.py#L589-L603
**Platform:**
Couldn't test the `get_committee_address` method with the current neo-go config, so it's just checking the opcode and it was invoked on the testnet.

CU-86dthh0nm - Update NeoToken native contract

---

boa3/internal/model/builtin/interop/interop.py
boa3/internal/model/builtin/interop/policy/__init__.py
boa3/internal/model/builtin/interop/policy/getattributefeemethod.py
boa3/internal/model/builtin/interop/policy/setattributefeemethod.py
boa3/internal/model/builtin/interop/policy/transactionattributetype.py
boa3/internal/model/builtin/native/policyclass.py
boa3/internal/model/sc/__init__.py
boa3/internal/neo3/network/payloads/transactionattributetype.py
boa3/sc/contracts/policycontract.py
boa3/sc/types/__init__.py
boa3_test/test_sc/native_test/policy/GetAttributeFee.py
boa3_test/test_sc/native_test/policy/SetAttributeFee.py
boa3_test/tests/compiler_tests/test_native/test_policy.py

Added `get_attribute_fee` and `set_attribute_fee` to the `PolicyContract` from `boa3.sc.contracts`.
Added `TransactionAttributeType` to `boa3.sc.types`
https://github.com/CityOfZion/neo3-boa/blob/50bf881206b2f370d569be897251fa3c3368ada0/boa3_test/test_sc/native_test/policy/SetAttributeFee.py#L1-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/50bf881206b2f370d569be897251fa3c3368ada0/boa3_test/tests/compiler_tests/test_native/test_policy.py#L45-L74
**Platform:**

#86dthh0zp - Update native PolicyContract

---

boa3/builtin/compile_time/__init__.py
boa3/sc/compiletime/__init__.py

#1222
Fixing the wrong default value on the `safe` parameter at the `public` decorator
**Platform:**

public decorator signature is misleading

---

boa3/internal/analyser/moduleanalyser.py
boa3_test/test_sc/interop_test/runtime/NotifyWithDynamicName.py
boa3_test/tests/compiler_tests/test_interop/test_runtime.py

You can't emit an event that is not on the manifest.
https://github.com/CityOfZion/neo3-boa/blob/3912663cd50d476dfef6bc11e2b441a334442946/boa3_test/test_sc/interop_test/runtime/NotifyWithName.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3912663cd50d476dfef6bc11e2b441a334442946/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L285-L297
**Platform:**

It's necessary to add notify event names on the manifest

---

boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_file_generation.py
boa3_test/tests/compiler_tests/test_list.py
boa3_test/tests/compiler_tests/test_string.py

Removed BoaTestRunner from some tests that don't need it.
**Platform:**

CU-86dtn3pzu - Refactor remaining tests that uses TestRunner

---

pyproject.toml

The last release showed 2 warnings in CI
```
/tmp/build-env-5woftfi1/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
and
```
corresp(dist, …
```

ci: fix setuptools deprecation warnings

---

docs/source/calling-smart-contracts.md
docs/source/getting-started.md

close #1285 
Update the documentation to use `boa3.sc` instead of `boa3.builtin`

Update boa3.builtin imports to boa3.sc on the documentation

---

boa3/internal/model/builtin/builtin.py
boa3/internal/model/builtin/method/__init__.py
boa3/internal/model/builtin/method/lenmethod.py
boa3/internal/model/builtin/method/lenstrmethod.py
boa3/internal/model/builtin/method/strsplitmethod.py
boa3/internal/model/builtin/native/stdlib/__init__.py
boa3/internal/model/builtin/native/stdlib/stringsplitmethod.py
boa3/internal/model/builtin/native/stdlib/strlenmethod.py
boa3/internal/model/builtin/native/stdlibclass.py
boa3/internal/model/type/primitive/strtype.py
boa3/sc/contracts/stdlib.py
boa3_test/test_sc/native_test/stdlib/StrLen.py
boa3_test/test_sc/native_test/stdlib/StringSplit.py
boa3_test/test_sc/native_test/stdlib/StringSplitRemoveEmptyEntries.py
boa3_test/tests/compiler_tests/test_builtin_method.py
boa3_test/tests/compiler_tests/test_native/test_stdlib.py

close #1302 
- Added StringSplit and StrLen to Boa3
- Changed a little bit how `'string'.split()` and `len('string')` works internally
- If you are using `len` with a string argument, then it will use StdLib, otherwise it will use `Opcode.SIZE`
- Using `Opcode.SIZE` on a string would sometimes return an incorrect length, because some string characters would consist of 2 or more bytes, e.g., "Φ" (`b'\xce\xa6'`) would have size 2 instead of 1
- If you are using `split` with 1 or 2 arguments, then it will use just StdLib, otherwise it will also concatenate the strings back into one when exceeding maxSplit arg. 
https://github.com/CityOfZion/neo3-boa/blob/c83666a17fa01c3326362bdc46ac976183aa4aee/boa3_test/test_sc/native …

Add StringSplit and StrLen methods from StdLib

---

boa3/internal/model/builtin/interop/crypto/ripemd160method.py
boa3/internal/model/builtin/interop/crypto/sha256method.py
boa3/internal/model/builtin/native/crypto_lib/__init__.py
boa3/internal/model/builtin/native/crypto_lib/recoversecp256k1.py
boa3/internal/model/builtin/native/cryptolibclass.py
boa3/sc/contracts/cryptolib.py
boa3_test/test_sc/function_test/ModuleMethodBoa2Test1.py
boa3_test/test_sc/if_test/IfOpCallBoa2Test.py
boa3_test/test_sc/native_test/cryptolib/RecoverSecp256K1.py
boa3_test/test_sc/native_test/cryptolib/Ripemd160Int.py
boa3_test/test_sc/native_test/cryptolib/Ripemd160Str.py
boa3_test/test_sc/native_test/cryptolib/Sha256Bool.py
boa3_test/test_sc/native_test/cryptolib/Sha256Int.py
boa3_test/test_sc/native_test/cryptolib/Sha256Str.py
boa3_test/tests/compiler_tests/test_if.py
boa3_test/tests/compiler_tests/test_native/test_cryptolib.py

#1302 
- Add RecoverSecp256K1 from CryptoLib;
- Change Sha256 and Ripemd160 to only accept `bytes` parameters
- Those methods initially accepted [all types of parameters](https://github.com/neo-project/neo/blob/604541c91b3151ee40a8613cb8534ebc0540fd27/src/neo/SmartContract/ApplicationEngine.Crypto.cs#L21), 
- but it was changed to only [accept `byte[]`](https://github.com/neo-project/neo/blob/d555af07b2888df3dc9d2b6238a122a8c98fbaa1/src/neo/SmartContract/Native/CryptoLib.cs#L27).
https://github.com/CityOfZion/neo3-boa/blob/54df40641d5321d5e768f3dfac39a8005ad86946/boa3_test/test_sc/native_test/cryptolib/RecoverSecp256K1.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/54df40641d5321d5e768f3dfac39a8005ad …

Add RecoverSecp256K1, and change Sha256 and Ripemd160

---

boa3/internal/model/builtin/interop/storage/get/storagegetintmethod.py
boa3/internal/model/builtin/interop/storage/getcheck/storagegetintmethod.py
boa3/internal/model/builtin/method/tointmethod.py
boa3/sc/utils/__init__.py
boa3_test/test_sc/bytes_test/BytesToIntBigEndianArgs.py
boa3_test/test_sc/bytes_test/BytesToIntBigEndianSignedArgs.py
boa3_test/test_sc/bytes_test/BytesToIntDefaultArgs.py
boa3_test/tests/compiler_tests/test_bytes.py

Since, endianness and sign were added to `to_bytes` #1308, they were also added to `to_int` method
https://github.com/CityOfZion/neo3-boa/blob/08c7ff9152e66f997de297a7642221718e78f5b9/boa3_test/test_sc/bytes_test/BytesToIntBigEndianSignedArgs.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/08c7ff9152e66f997de297a7642221718e78f5b9/boa3_test/tests/compiler_tests/test_bytes.py#L95-L155
**Platform:**
- OS: MacOS Tahoe 26.0
- Python version:  Python 3.12

Add endianness and sign to to_int method
