CityOfZion/neo3-boa

boa3/analyser/astanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/model/module.py, boa3/neo/vm/Opcode.py, boa3_test/example/variable_test/AssignLocalWithArgument.py, boa3_test/example/variable_test/ReturnArgument.py, boa3_test/example/variable_test/ReturnLocalVariable.py, boa3_test/example/variable_test/ReturnUndeclaredVariable.py, boa3_test/example/variable_test/UsingUndeclaredVariable.py, boa3_test/tests/test_variable.py
- Assign variable value in other variables
- Variable value as function return
- As operations aren't implemented yet, variable values as operands aren't implemented as well
=> Convert local variables access

boa3/cli.py, setup.py
Command `neo3-boa <contract-path>.py` to run neo3-boa on console.
=> Command line interface for neo3-boa

boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3_test/example/if_test/ConstantCondition.py, boa3_test/example/if_test/IfElse.py, boa3_test/example/if_test/MismatchedTypeCondition.py, boa3_test/example/if_test/NestedIf.py, boa3_test/example/if_test/NoCondition.py, boa3_test/example/if_test/RelationalCondition.py, boa3_test/example/if_test/VariableCondition.py, boa3_test/example/while_test/WhileBoa2Test.py, boa3_test/example/while_test/WhileBoa2Test2.py, boa3_test/tests/test_if.py, boa3_test/tests/test_while.py
- Conditions that don't result in a boolean value won't compile
- Elif and else branches will be implemented in other issues
=> Convert If statement

boa3/analyser/typeanalyser.py, boa3/cli.py, boa3/compiler/codegeneratorvisitor.py, boa3/model/operation/binary/logical/booleanand.py, boa3/model/operation/binary/logical/booleanor.py, boa3/model/operation/binaryop.py, boa3/model/operation/operator.py, boa3/model/operation/unary/booleannot.py, boa3/model/operation/unaryop.py, boa3_test/example/logical_test/BoolAnd.py, boa3_test/example/logical_test/BoolNot.py, boa3_test/example/logical_test/BoolOr.py, boa3_test/example/logical_test/BoolOrThreeElements.py, boa3_test/example/logical_test/MismatchedOperandAnd.py, boa3_test/example/logical_test/MismatchedOperandNot.py, boa3_test/example/logical_test/MixedOperations.py, boa3_test/example/while_test/MultipleRelationalCondition.py, boa3_test/tests/test_logical.py, boa3_test/tests/test_relational.py, boa3_test/tests/test_while.py, setup.py
- Implemented the logical operations `and`, `or` and `not` and the boolean inequality
- Implemented chained comparisons (ex: `a < b < c`)
=> Convert boolean logic operations

boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/exception/CompilerError.py, boa3/model/builtin/builtin.py, boa3/model/builtin/builtinmethod.py, boa3/model/builtin/lenmethod.py, boa3/model/type/genericsequencetype.py, boa3/model/type/strtype.py, boa3/model/type/type.py, boa3_test/example/built_in_methods_test/LenMismatchedType.py, boa3_test/example/built_in_methods_test/LenString.py, boa3_test/example/built_in_methods_test/LenTooFewParameters.py, boa3_test/example/built_in_methods_test/LenTooManyParameters.py, boa3_test/example/built_in_methods_test/LenTuple.py, boa3_test/tests/test_builtin_method.py, boa3_test/tests/test_types.py
- Implemented the builtin function `len()` for the types already implemented (`str` and `tuple`)
=> Convert len builtin method

boa3/__init__.py, boa3/analyser/astanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/cli.py, boa3/compiler/filegenerator.py, boa3/exception/CompilerError.py, boa3/exception/CompilerWarning.py, boa3/model/operation/operation.py, boa3/model/type/booltype.py, boa3/model/type/genericsequencetype.py, boa3/model/type/inttype.py, boa3/model/type/itype.py, boa3/model/type/nonetype.py, boa3/model/type/sequencetype.py, boa3/model/type/strtype.py, boa3/neo/utils/serializer.py, boa3/neo/vm/VMCode.py, boa3/neo/vm/opcode/OpcodeInformation.py, boa3_test/tests/boa_test.py, boa3_test/tests/test_arithmetic.py, boa3_test/tests/test_builtin_method.py, boa3_test/tests/test_file_generation.py, boa3_test/tests/test_function.py, boa3_test/tests/test_if.py, boa3_test/tests/test_logical.py, boa3_test/tests/test_relational.py, boa3_test/tests/test_tuple.py, boa3_test/tests/test_variable.py, boa3_test/tests/test_while.py
- Log compiler errors and warnings
- Log when main method in analysed
- Log methods inclusions in the abi file
=> Include logging

boa3/neo/smart_contract/neffile.py
=> update compiler name to include organisation

README.md
Included some information on README file about the functionalities that Neo3-boa already have and what it will do.
=> Update the README file to include what Neo3-boa does and will do

README.md, boa3/model/operation/binary/logical/booleanand.py, boa3/model/operation/binary/logical/booleanor.py, boa3/model/operation/binary/relational/LessThan.py, boa3/model/operation/binary/relational/Lessthanorequal.py, boa3/model/operation/binary/relational/greaterthan.py, boa3/model/operation/binary/relational/identity.py, boa3/model/operation/binary/relational/notidentity.py, boa3/model/operation/binary/relational/numericequality.py, boa3/model/operation/binary/relational/numericinequality.py, boa3/model/operation/binary/relational/objectequality.py, boa3/model/operation/binary/relational/objectinequality.py, boa3/model/operation/binaryop.py, boa3_test/example/relational_test/MixedEquality.py, boa3_test/example/relational_test/MixedGreaterOrEqual.py, boa3_test/example/relational_test/MixedGreaterThan.py, boa3_test/example/relational_test/MixedInequality.py, boa3_test/example/relational_test/MixedLessOrEqual.py, boa3_test/example/relational_test/MixedLessThan.py, boa3_test/example/relational_test/StrGreaterOrEqual.py, boa3_test/example/relational_test/StrGreaterThan.py, boa3_test/example/relational_test/StrInequality.py, boa3_test/example/relational_test/StrLessOrEqual.py, boa3_test/example/relational_test/StrLessThan.py, boa3_test/tests/test_relational.py
Complements #8 with the implementation fo string relational operations
=> Convert string relational operations

requirements_dev.txt
bump version is no longer maintained, use the fork that is active
=> change bump version to maintained fork

boa3/compiler/compiler.py, boa3/compiler/filegenerator.py, boa3/model/builtin/interopmethod/runtime/notifymethod.py, boa3_test/tests/boa_test.py, boa3_test/tests/test_file_generation.py
Included the offset of each method into the generated manifest
=> Include method offset information into the abi

boa3/interop/storage/__init__.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/storage/storagedeletemethod.py, boa3_test/example/storage_test/StorageDeleteBytesKey.py, boa3_test/example/storage_test/StorageDeleteMismatchedType.py, boa3_test/example/storage_test/StorageDeleteStrKey.py, boa3_test/tests/test_storage.py
- Implemented function to call delete key-values from local storage.
=> Implement Storage Delete Interop

boa3/model/type/type.py, boa3_test/example/function_test/ReturnIfExpression.py, boa3_test/example/function_test/ReturnIfExpressionMismatched.py, boa3_test/example/if_test/MismatchedIfExp.py, boa3_test/tests/test_function.py, boa3_test/tests/test_if.py
Fix #56 
Fixed evaluation of `if` expressions
=> If Expression Mismatched Types not raised

boa3/analyser/constructanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/neo/vm/opcode/Opcode.py, boa3_test/tests/test_for.py, boa3_test/tests/test_function.py, boa3_test/tests/test_string.py
Complements #24 with the implementation of string iteration
```
def Main() -> str:
a: int = 0
b: str = ''
for x in '3515':
a = a + 1
b = x + b
return b  # expected '5153'
```
=> Implement string iteration

boa3/model/builtin/builtin.py, boa3/model/builtin/builtincallable.py, boa3/model/builtin/decorator/builtindecorator.py, boa3/model/builtin/interop/interopevent.py, boa3/model/builtin/interop/runtime/notifymethod.py, boa3/model/builtin/method/builtinevent.py, boa3/model/builtin/method/builtinmethod.py, boa3_test/tests/test_file_generation.py, boa3_test/tests/test_interop.py
Changed the implementation of notify interop. Notify syscall now receives the [event name](https://github.com/neo-project/neo/pull/1701).
=> Change Notify implementation

boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/compiler/vmcodemapping.py, boa3_test/example/list_test/ListSlicingNegativeEnd.py, boa3_test/example/list_test/ListSlicingNegativeStart.py, boa3_test/example/string_test/StringSlicingNegativeEnd.py, boa3_test/example/string_test/StringSlicingNegativeStart.py, boa3_test/example/tuple_test/TupleSlicingNegativeEnd.py, boa3_test/example/tuple_test/TupleSlicingNegativeStart.py, boa3_test/tests/test_list.py, boa3_test/tests/test_string.py, boa3_test/tests/test_tuple.py
Complements #30 and #73 with negative start and end indexes
```python
string_example = 'example'
list_example = [1, 2, 3]
tuple_example = (4, 5, 6)
a = string_example[-4:-2]
b = list_example[-1:]
c = tuple_example[:-2]
d = list_example[1:-1]
```
=> Sequence slicing with negative values

boa3/analyser/astanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/model/builtin/builtin.py, boa3/model/builtin/method/exceptionmethod.py, boa3/model/type/baseexceptiontype.py, boa3/model/type/type.py, boa3_test/test_sc/exception_test/RaiseExceptionEmptyMessage.py, boa3_test/test_sc/exception_test/RaiseExceptionVariableMessage.py, boa3_test/test_sc/exception_test/RaiseExceptionWithMessage.py, boa3_test/test_sc/exception_test/RaiseExceptionWithoutCall.py, boa3_test/test_sc/exception_test/RaiseMismatchedType.py, boa3_test/test_sc/exception_test/RaiseSpecificException.py, boa3_test/test_sc/exception_test/RaiseVariableException.py, boa3_test/tests/test_exception.py, boa3_test/tests/test_tuple.py
- Implemented the Python's raise exception feature
```python
def foo(bar: int, zubs):
if bar < 0 or zubs < 0:
raise Exception('must not be negative')
if bar * zubs > 1000:
raise ValueError
```
Currently, only `builtin` exception can be used
=> Implement raise Exception

boa3/analyser/constructanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/constants.py, boa3_test/test_sc/for_test/ForBreak.py, boa3_test/test_sc/for_test/ForBreakElse.py, boa3_test/test_sc/while_test/WhileBoa2Test.py, boa3_test/test_sc/while_test/WhileBoa2Test2.py, boa3_test/test_sc/while_test/WhileBreak.py, boa3_test/test_sc/while_test/WhileBreakElse.py, boa3_test/tests/boa_test.py, boa3_test/tests/test_for.py, boa3_test/tests/test_while.py
Implemented the `break` loop statement
```python
def break_example(arg_list: List[int], value: int) -> int:
result = -1
for x in arg_list:
if x % 5 == 0:
result = x
break
return result
```
=> Break Statement

boa3/analyser/astoptimizer.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator.py, boa3/compiler/codegeneratorvisitor.py, boa3/model/operation/operator.py, boa3/neo/vm/TryCode.py, boa3_test/tests/test_exception.py
Implemented the `finally` body of `try` statements.
```python
def foo(bar: int) -> int:
try:
x: int = may_raise_exception(bar)
except Exception:
x = bar
finally:
x += bar
return x
```
=> Implement Try Finally

README.md
=> Boa-242 Include a suggestion note for resolving compiler errors in the README

boa3/builtin/interop/binary/__init__.py, boa3/model/builtin/interop/binary/base58decodemethod.py, boa3/model/builtin/interop/binary/base58encodemethod.py, boa3/model/builtin/interop/interop.py, boa3/neo/utils/__init__.py, boa3_test/test_sc/interop_test/Base58Decode.py, boa3_test/test_sc/interop_test/Base58DecodeMismatchedType.py, boa3_test/test_sc/interop_test/Base58Encode.py, boa3_test/test_sc/interop_test/Base58EncodeMismatchedType.py, boa3_test/tests/test_classes/testengine.py, boa3_test/tests/test_interop.py
Implemented Base58 encoding and decoding interops
```python
from boa3.builtin.interop.binary import base58_decode, base58_encode
@public
def encode(key: str) -> bytes:
return base58_encode(key)
@public
def decode(key: bytes) -> str:
return base58_decode(key)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/ee24711d0905144dbad60a65534cc4fa08a14e19/boa3_test/tests/test_interop.py#L589-L673
=> Implement Base58 Interop

boa3/model/builtin/interop/crypto/checkmultisigwithecdsasecp256k1method.py, boa3/model/builtin/interop/crypto/checkmultisigwithecdsasecp256r1method.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Bool.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Byte.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Int.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Str.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Bool.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Byte.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Int.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Str.py, boa3_test/test_sc/interop_test/Hash160Bool.py, boa3_test/test_sc/interop_test/Hash160Bytes.py, boa3_test/test_sc/interop_test/Hash160Int.py, boa3_test/test_sc/interop_test/Hash256Bool.py, boa3_test/test_sc/interop_test/Hash256Bytes.py, boa3_test/test_sc/interop_test/Hash256Int.py, boa3_test/test_sc/interop_test/Ripemd160Bool.py, boa3_test/test_sc/interop_test/Ripemd160Bytes.py, boa3_test/test_sc/interop_test/Ripemd160Int.py, boa3_test/test_sc/interop_test/Sha256Bool.py, boa3_test/test_sc/interop_test/Sha256Bytes.py, boa3_test/test_sc/interop_test/Sha256Int.py, boa3_test/tests/test_interop.py
#114 
Included more unit tests, such as Int, Bool and Bytes, to the crypto interops and used the test engine.
Go to boa3_test/tests/test_interop.py and run the tests
**Tests**
They were tested using the test engine.
**Platform:**
- Python version Python 3.7.9
=> Boa-267 Include more unit tests for crypto interops

boa3/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/updatemethod.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/UpdateContract.py, boa3_test/test_sc/interop_test/UpdateContractTooFewArguments.py, boa3_test/test_sc/interop_test/UpdateContractTooManyArguments.py, boa3_test/tests/test_interop.py
#114 
Implemented Update Contract Interop
Call update_contract
**Tests**
It was tested using Opcode only
**Platform:**
- Python version Python 3.7.9
=> Boa-190 Implement Update Contract Interop

boa3/builtin/interop/iterator/__init__.py, boa3/model/builtin/builtin.py, boa3/model/builtin/interop/binary/__init__.py, boa3/model/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/crypto/__init__.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/iterator/__init__.py, boa3/model/builtin/interop/iterator/iteratorinitmethod.py, boa3/model/builtin/interop/iterator/iteratortype.py, boa3/model/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/storage/__init__.py, boa3/model/type/collection/genericcollectiontype.py, boa3/model/type/type.py, boa3/neo/core/types/InteropInterface.py, boa3/neo/utils/__init__.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Bool.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Byte.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Int.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256k1Str.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Bool.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Byte.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Int.py, boa3_test/test_sc/interop_test/CheckMultisigWithECDsaSecp256r1Str.py, boa3_test/test_sc/interop_test/CreateContractTooManyArguments.py, boa3_test/test_sc/interop_test/IteratorCreateDict.py, boa3_test/test_sc/interop_test/IteratorCreateList.py, boa3_test/test_sc/interop_test/IteratorCreateMismatchedTypes.py, boa3_test/test_sc/interop_test/UpdateContract.py, boa3_test/tests/test_interop.py
Implemented the class ``Iterator`` with its constructor being the Neo interop ``Iterator.Create``
```python
from boa3.builtin.interop.iterator import Iterator
def list_iterator(x: list) -> Iterator:
return Iterator(x)
def dict_iterator(x: dict) -> Iterator:
return Iterator(x)
```
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/512f1f7c18f7d3bcd2b100bfe9fa68cc2db681a4/boa3_test/tests/test_interop.py#L1684-L1728
=> Boa-207 Implement Iterator Create Interop

README.md, docs/ContractExamplesTest.md
Change the README file to be easier to read.
=> Boa-233 Move README supported features table's examples to other markdown files

boa3/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/createmethod.py, boa3/model/builtin/interop/json/__init__.py, boa3_test/tests/boa_test.py, boa3_test/tests/test_class.py, boa3_test/tests/test_classes/testengine.py, boa3_test/tests/test_examples.py, boa3_test/tests/test_interop.py, boa3_test/tests/test_storage.py
Include unit tests for the examples
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/Boa-268/boa3_test/tests/test_examples.py
=> Boa-268 Add tests using the TestEngine to examples

boa3/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/blockchain/getcontractmethod.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/runtime/__init__.py, boa3_test/test_sc/interop_test/GetContract.py, boa3_test/tests/test_interop.py
#114 
Implemented GetContract Interop and organized interops.py dictionary in alphanumeric order.
Call get_contract
**Tests**
Tested it using the test engine and Opcode.
**Platform:**
=> Boa-148 Implement Interop GetContract

boa3/builtin/interop/runtime/__init__.py
**Platform:**
- Python version 3.7.6
=> Boa-272 Remove is_application_trigger()  and is_verification_trigger() and change trigger() description

boa3/builtin/interop/storage/__init__.py, boa3/builtin/interop/storage/storagecontext.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/storage/__init__.py, boa3/model/builtin/interop/storage/storagecontexttype.py, boa3/model/builtin/interop/storage/storagegetcontextmethod.py, boa3_test/test_sc/storage_test/StorageGetContext.py, boa3_test/tests/test_storage.py
#114 
Implemented GetContext Interop and StorageContextType
Call get_context()
**Tests**
Tested it with both Opcode and TestEngine, but I could not really test StorageContext contents
**Platform:**
=> Boa-79 Implement Get Current Storage Context

boa3/model/builtin/builtin.py, boa3/model/builtin/classmethod/toboolmethod.py, boa3/model/builtin/interop/storage/storagegetcontextmethod.py, boa3_test/test_sc/bytes_test/BytesToBool.py, boa3_test/test_sc/bytes_test/BytesToBoolWithBuiltin.py, boa3_test/test_sc/bytes_test/BytesToBoolWithBuiltinHardCodedFalse.py, boa3_test/test_sc/bytes_test/BytesToBoolWithBuiltinHardCodedTrue.py, boa3_test/test_sc/bytes_test/BytesToBoolWithBuiltinMismatchedTypes.py, boa3_test/tests/test_bytes.py
Call .to_bool()
**Tests**
Unit Tests inside test_bytes.py
**Platform:**
- Python version 3.7.6
=> Boa-289 Create .to_bool()

.bumpversion.cfg, CHANGELOG.md, README.md, boa3/__init__.py, docs/ContractExamplesTest.md
Updated CHANGELOG with the v0.6.0 changes
=> Update docs to v0.6.0

CHANGELOG.md, README.md, docs/ContractExamplesTest.md
Updated CHANGELOG and README with the v0.6.1 changes
=> Update docs to v0.6.1

.circleci/config.yml, boa3/constants.py, boa3/neo/smart_contract/notification.py
neo-project/neo-devpack-dotnet#396
neo-project/neo-devpack-dotnet#365
``neo-devpack-dotnet`` repository, which is where the TestEngine project is, was updated to use .Net 5.0, so the .Net version used for running the unit tests that use TestEngine must be updated to be compatible
=> Update CircleCI .Net to .Net 5

README.md
#194 
Added instructions on how to install, update, and use the TestEngine. Also fixed some anchors on the Table of Contents.
**Platform:**
=> Boa-278 Include in the README how to test using TestEngine

README.md, docs/source/index.rst, docs/source/install.rst, docs/source/testengine.rst
Added TestEngine instruction at neo3-boa docs and did some small corrections.
**Platform:**
- OS:  Windows 10 x64
- Python version:  Python 3.8
=> Boa-327 Include how to run the unit tests in the docs

boa3_test/tests/boa_test.py, boa3_test/tests/test_metadata.py
Fixed unit tests that were failing on #227 
**Platform:**
=> Boa-321 - Simplify how to get smart contract's path in the unit tests

boa3/analyser/astoptimizer.py, boa3/analyser/typeanalyser.py, boa3_test/tests/boa_test.py
There were some minor bugs that were blocking the port of [neo-boa](https://github.com/CityOfZion/neo-boa)'s unit tests for neo3-boa
**Platform:**
=> Small fixes for Boa-182

boa3/compiler/codegenerator.py, boa3_test/examples/test_native/example_contract_for_wrapped_neo.py, boa3_test/examples/test_native/methods.py, boa3_test/examples/wrapped_neo.py, boa3_test/tests/examples/test_wrapped_neo.py, boa3_test/tests/test_classes/testengine.py
Added a wrapped neo template.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/424b187e2abe1025272608627e1e82bcc90357a3/boa3_test/tests/examples/test_wrapped_neo.py
**Platform:**
=> Boa-316 Wrapped Neo

boa3/constants.py, boa3_test/tests/test_classes/nativetokenprefix.py, boa3_test/tests/test_interop/test_blockchain.py, boa3_test/tests/test_interop/test_contract.py
https://github.com/simplitech/neo-devpack-dotnet/issues/12
Updated the TestEngine interface in neo3-boa to be compatible with the current Neo version
**Platform:**
=> Update TestEngine's Neo version

boa3_test/examples/HTLC.py, boa3_test/examples/NEP17.py, boa3_test/examples/test_native/example_contract_for_htlc.py, boa3_test/examples/test_native/example_contract_for_wrapped_neo.py, boa3_test/examples/test_native/methods.py, boa3_test/examples/wrapped_neo.py, boa3_test/tests/examples/test_wrapped_neo.py
TestEngine was updated to use Neo3 preview5. Some small changes were made, so fixed them in neo-boa as well
=> Fixes for neo3-preview5

boa3/compiler/codegenerator/codegenerator.py, boa3/model/builtin/builtin.py, boa3/model/builtin/classmethod/__init__.py, boa3/model/builtin/classmethod/insertmethod.py, boa3/model/builtin/contract/__init__.py, boa3/model/builtin/method/__init__.py, boa3/model/builtin/method/builtinmethod.py, boa3_test/test_sc/list_test/InsertAnyValue.py, boa3_test/test_sc/list_test/InsertIntNegativeIndex.py, boa3_test/test_sc/list_test/InsertIntValue.py, boa3_test/test_sc/list_test/InsertIntWithBuiltin.py, boa3_test/tests/test_list.py
#242 
Implemented Python built-in `list` `insert` method
```python
from typing import List
@public
def Main() -> List[int]:
a = [1, 2, 3]
a.insert(2, 4)
return a  # expected [1, 2, 4, 3]
```
**Platform:**
=> Convert list insert method

CHANGELOG.md, README.md, docs/ContractExamplesTest.md
Updated CHANGELOG and README with the v0.7 changes
=> Update docs to v0.7

boa3_test/test_sc/variable_test/AnonymousVariable.py, boa3_test/tests/test_variable.py
#248 
Anonymous variables already worked, included unit tests to make sure it works with future changes.
```python
for _ in range(20):
do_something()
```
**Tests**
Included unit tests for validation
**Platform:**
=> Support to anonymous variables

boa3_test/tests/examples/test_NEP17.py
#365 
It was something that should have been done before, but the test engine limitations made it be postponed.
**Tests**
It was tested using the TestEngine.
**Platform:**
=> Finish implementing NEP-17 test #365

boa3_test/examples/NEP17.py, boa3_test/examples/amm.py, boa3_test/examples/nep5.py, boa3_test/examples/test_native/example_contract_for_wrapped_tokens.py, boa3_test/examples/wrapped_gas.py, boa3_test/tests/examples/test_amm.py, boa3_test/tests/examples/test_wrapped_neo.py
#309 
Created an AMM example.
The smart contract is located at [boa3_test/examples/amm.py](https://github.com/CityOfZion/neo3-boa/blob/96f184f68e16ef316b3fec541033018ac9f653bb/boa3_test/examples/amm.py)
**Tests**
Tested it at [boa3_test/tests/examples/test_amm.py](https://github.com/CityOfZion/neo3-boa/blob/96f184f68e16ef316b3fec541033018ac9f653bb/boa3_test/tests/examples/test_amm.py) using the TestEngine.
**Platform:**
**(Optional) Additional comments**
Also did some minor changes in other smart contracts.
=>  Create simple AMM example #309

CHANGELOG.md
Updated CHANGELOG and README with the v0.7.1 changes
=> update docs to v0.7.1

boa3/compiler/codegenerator/codegeneratorvisitor.py
#380 
Fixed debug info generation that wasn't including some lines that should be included
**Tests**
Run one smart contract from each [test_sc](https://github.com/CityOfZion/neo3-boa/tree/%23380/boa3_test/test_sc) folder using the [neo-debugger compatible with Neo N3 RC1](https://github.com/neo-project/neo-debugger/releases/tag/2.0.3)
**Platform:**
=> Fix debug info with assert statements

CHANGELOG.md, README.md, boa3/builtin/interop/__init__.py, boa3/model/builtin/method/__init__.py, boa3_test/examples/HTLC.py, boa3_test/tests/compiler_tests/test_arithmetic.py, boa3_test/tests/compiler_tests/test_interop/test_binary.py, boa3_test/tests/examples_tests/test_HTLC.py, boa3_test/tests/examples_tests/test_amm.py, boa3_test/tests/test_classes/transaction.py, docs/ContractExamplesTest.md, docs/source/code-reference.rst
#408
Updated CHANGELOG and README with the v0.8 changes
=> Update docs to v0.8

boa3/builtin/type/__init__.py, boa3/model/builtin/builtin.py, boa3/model/builtin/method/uint256method.py, boa3/model/type/collection/sequence/uint256type.py, boa3_test/test_sc/built_in_methods_test/IsInstanceUInt256.py, boa3_test/test_sc/neo_type_test/UInt256CallBytes.py, boa3_test/test_sc/neo_type_test/UInt256CallInt.py, boa3_test/test_sc/neo_type_test/UInt256CallMismatchedType.py, boa3_test/test_sc/neo_type_test/UInt256CallWithoutArgs.py, boa3_test/test_sc/neo_type_test/UInt256ConcatWithBytes.py, boa3_test/test_sc/neo_type_test/UInt256ReturnBytes.py, boa3_test/tests/compiler_tests/test_builtin_method.py, boa3_test/tests/compiler_tests/test_neo_types.py
#315 
Use `UInt256()`
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/121a0a9d068642760a8c5404eb5699e97f0b1572/boa3_test/tests/compiler_tests/test_neo_types.py#L105-L196
**Platform:**
=> Add support to UInt256 #315

boa3_test/examples/NEP17.py, boa3_test/examples/test_native/auxiliary_contract.py, boa3_test/examples/test_native/auxiliary_contract_2.py, boa3_test/examples/wrapped_gas.py, boa3_test/tests/examples_tests/test_HTLC.py, boa3_test/tests/examples_tests/test_NEP17.py, boa3_test/tests/examples_tests/test_amm.py, boa3_test/tests/examples_tests/test_nep5.py, boa3_test/tests/examples_tests/test_wrapped_neo.py
#416
Some tests were not working after an update, so they were fixed.
**Tests**
They were tested using the TestEngine.
**Platform:**
=> Change the examples unit tests #416

CHANGELOG.md, README.md, docs/ContractExamplesTest.md, docs/source/code-reference.rst, docs/source/getting-started.rst
#434
Updated CHANGELOG and README with the v0.8.1 changes
=> Update docs to v0.8.1

boa3/builtin/interop/blockchain/__init__.py, boa3/builtin/interop/blockchain/transaction.py, boa3/model/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/blockchain/transactiontype.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/blockchain/Transaction.py, boa3_test/test_sc/interop_test/runtime/ScriptContainerAsTransaction.py, boa3_test/tests/compiler_tests/test_interop/test_blockchain.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py
#439 
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7ef20e6f690af49bf2a2520f0fa7b6cda5ed7ea8/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L106-L127
**Platform:**
Also added a test to cast a script container into a Transaction.
https://github.com/CityOfZion/neo3-boa/blob/7ef20e6f690af49bf2a2520f0fa7b6cda5ed7ea8/boa3_test/test_sc/interop_test/runtime/ScriptContainerAsTransaction.py#L8-L10
https://github.com/CityOfZion/neo3-boa/blob/7ef20e6f690af49bf2a2520f0fa7b6cda5ed7ea8/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L601-L620
=>  Implement Transaction Type

boa3/analyser/astanalyser.py, boa3/analyser/builtinfunctioncallanalyser.py, boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/model/imports/builtin.py, boa3_test/test_sc/import_test/ImportInteropWithAlias.py, boa3_test/tests/compiler_tests/test_import.py
#474
Fixed bug when importing packages and setting an alias to them
https://github.com/CityOfZion/neo3-boa/blob/5ab430d2afbde77bf2815ab2f9f869a51b225c93/boa3_test/test_sc/import_test/ImportInteropWithAlias.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/5ab430d2afbde77bf2815ab2f9f869a51b225c93/boa3_test/tests/compiler_tests/test_import.py#L98-L104
**Platform:**
=> Fixed import with alias

CHANGELOG.md, README.md, boa3/builtin/contract/__init__.py, boa3/builtin/interop/contract/__init__.py, docs/ContractExamplesTest.md, docs/source/boa3/boa3.rst, docs/source/code-reference.rst, docs/source/getting-started.rst, docs/source/package-reference.rst
#475
Updated CHANGELOG, README, and the docs with the v0.8.2 changes
=> Update docs to v0.8.2

boa3/model/builtin/builtin.py, boa3/model/builtin/method/__init__.py, boa3/model/builtin/method/reversedmethod.py, boa3/model/type/collection/sequence/reversedtype.py, boa3/model/type/type.py, boa3/neo/vm/opcode/Opcode.py, boa3_test/test_sc/reversed_test/ReversedBytes.py, boa3_test/test_sc/reversed_test/ReversedList.py, boa3_test/test_sc/reversed_test/ReversedListBool.py, boa3_test/test_sc/reversed_test/ReversedListBytes.py, boa3_test/test_sc/reversed_test/ReversedListInt.py, boa3_test/test_sc/reversed_test/ReversedListStr.py, boa3_test/test_sc/reversed_test/ReversedParameterMismatchedType.py, boa3_test/test_sc/reversed_test/ReversedRange.py, boa3_test/test_sc/reversed_test/ReversedString.py, boa3_test/test_sc/reversed_test/ReversedTuple.py, boa3_test/tests/compiler_tests/test_reversed.py
#243 
Added the `reversed` class and method. It was implemented as a sequence instead of an Iterator.
Use `reversed()` with a Sequence as a parameter.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/389c4219b2cf12f045832f380f9452d6529e4fa2/boa3_test/tests/compiler_tests/test_reversed.py
**Platform:**
=> Convert builtin 'reversed'

boa3_test/examples/test_native/update_contract.py, boa3_test/examples/update_contract.py, boa3_test/tests/examples_tests/test_update_contract.py
#330 
Added an example using the `update_contract` built-in method.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d956b03a7f58529f78d52617bd4196215cf08477/boa3_test/tests/examples_tests/test_update_contract.py
**Platform:**
=> Contract update example

boa3/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/blockchain/__init__.py, boa3/model/builtin/interop/blockchain/currenthashmethod.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/blockchain/CurrentHash.py, boa3_test/tests/compiler_tests/test_interop/test_blockchain.py
#494 
Call `current_hash`.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fac3e18dcda68109cd2df454942f0c8834cfce0a/boa3_test/tests/compiler_tests/test_interop/test_blockchain.py#L395-L408
**Platform:**
=> Implement LedgerContract currentHash

boa3/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/getminimumdeploymentfeemethod.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/contract/GetMinimumDeploymentFee.py, boa3_test/test_sc/interop_test/contract/GetMinimumDeploymentFeeTooManyArguments.py, boa3_test/tests/compiler_tests/test_interop/test_contract.py
#493 
https://github.com/CityOfZion/neo3-boa/blob/74bd9a11b163bd9dc77d7855045001552cbea0d2/boa3_test/test_sc/interop_test/contract/GetMinimumDeploymentFee.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/74bd9a11b163bd9dc77d7855045001552cbea0d2/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L429-L439
**Platform:**
=> Implement ContractManagement getMinimumDeploymentFee

boa3/analyser/typeanalyser.py, boa3/builtin/interop/role/__init__.py, boa3/compiler/codegenerator/codegenerator.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3/neo3/contracts/native/__init__.py, boa3/neo3/contracts/native/nativetypes.py, boa3_test/test_sc/exception_test/TryExceptElse.py, boa3_test/test_sc/exception_test/TryExceptElseFinally.py, boa3_test/test_sc/interop_test/role/GetDesignatedByRole.py, boa3_test/tests/compiler_tests/test_boa_builtin_method.py, boa3_test/tests/compiler_tests/test_exception.py
#249
Implemented `else` branch of `try` statements
https://github.com/CityOfZion/neo3-boa/blob/d9af2f0a5cb36a9bfc3df6233e93a2ec7d5a6f26/boa3_test/test_sc/exception_test/TryExceptElseFinally.py#L7-L14
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d9af2f0a5cb36a9bfc3df6233e93a2ec7d5a6f26/boa3_test/tests/compiler_tests/test_exception.py#L333-L416
**Platform:**
=> Implement Try Else

boa3/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/__init__.py, boa3/model/builtin/interop/contract/createmultisigaccountmethod.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/contract/CreateMultisigAccount.py, boa3_test/test_sc/interop_test/contract/CreateMultisigAccountTooFewArguments.py, boa3_test/test_sc/interop_test/contract/CreateMultisigAccountTooManyArguments.py, boa3_test/test_sc/interop_test/contract/CreateStandardAccount.py, boa3_test/test_sc/interop_test/contract/CreateStandardAccountTooFewArguments.py, boa3_test/test_sc/interop_test/contract/CreateStandardAccountTooManyArguments.py, boa3_test/tests/compiler_tests/test_interop/test_contract.py
#490 
https://github.com/CityOfZion/neo3-boa/blob/8be7c1ed02326e7a4dd20952e2b5ec4baae4bfcc/boa3_test/test_sc/interop_test/contract/CreateMultisigAccount.py#L1-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/8be7c1ed02326e7a4dd20952e2b5ec4baae4bfcc/boa3_test/tests/compiler_tests/test_interop/test_contract.py#L449-L469
**Platform:**
Also changed a test from CreateStandardAccount.py and added some tests that should fail for it.
=> Implement Contract CreateMultisigAccount Interop

boa3/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/runtime/getrandommethod.py, boa3_test/test_sc/interop_test/runtime/GetRandom.py, boa3_test/test_sc/interop_test/runtime/GetRandomTooManyArguments.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py
#546 
https://github.com/CityOfZion/neo3-boa/blob/12c61d204bc6e807f85d4c720b85cbb67f6e7e70/boa3_test/test_sc/interop_test/runtime/GetRandom.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/12c61d204bc6e807f85d4c720b85cbb67f6e7e70/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L635-L644
**Platform:**
=> Implement Runtime GetRandom Interop

boa3/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/runtime/getnetworkmethod.py, boa3_test/test_sc/interop_test/runtime/GetNetwork.py, boa3_test/test_sc/interop_test/runtime/GetNetworkTooManyArguments.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py
#544 
https://github.com/CityOfZion/neo3-boa/blob/4b16cc8cee3d87c4114cb46b47bcaa4ff322a2f9/boa3_test/test_sc/interop_test/runtime/GetNetwork.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4b16cc8cee3d87c4114cb46b47bcaa4ff322a2f9/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L621-L630
**Platform:**
I'm creating this as a draft first, because without #547 3 tests will break.
=> Implement Runtime GetNetwork Interop

boa3/builtin/interop/binary/__init__.py, boa3/model/builtin/interop/binary/__init__.py, boa3/model/builtin/interop/binary/memorysearchmethod.py, boa3/model/builtin/interop/interop.py, boa3_test/test_sc/interop_test/binary/MemorySearch.py, boa3_test/test_sc/interop_test/binary/MemorySearchDefault.py, boa3_test/test_sc/interop_test/binary/MemorySearchMismatchedType.py, boa3_test/test_sc/interop_test/binary/MemorySearchStart.py, boa3_test/test_sc/interop_test/binary/MemorySearchTooFewArguments.py, boa3_test/test_sc/interop_test/binary/MemorySearchTooManyArguments.py, boa3_test/tests/compiler_tests/test_interop/test_binary.py
#500 
https://github.com/CityOfZion/neo3-boa/blob/3ca94a675ae1a133021dbd2fd42d068a01f67c60/boa3_test/test_sc/interop_test/binary/MemorySearch.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3ca94a675ae1a133021dbd2fd42d068a01f67c60/boa3_test/tests/compiler_tests/test_interop/test_binary.py#L428-L556
**Platform:**
=> Implement StdLib memorySearch

CHANGELOG.md, README.md, docs/ContractExamplesTest.md, docs/source/code-reference.rst
#566
Updated CHANGELOG, README, and the docs with the v0.8.3 changes
=> Update docs to v0.8.3

boa3/model/builtin/builtin.py, boa3/model/builtin/classmethod/__init__.py, boa3/model/builtin/classmethod/countmethod.py, boa3/model/builtin/classmethod/countsequencemethod.py, boa3/model/builtin/classmethod/countstrmethod.py, boa3_test/test_sc/built_in_methods_test/CountSequenceTooFewArguments.py, boa3_test/test_sc/built_in_methods_test/CountSequenceTooManyArguments.py, boa3_test/test_sc/built_in_methods_test/CountStr.py, boa3_test/test_sc/built_in_methods_test/CountStrDefault.py, boa3_test/test_sc/built_in_methods_test/CountStrEndDefault.py, boa3_test/test_sc/built_in_methods_test/CountStrTooFewArguments.py, boa3_test/test_sc/built_in_methods_test/CountStrTooManyArguments.py, boa3_test/tests/compiler_tests/test_builtin_method.py
#537
Split the logic of CountMethod into 2 (CountSequenceMethod and CountStrMethod).
https://github.com/CityOfZion/neo3-boa/blob/c1ec185d55c492df2be20073489d6798dd94e6ef/boa3_test/test_sc/built_in_methods_test/CountStr.py#L1-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c1ec185d55c492df2be20073489d6798dd94e6ef/boa3_test/tests/compiler_tests/test_builtin_method.py#L1130-L1260
**Platform:**
-
=> Implement str count

boa3/model/builtin/method/strsplitmethod.py, boa3_test/test_sc/built_in_methods_test/StrSplit.py, boa3_test/test_sc/built_in_methods_test/StrSplitMaxsplitDefault.py, boa3_test/tests/compiler_tests/test_builtin_method.py
#515 
https://github.com/CityOfZion/neo3-boa/blob/fa321921e5255729d078785bdc897fce0d91e1ba/boa3_test/test_sc/built_in_methods_test/StrSplit.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fa321921e5255729d078785bdc897fce0d91e1ba/boa3_test/tests/compiler_tests/test_builtin_method.py#L987-L1017
**Platform:**
=> Implement maxsplit parameter on the str split method

.circleci/config.yml, CHANGELOG.md, README.md
#583
Updated CHANGELOG, README, and the docs with the v0.9 changes
=> Update docs to v0.9

boa3/analyser/moduleanalyser.py, boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator/codegenerator.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3/constants.py, boa3/model/method.py, boa3/model/type/classes/classinitmethoddefault.py, boa3/model/type/classes/classtype.py, boa3/model/type/classes/userclass.py, boa3_test/test_sc/class_test/UserClassWithInitWithArgs.py, boa3_test/tests/compiler_tests/test_builtin_method.py, boa3_test/tests/compiler_tests/test_class.py, boa3_test/tests/compiler_tests/test_import.py, boa3_test/tests/compiler_tests/test_interop/test_crypto.py, boa3_test/tests/compiler_tests/test_interop/test_iterator.py, boa3_test/tests/compiler_tests/test_interop/test_oracle.py, boa3_test/tests/compiler_tests/test_interop/test_storage.py
#554
Implemented support to object instantiation for user-created classes.
https://github.com/CityOfZion/neo3-boa/blob/4b30f9ab620d5325a416d8ac9bb5e6f7bd6c328a/boa3_test/test_sc/class_test/UserClassWithInit.py#L4-L11
https://github.com/CityOfZion/neo3-boa/blob/4b30f9ab620d5325a416d8ac9bb5e6f7bd6c328a/boa3_test/test_sc/class_test/UserClassWithInitWithArgs.py#L4-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4b30f9ab620d5325a416d8ac9bb5e6f7bd6c328a/boa3_test/tests/compiler_tests/test_class.py#L199-L211
https://github.com/CityOfZion/neo3-boa/blob/4b30f9ab620d5325a416d8ac9bb5e6f7bd6c328a/boa3_test/tests/compiler_tests/test_class.py#L114-L116
https://github.com/CityOfZion/neo3-boa/blob/4b30f9ab620d5325a416d8ac …
=> Implement class instantiation

boa3/analyser/moduleanalyser.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3/model/builtin/builtin.py, boa3/model/builtin/decorator/__init__.py, boa3/model/builtin/decorator/instancemethoddecorator.py, boa3/model/type/classes/classinitmethoddefault.py, boa3_test/tests/compiler_tests/test_class.py, boa3_test/tests/compiler_tests/test_function.py
#556
Implemented instance methods definitions.
https://github.com/CityOfZion/neo3-boa/blob/74631e0cd83d99d100d5ceb8089c47a77d14727c/boa3_test/test_sc/class_test/UserClassWithInstanceMethod.py#L4-L11
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/74631e0cd83d99d100d5ceb8089c47a77d14727c/boa3_test/tests/compiler_tests/test_class.py#L213-L219
**Platform:**
=> Implement class with instance methods

boa3/builtin/nativecontract/policy.py, boa3/model/builtin/native/nativecontract.py, boa3/model/builtin/native/policyclass.py, boa3/model/imports/builtin.py, boa3_test/test_sc/native_test/policy/GetExecFeeFactor.py, boa3_test/test_sc/native_test/policy/GetExecFeeFactorTooManyArguments.py, boa3_test/test_sc/native_test/policy/GetFeePerByte.py, boa3_test/test_sc/native_test/policy/GetFeePerByteTooManyArguments.py, boa3_test/test_sc/native_test/policy/GetStoragePrice.py, boa3_test/test_sc/native_test/policy/GetStoragePriceTooManyArguments.py, boa3_test/test_sc/native_test/policy/IsBlocked.py, boa3_test/test_sc/native_test/policy/IsBlockedMismatchedTypeBool.py, boa3_test/test_sc/native_test/policy/IsBlockedMismatchedTypeInt.py, boa3_test/test_sc/native_test/policy/IsBlockedMismatchedTypeStr.py, boa3_test/test_sc/native_test/policy/IsBlockedTooFewArguments.py, boa3_test/test_sc/native_test/policy/IsBlockedTooManyArguments.py, boa3_test/tests/compiler_tests/test_native/test_policy.py
#599
Implemented an interface for interacting with the Policy native contract in a clearer way.
https://github.com/CityOfZion/neo3-boa/blob/c6f3f1ffa0eb9748c46cf2d3da73f96fa70cb4f9/boa3/builtin/nativecontract/policy.py#L4-L47
https://github.com/CityOfZion/neo3-boa/blob/c6f3f1ffa0eb9748c46cf2d3da73f96fa70cb4f9/boa3_test/test_sc/native_test/policy/GetStoragePrice.py#L2-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c6f3f1ffa0eb9748c46cf2d3da73f96fa70cb4f9/boa3_test/tests/compiler_tests/test_native/test_policy.py#L10-L66
**Platform:**
=> Implement interface for Policy native contract

boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator/codegenerator.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3_test/test_sc/bytes_test/SliceOmittedWithNegativeStride.py, boa3_test/test_sc/bytes_test/SliceOmittedWithStride.py, boa3_test/test_sc/bytes_test/SliceWithNegativeStride.py, boa3_test/test_sc/bytes_test/SliceWithStride.py, boa3_test/test_sc/list_test/ListSlicingOmittedWithNegativeStride.py, boa3_test/test_sc/list_test/ListSlicingOmittedWithStride.py, boa3_test/test_sc/list_test/ListSlicingWithNegativeStride.py, boa3_test/test_sc/range_test/RangeSlicingOmittedWithNegativeStride.py, boa3_test/test_sc/range_test/RangeSlicingOmittedWithStride.py, boa3_test/test_sc/range_test/RangeSlicingWithNegativeStride.py, boa3_test/test_sc/string_test/StringSlicingOmittedWithNegativeStride.py, boa3_test/test_sc/string_test/StringSlicingWithNegativeStride.py, boa3_test/test_sc/string_test/StringSlicingWithStride.py, boa3_test/test_sc/tuple_test/TupleSlicingOmittedWithNegativeStride.py, boa3_test/test_sc/tuple_test/TupleSlicingOmittedWithStride.py, boa3_test/test_sc/tuple_test/TupleSlicingWithNegativeStride.py, boa3_test/tests/compiler_tests/test_bytes.py, boa3_test/tests/compiler_tests/test_list.py, boa3_test/tests/compiler_tests/test_range.py, boa3_test/tests/compiler_tests/test_string.py, boa3_test/tests/compiler_tests/test_tuple.py
#240 
https://github.com/CityOfZion/neo3-boa/blob/d68f6f632ce85f0c7e0fbd48f7224e0e7b1fd9f0/boa3_test/test_sc/list_test/ListSlicingOmittedWithStride.py
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d68f6f632ce85f0c7e0fbd48f7224e0e7b1fd9f0/boa3_test/tests/compiler_tests/test_list.py#L593-L630
**Platform:**
Using a stride with start and end was not implemented, the logic will be implemented on #594.
=> Sequence slicing with stride

boa3/builtin/nativecontract/ledger.py, boa3/model/builtin/native/__init__.py, boa3/model/builtin/native/ledgerclass.py, boa3/model/builtin/native/nativecontract.py, boa3_test/test_sc/interop_test/blockchain/GetTransactionFromBlockMismatchedType.py, boa3_test/test_sc/interop_test/blockchain/GetTransactionHeightMismatchedType.py, boa3_test/test_sc/interop_test/blockchain/GetTransactionMismatchedType.py, boa3_test/test_sc/native_test/ledger/GetBlockByHash.py, boa3_test/test_sc/native_test/ledger/GetBlockByIndex.py, boa3_test/test_sc/native_test/ledger/GetBlockMismatchedTypes.py, boa3_test/test_sc/native_test/ledger/GetTransaction.py, boa3_test/test_sc/native_test/ledger/GetTransactionFromBlockInt.py, boa3_test/test_sc/native_test/ledger/GetTransactionFromBlockMismatchedType.py, boa3_test/test_sc/native_test/ledger/GetTransactionFromBlockUInt256.py, boa3_test/test_sc/native_test/ledger/GetTransactionHeight.py, boa3_test/test_sc/native_test/ledger/GetTransactionHeightMismatchedType.py, boa3_test/test_sc/native_test/ledger/GetTransactionMismatchedType.py, boa3_test/tests/compiler_tests/test_native/test_ledger.py
#601 
Implemented an interface for interacting with the Ledger native contract in a clearer way.
https://github.com/CityOfZion/neo3-boa/blob/1211aff158f5ee3cce3b07bf8dc4a9a2799b4f4d/boa3/builtin/nativecontract/ledger.py#L7-L57
https://github.com/CityOfZion/neo3-boa/blob/ce40449a080ec86ea8a11e6aad87106fd3bdd651/boa3_test/test_sc/native_test/ledger/GetBlockByHash.py#L7-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1211aff158f5ee3cce3b07bf8dc4a9a2799b4f4d/boa3_test/tests/compiler_tests/test_native/test_ledger.py#L14-L287
**Platform:**
Also added more CompilerError tests to `interop/blockchain`.
=> Implement interface for Ledger native contract

boa3/builtin/nativecontract/neo.py, boa3/model/builtin/native/__init__.py, boa3/model/builtin/native/nativecontract.py, boa3/model/builtin/native/neoclass.py, boa3_test/test_sc/native_test/neo/BalanceOf.py, boa3_test/test_sc/native_test/neo/BalanceOfTooManyArguments.py, boa3_test/test_sc/native_test/neo/Decimals.py, boa3_test/test_sc/native_test/neo/DecimalsTooManyArguments.py, boa3_test/test_sc/native_test/neo/Symbol.py, boa3_test/test_sc/native_test/neo/SymbolTooManyArguments.py, boa3_test/test_sc/native_test/neo/TotalSupply.py, boa3_test/test_sc/native_test/neo/TotalSupplyTooManyArguments.py, boa3_test/test_sc/native_test/neo/Transfer.py, boa3_test/test_sc/native_test/neo/TransferDataDefault.py, boa3_test/test_sc/native_test/neo/TransferTooFewArguments.py, boa3_test/test_sc/native_test/neo/TransferTooManyArguments.py, boa3_test/tests/compiler_tests/test_native/test_neo.py
#610
Implemented an interface for interacting with the NEP-17 methods in the NEO native contract in a clearer way.
https://github.com/CityOfZion/neo3-boa/blob/7b5376839242adffce9b9ff55ee8ca56eb261fc4/boa3/builtin/nativecontract/neo.py#L1-L74
https://github.com/CityOfZion/neo3-boa/blob/7b5376839242adffce9b9ff55ee8ca56eb261fc4/boa3_test/test_sc/native_test/neo/Symbol.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/7b5376839242adffce9b9ff55ee8ca56eb261fc4/boa3_test/tests/compiler_tests/test_native/test_neo.py#L1-L100
**Platform:**
Other methods will be implemented in #622.
=> Implement initial interface for NEO native contract

boa3/builtin/nativecontract/rolemanagement.py, boa3/compiler/codegenerator/codegenerator.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3/compiler/codegenerator/generatordata.py, boa3/model/builtin/native/nep17_methods/decimalsmethod.py, boa3/model/operation/operation.py, boa3/neo3/contracts/namedcurve.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsa.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Bool.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Bytes.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Int.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1MismatchedType.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256k1Str.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Bool.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Bytes.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Int.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1MismatchedType.py, boa3_test/test_sc/interop_test/crypto/VerifyWithECDsaSecp256r1Str.py, boa3_test/test_sc/native_test/cryptolib/VerifyWithECDsaSecp256r1MismatchedType.py, boa3_test/test_sc/native_test/stdlib/SerializationBoa2Test.py, boa3_test/tests/compiler_tests/test_native/test_contract_management.py, boa3_test/tests/compiler_tests/test_native/test_gas.py, boa3_test/tests/compiler_tests/test_range.py
#598
Refactored CodeGeneratorVisitor so all `visit` methods return the same data type.
**Tests**
Rerun all existing unit tests
**Platform:**
=> Refactor visit_Attribute to clarify code

.circleci/config.yml, CHANGELOG.md, README.md, boa3_test/tests/compiler_tests/test_bytes.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py, boa3_test/tests/compiler_tests/test_string.py
#639
Updated CHANGELOG, README, and the docs with the v0.10 changes
=> Prepare release v.0.10

boa3/model/builtin/builtin.py, boa3/model/builtin/classmethod/__init__.py, boa3/model/builtin/classmethod/copymethod.py, boa3_test/test_sc/list_test/Copy.py, boa3_test/test_sc/list_test/CopyBool.py, boa3_test/test_sc/list_test/CopyBuiltinCall.py, boa3_test/test_sc/list_test/CopyBytes.py, boa3_test/test_sc/list_test/CopyInt.py, boa3_test/test_sc/list_test/CopyStr.py, boa3_test/tests/compiler_tests/test_list.py
#257 
Implemented the copy() function from the List class.
https://github.com/CityOfZion/neo3-boa/blob/52ac3b749b7259e1b8e08c9e11f54ac73d0594cc/boa3_test/test_sc/list_test/Copy.py#L5-L7
or
https://github.com/CityOfZion/neo3-boa/blob/52ac3b749b7259e1b8e08c9e11f54ac73d0594cc/boa3_test/test_sc/list_test/CopyBuiltinCall.py#L6-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/52ac3b749b7259e1b8e08c9e11f54ac73d0594cc/boa3_test/tests/compiler_tests/test_list.py#L1177-L1241
**Platform:**
=> Implement List copy method

boa3/analyser/moduleanalyser.py, boa3/compiler/codegenerator/codegenerator.py, boa3/model/builtin/builtin.py, boa3/model/builtin/method/__init__.py, boa3/model/builtin/method/supermethod.py, boa3/model/operation/binary/relational/__init__.py, boa3/model/type/classes/classinitmethoddefault.py, boa3/model/type/classes/classtype.py, boa3/model/type/classes/contractinterfaceclass.py, boa3/model/type/classes/userclass.py, boa3_test/test_sc/class_test/UserClassWithBase.py, boa3_test/test_sc/class_test/UserClassWithBuiltinBase.py, boa3_test/test_sc/class_test/UserClassWithCreatedBase.py, boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithArgs.py, boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithInit.py, boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithVariables.py, boa3_test/test_sc/class_test/UserClassWithMultipleBases.py, boa3_test/tests/compiler_tests/test_class.py
#713
Initial implementation of class inheritance. Implemented single class inheritance and is possible to use inherited methods and variables.
Didn't implement inheritance using Python types (#714). Multiple inheritances and using `super()` calls are not supported yet
https://github.com/CityOfZion/neo3-boa/blob/ee8c0a4d20334381dd8a4c5fbccf2d9e8c06058f/boa3_test/test_sc/class_test/UserClassWithCreatedBaseWithVariables.py#L4-L22
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/ee8c0a4d20334381dd8a4c5fbccf2d9e8c06058f/boa3_test/tests/compiler_tests/test_class.py#L290-L357
**Platform:**
=> Implement inheritance for user created classes

boa3/analyser/moduleanalyser.py, boa3/compiler/codegenerator/codegenerator.py, boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3_test/test_sc/variable_test/ListGlobalAssignment.py, boa3_test/tests/compiler_tests/test_variable.py
#737
Fixed issue that caused runtime error when accessing global variables inside class methods
https://github.com/CityOfZion/neo3-boa/blob/be1f50951847660aa4f2925701b72163ef3cf3dd/boa3_test/test_sc/variable_test/ListGlobalAssignment.py#L5-L26
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/be1f50951847660aa4f2925701b72163ef3cf3dd/boa3_test/tests/compiler_tests/test_variable.py#L539-L548
**Platform:**
=> user defined class methods error without assignment

.circleci/config.yml, README.md, boa3/neo/vm/opcode/Opcode.py, boa3/neo/vm/opcode/OpcodeInfo.py, boa3_test/tests/compiler_tests/test_interop/test_iterator.py, boa3_test/tests/compiler_tests/test_interop/test_storage.py, docs/source/getting-started.rst
#738
Updated with Neo 3.1 new opcodes and updated test engine
**Platform:**
=> Support to Neo 3.1

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, boa3/builtin/__init__.py, boa3/builtin/interop/blockchain/__init__.py, boa3/builtin/nativecontract/contractmanagement.py, boa3/builtin/nativecontract/policy.py, boa3/model/builtin/interop/blockchain/__init__.py, boa3_test/examples/README.md, boa3_test/tests/compiler_tests/test_relational.py, docs/ContractExamplesTest.md, docs/source/boa3/builtin/boa3-builtins.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-contractmanagement.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-cryptolib.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-gas.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-ledger.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-neo.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-policy.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-rolemanagement.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract-stdlib.rst, docs/source/boa3/builtin/nativecontract/boa3-builtin-nativecontract.rst, docs/source/code-reference.rst
#752
Updated CHANGELOG, README, and the docs with the v0.10.1 changes
=> Prepare release v0.10.1

boa3/model/builtin/builtin.py, boa3/model/builtin/method/__init__.py, boa3/model/builtin/method/boolmethod.py, boa3/model/type/primitive/booltype.py, boa3_test/test_sc/built_in_methods_test/Bool.py, boa3_test/test_sc/built_in_methods_test/BoolBytes.py, boa3_test/test_sc/built_in_methods_test/BoolClass.py, boa3_test/test_sc/built_in_methods_test/BoolDict.py, boa3_test/test_sc/built_in_methods_test/BoolInt.py, boa3_test/test_sc/built_in_methods_test/BoolList.py, boa3_test/test_sc/built_in_methods_test/BoolRange.py, boa3_test/test_sc/built_in_methods_test/BoolStr.py, boa3_test/tests/compiler_tests/test_builtin_method.py
#678 
Added support to bool constructor
https://github.com/CityOfZion/neo3-boa/blob/9a2921fe1a23a1a087220ed14a5c1954ac488c20/boa3_test/test_sc/built_in_methods_test/Bool.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/9a2921fe1a23a1a087220ed14a5c1954ac488c20/boa3_test/tests/compiler_tests/test_builtin_method.py#L1623-L1734
**Platform:**
=> Add support to bool constructor

boa3/analyser/typeanalyser.py, boa3/compiler/codegenerator/codegenerator.py, boa3/model/builtin/method/boolmethod.py, boa3/model/builtin/method/intbytestringmethod.py, boa3/model/builtin/method/intmethod.py, boa3_test/test_sc/native_test/gas/ImportWithAlias.py, boa3_test/tests/compiler_tests/test_native/test_gas.py
#766
Fixed issue related to importing classes with aliases and accessing their class methods.
https://github.com/CityOfZion/neo3-boa/blob/3eb4de9f2b1d8dc2f93b9ffa0ccb3e64d65beb6f/boa3_test/test_sc/native_test/gas/ImportWithAlias.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3eb4de9f2b1d8dc2f93b9ffa0ccb3e64d65beb6f/boa3_test/tests/compiler_tests/test_native/test_gas.py#L101-L106
**Platform:**
=> Importing a class and changing the alias is not running properly

boa3_test/examples/README.md, boa3_test/examples/amm.py, boa3_test/examples/auxiliary_contracts/auxiliary_contract.py, boa3_test/examples/auxiliary_contracts/auxiliary_contract_2.py, boa3_test/examples/auxiliary_contracts/update_contract.py, boa3_test/examples/hello_world.py, boa3_test/examples/htlc.py, boa3_test/examples/ico.py, boa3_test/examples/nep17.py, boa3_test/examples/nep5.py, boa3_test/examples/update_contract.py, boa3_test/examples/wrapped_gas.py, boa3_test/examples/wrapped_neo.py, boa3_test/test_sc/contract_interface_test/Nep17Interface.py, boa3_test/tests/boa_test.py, boa3_test/tests/examples_tests/test_amm.py, boa3_test/tests/examples_tests/test_htlc.py, boa3_test/tests/examples_tests/test_ico.py, boa3_test/tests/examples_tests/test_nep17.py, boa3_test/tests/examples_tests/test_nep5.py, boa3_test/tests/examples_tests/test_update_contract.py, boa3_test/tests/examples_tests/test_wrapped_neo.py, docs/source/tutorials.rst
#795 
Refactored the example contracts to use all the features already supported by boa
**Tests**
Rerun all the examples tests
=> Update examples with latest boa features

requirements.txt, requirements_dev.txt, setup.py
#804
Removed unused requirements from [requirements.txt](https://github.com/CityOfZion/neo3-boa/blob/%23804/requirements.txt) and [requirements_dev.txt](https://github.com/CityOfZion/neo3-boa/blob/%23804/requirements_dev.txt).
=> Remove unused dependencies from requirements

CHANGELOG.md, README.md, docs/ContractExamplesTest.md, docs/source/code-reference.rst
#810
Updated CHANGELOG, README, and the docs with the v0.11.0 changes
=> Update docs to v0.11.0

README.rst, setup.cfg
#825
Updated [README.rst](https://github.com/CityOfZion/neo3-boa/blob/%23825/README.rst) with the same basic information that is on [README.md](https://github.com/CityOfZion/neo3-boa/blob/%23825/README.md)
=> Update README.rst #825

README.md, docs/source/getting-started.rst
Added instructions on how to generate the nefdbnfo file.
=> Docs don't mention need for --debug flag

README.md
Added a warning on the README.
**Platform:**
=> Before fixing the Python 3.10 bug, let's change the readme telling about the issue

boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandards.py, boa3_test/tests/compiler_tests/test_metadata.py, boa3_test/tests/test_classes/contract/neomanifeststruct.py
It was already there, added a test using NeoManifestStruct.
https://github.com/CityOfZion/neo3-boa/blob/c9e64e0e7a67ccb52407f16ae08e8ff47a8f43aa/boa3_test/test_sc/metadata_test/MetadataInfoSupportedStandards.py#L15-L19
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c9e64e0e7a67ccb52407f16ae08e8ff47a8f43aa/boa3_test/tests/compiler_tests/test_metadata.py#L161-L185
**Platform:**
=> Implement Supported Standards to the test classes

boa3/neo/vm/opcode/Opcode.py, boa3/neo/vm/opcode/OpcodeInfo.py
Added 2 opcodes.
**Platform:**
=> Include new Neo VM opcodes

boa3/model/builtin/interop/runtime/getnotificationsmethod.py, boa3_test/test_sc/interop_test/runtime/GetNotifications.py, boa3_test/tests/compiler_tests/test_import.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py
Changed the method arg and the default value
https://github.com/CityOfZion/neo3-boa/blob/fc773d29aa2d4eedf7dc019efc7f71e6337b4036/boa3_test/test_sc/interop_test/runtime/GetNotifications.py#L1-L22
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fc773d29aa2d4eedf7dc019efc7f71e6337b4036/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L427-L469
**Platform:**
=> Change getnotificationsmethod opcode

boa3/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/interop.py, boa3/model/builtin/interop/runtime/__init__.py, boa3/model/builtin/interop/runtime/getaddressversionmethod.py, boa3_test/test_sc/interop_test/runtime/AddressVersion.py, boa3_test/test_sc/interop_test/runtime/AddressVersionCantAssign.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py
Added the address_version property
https://github.com/CityOfZion/neo3-boa/blob/85122abed851f38797b9220e76f17099bcfc7f0c/boa3_test/test_sc/interop_test/runtime/AddressVersion.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/85122abed851f38797b9220e76f17099bcfc7f0c/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L647-L656
**Platform:**
=> Implement GetAddressVersion interop

boa3/builtin/nativecontract/neo.py, boa3/model/builtin/native/neo_contract_methods/__init__.py, boa3/model/builtin/native/neo_contract_methods/unvote.py, boa3/model/builtin/native/neoclass.py, boa3_test/test_sc/native_test/neo/UnVoteTooFewArguments.py, boa3_test/test_sc/native_test/neo/UnVoteTooManyArguments.py, boa3_test/test_sc/native_test/neo/Vote.py, boa3_test/tests/compiler_tests/test_native/test_neo.py
Added the UnVote method.
https://github.com/CityOfZion/neo3-boa/blob/fee5dd8a3a54b0ba2c702082e08efa8c274f1865/boa3_test/test_sc/native_test/neo/Vote.py#L1-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/fee5dd8a3a54b0ba2c702082e08efa8c274f1865/boa3_test/tests/compiler_tests/test_native/test_neo.py#L141-L202
**Platform:**
=> Implement NEO Native Contract method `unVote`

boa3/neo/__init__.py, boa3_test/examples/nep11_non_divisible.py, boa3_test/tests/examples_tests/test_nep11_non_divisible.py
Replaced the old NEP-11 example with GhostMarket one, also added GhostMarket tests and some other tests
**Platform:**
=> Replace NEP-11 example with GhostMarket template

boa3/model/builtin/interop/storage/storagedeletemethod.py
It was already done before, just removed some code
=> Refactor StorageDeleteMethod

boa3/model/builtin/method/printboolmethod.py, boa3/model/builtin/method/printbytestringmethod.py, boa3/model/builtin/method/printintmethod.py, boa3/model/builtin/method/printmethod.py, boa3/model/builtin/method/printsequencemethod.py, boa3_test/examples/nep11_non_divisible.py, boa3_test/test_sc/built_in_methods_test/PrintBool.py, boa3_test/test_sc/built_in_methods_test/PrintBytes.py, boa3_test/tests/compiler_tests/test_builtin_method.py
Improved the `print` output for better visualization of logs
https://github.com/CityOfZion/neo3-boa/blob/a64e8e5ef73da7c163b24b4ea7f249ba2a25750e/boa3_test/test_sc/built_in_methods_test/PrintInt.py#L4-L6
https://github.com/CityOfZion/neo3-boa/blob/a64e8e5ef73da7c163b24b4ea7f249ba2a25750e/boa3_test/test_sc/built_in_methods_test/PrintBool.py#L4-L6
https://github.com/CityOfZion/neo3-boa/blob/a64e8e5ef73da7c163b24b4ea7f249ba2a25750e/boa3_test/test_sc/built_in_methods_test/PrintBytes.py#L4-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/a64e8e5ef73da7c163b24b4ea7f249ba2a25750e/boa3_test/tests/compiler_tests/test_builtin_method.py#L573-L625
**Platform:**
=> Implement print with other values

boa3/compiler/codegenerator/codegenerator.py, boa3_test/examples/nep11_non_divisible.py, boa3_test/tests/compiler_tests/test_constant.py
Included the conversion of literal sequences and dictionaries in the code generator
https://github.com/CityOfZion/neo3-boa/blob/f4d3fa6d8990b1cfd38e3efbdff57b8ad0a3e6c4/boa3_test/tests/compiler_tests/test_constant.py#L146-L158
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f4d3fa6d8990b1cfd38e3efbdff57b8ad0a3e6c4/boa3_test/tests/compiler_tests/test_constant.py#L146-L418
**Platform:**
=> Convert Literal Collections

.circleci/config.yml, boa3_test/tests/boa_test.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py, boa3_test/tests/test_classes/testengine.py
Changed TestEngine interface to support the calling script hash feature
https://github.com/CityOfZion/neo3-boa/blob/1479d4e6ccd822f92e29c054ef9bc3f58d251e85/boa3_test/tests/boa_test.py#L285-L287
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/1479d4e6ccd822f92e29c054ef9bc3f58d251e85/boa3_test/tests/compiler_tests/test_interop/test_runtime.py#L298-L315
=> Test Engine calling scripthash support

boa3/neo/contracts/neffile.py, boa3/neo3/contracts/nef.py, boa3_test/tests/compiler_tests/test_file_generation.py, boa3_test/tests/neo_tests/smart_contract/test_neffile.py
Updated NEF generation to handle method tokens. The usage of method tokens will be implemented in others pull requests.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/44a5fb3aa0fc24393ffd38bf29e9219f3cb57670/boa3_test/tests/compiler_tests/test_file_generation.py#L41-L67
=> Create and use method tokens in the NEF generation

boa3/compiler/codegenerator/codegeneratorvisitor.py, boa3_test/test_sc/variable_test/InnerObjectVariableAccess.py, boa3_test/tests/compiler_tests/test_variable.py
Fixed the execution of inner object variables access
https://github.com/CityOfZion/neo3-boa/blob/bfb852a90d55e44917354c5263b53945496fd790/boa3_test/test_sc/variable_test/InnerObjectVariableAccess.py#L12-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bfb852a90d55e44917354c5263b53945496fd790/boa3_test/tests/compiler_tests/test_variable.py#L706-L712
**Platform:**
=> Inner variables are not being accessed as expected

boa3_test/tests/compiler_tests/test_metadata.py, boa3_test/tests/test_classes/contract/neopermissionsstruct.py
A clear and concise description of what you made in this change.
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/0048db2b3c9f864722bc67648e7a9e91cd9f0a4b/boa3_test/tests/compiler_tests/test_metadata.py#L360-L387
**Platform:**
=> Implement Permissions to the test classes

boa3/compiler/codegenerator/codegenerator.py, boa3_test/test_sc/class_test/UserClassWithDeployMethod.py, boa3_test/tests/compiler_tests/test_class.py, boa3_test/tests/compiler_tests/test_function.py
The contract failed to deploy in this case
https://github.com/CityOfZion/neo3-boa/blob/596daaf8a83cdd8385da77405821e65e0940f5ab/boa3_test/test_sc/class_test/UserClassWithDeployMethod.py#L8-L26
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/596daaf8a83cdd8385da77405821e65e0940f5ab/boa3_test/tests/compiler_tests/test_class.py#L506-L511
**Platform:**
=> Invalid contract is generated when using classes and setting _deploy method in the same smart contract

.circleci/config.yml, boa3_test/tests/compiler_tests/test_interop/test_blockchain.py, boa3_test/tests/compiler_tests/test_native/test_ledger.py, boa3_test/tests/test_classes/block.py
Changed the tests to support the update on Test Engine
=> Make Test Engine return block hashes

boa3_test/examples/nep17.py, boa3_test/test_sc/contract_interface_test/ContractInterfaceCodeOptimization.py, boa3_test/test_sc/contract_interface_test/Nep17Interface.py, boa3_test/test_sc/contract_interface_test/Nep17InterfaceWithDisplayName.py
https://app.clickup.com/t/32k46pf
Now takes into account that `from` can be `null`
**Tests**
See clickup
=> fix OnNep17Payment of NEP17 example 

.circleci/config.yml, boa3/model/builtin/interop/contract/getgasscripthashmethod.py, boa3/model/builtin/interop/contract/getneoscripthashmethod.py, boa3/model/builtin/native/oracleclass.py, boa3/neo3/network/payloads/verification.py, boa3_test/tests/boa_test.py, boa3_test/tests/compiler_tests/test_interop/test_blockchain.py, boa3_test/tests/compiler_tests/test_interop/test_runtime.py, boa3_test/tests/compiler_tests/test_native/test_ledger.py, boa3_test/tests/test_classes/signer.py, boa3_test/tests/test_classes/testengine.py, boa3_test/tests/test_classes/witnessscope.py
Update interface to support TestEngine changes
=> Add WitnessScope in the TestEngine execution arguments

boa3/builtin/nativecontract/contractmanagement.py, boa3/model/builtin/native/contract_management/__init__.py, boa3/model/builtin/native/contract_management/hasmethod.py, boa3/model/builtin/native/contractmanagementclass.py, boa3_test/test_sc/native_test/contractmanagement/HasMethod.py, boa3_test/tests/compiler_tests/test_native/test_contract_management.py
Implemented ContractManagement native contract method `hasMethod`
https://github.com/CityOfZion/neo3-boa/blob/3e26b30a03f8629212a2b24d5607df94b04832cd/boa3/builtin/nativecontract/contractmanagement.py#L37-L52
https://github.com/CityOfZion/neo3-boa/blob/3e26b30a03f8629212a2b24d5607df94b04832cd/boa3_test/test_sc/native_test/contractmanagement/HasMethod.py#L3-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3e26b30a03f8629212a2b24d5607df94b04832cd/boa3_test/tests/compiler_tests/test_native/test_contract_management.py#L57-L71
**Platform:**
=> Implement ContractManagement Native Contract method `hasMethod`

README.md
Update README with more complete instructions of how to install TestEngine and use it to run the unit tests
=> Improve testengine installation instructions

.circleci/config.yml, .coveragerc, .gitignore, README.md, requirements_dev.txt
Included code coverage report in the test process in CircleCI
=> Add code coverage to build process

boa3/model/builtin/method/printboolmethod.py, boa3/model/builtin/method/printclassmethod.py, boa3/model/builtin/method/printmethod.py, boa3/model/builtin/method/printsequencemethod.py, boa3/model/type/classes/userclass.py, boa3_test/test_drive/testrunner/neo_test_runner.py, boa3_test/test_sc/built_in_methods_test/PrintClass.py, boa3_test/test_sc/built_in_methods_test/PrintList.py, boa3_test/tests/boa_test.py, boa3_test/tests/compiler_tests/test_builtin_method.py
Support to printing sequences (`list`, `tuple`, `dict`) and user-implemented classes.
https://github.com/CityOfZion/neo3-boa/blob/f08065b0f21b3e1eef52b4a6c5a6163d7fd54dd0/boa3_test/test_sc/built_in_methods_test/PrintClass.py#L4-L13
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/f08065b0f21b3e1eef52b4a6c5a6163d7fd54dd0/boa3_test/tests/compiler_tests/test_builtin_method.py#L888-L936
**Platform:**
=> Improve print logging messages

boa3_test/test_drive/model/network/payloads/testblock.py, boa3_test/test_drive/neoxp/command/neoexpresscommand/show/__init__.py, boa3_test/test_drive/neoxp/command/neoexpresscommand/show/block.py, boa3_test/test_drive/neoxp/model/neoxpconfig.py, boa3_test/test_drive/neoxp/utils.py, boa3_test/test_drive/testrunner/blockchain/block.py, boa3_test/test_drive/testrunner/neo_test_runner.py, boa3_test/tests/compiler_tests/test_interop/test_blockchain.py, boa3_test/tests/compiler_tests/test_native/test_ledger.py, boa3_test/tests/test_classes/block.py
Changed the execution tests of the compiled smart contracts related to blocks to use TestRunner instead of TestEngine
**Tests**
=> Refactor block unit tests to use test runner

boa3_test/examples/amm.py, boa3_test/examples/wrapped_gas.py, boa3_test/examples/wrapped_neo.py, boa3_test/test_drive/model/invoker/neoinvoke.py, boa3_test/test_drive/neoxp/batch.py, boa3_test/test_drive/neoxp/command/neoexpresscommand/contract/__init__.py, boa3_test/test_drive/neoxp/command/neoexpresscommand/contract/invoke.py, boa3_test/test_drive/neoxp/command/neoxp_contract.py, boa3_test/test_drive/testrunner/neo_test_runner.py, boa3_test/test_drive/testrunner/utils.py, boa3_test/tests/compiler_tests/test_bytes.py, boa3_test/tests/examples_tests/test_amm.py, boa3_test/tests/examples_tests/test_wrapped_neo.py
Changed the execution tests of AMM example to use TestRunner instead of TestEngine
**Tests**
=> Refactor AMM unit tests to use Test Runner

boa3_test/examples/auxiliary_contracts/update_contract.py, boa3_test/examples/nep5.py, boa3_test/examples/update_contract.py, boa3_test/tests/examples_tests/test_hello_world.py, boa3_test/tests/examples_tests/test_nep5.py, boa3_test/tests/examples_tests/test_update_contract.py
Adapted the smart contracts and changed the unit test on:
- test_hello_world.py
- test_nep5.py and nep5.py
- test_update_contract.py and update_contract.py 
**Platform:**
=> Refactor unit tests of simpler examples to use Test Runner

boa3_test/examples/ico.py, boa3_test/tests/boa_test.py, boa3_test/tests/compiler_tests/test_variable.py, boa3_test/tests/examples_tests/test_ico.py, boa3_test/tests/run_unit_tests.py
Changed the execution tests of the ICO example to use TestRunner instead of TestEngine
**Tests**
=> Refactor ICO unit tests to use Test Runner

boa3_test/examples/wrapped_neo.py, boa3_test/tests/examples_tests/test_wrapped_neo.py
A clear and concise description of what you made in this change.
**Tests**
Reran the test in test_wrapped_neo.py
**Platform:**
=> Refactor wrapped neo unit tests to use Test Runner

boa3_test/examples/htlc.py, boa3_test/test_drive/neoxp/batch.py, boa3_test/test_drive/neoxp/command/neoxp.py, boa3_test/test_drive/testrunner/neo_test_runner.py, boa3_test/tests/examples_tests/test_htlc.py
Part of an overall refactoring.
Changed the execution tests of the HTLC example to use TestRunner instead of TestEngine. Also did some small changes to the smart contract
**Tests**
Reran the test in test_htlc.py
**Platform:**
=> Refactor HTLC unit tests to use Test Runner

boa3_test/tests/examples_tests/test_ico.py
The tests were checking the "transfer" event instead of the "Transfer" event,
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/4d3f9d2bff8cdd87bbca12d7208411c463532bef/boa3_test/tests/examples_tests/test_ico.py#L373-L395
**Platform:**
=> ICO unit test is checking the wrong event and expecting an old behaviour

boa3/internal/compiler/codegenerator/codegenerator.py, boa3/internal/model/builtin/method/maxbytestringmethod.py, boa3/internal/model/builtin/method/maxmethod.py
Refactored `max` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/3eb4a7e1d31f078dd7d9e552d3ccc239a09fa52d/boa3_test/test_sc/built_in_methods_test/MaxStrMoreArguments.py#L4-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3eb4a7e1d31f078dd7d9e552d3ccc239a09fa52d/boa3_test/tests/compiler_tests/test_builtin_method.py#L1194-L1343
**Platform:**
=> Refactor max implementation to improve readability

boa3/internal/neo3/network/payloads/verification.py
Removed unused methods from WitnessRuleAction and WitnessScope.
**Platform:**
=> Unresolved reference 'WitnessConditionType.to_csharp_string

boa3/internal/compiler/codegenerator/codegenerator.py, boa3/internal/compiler/codegenerator/stackmemento.py, boa3/internal/model/builtin/classmethod/lowermethod.py, boa3/internal/model/builtin/method/listbytesstringmethod.py, boa3/internal/model/builtin/method/printclassmethod.py, boa3/internal/model/operation/binary/arithmetic/strbytesmultiplication.py, boa3/internal/neo/vm/opcode/OpcodeHelper.py
Refactored `lower` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/12aa115d6258a0f4488c7a350b5243362b6422da/boa3_test/test_sc/string_test/LowerStringMethod.py#L4-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/12aa115d6258a0f4488c7a350b5243362b6422da/boa3_test/tests/compiler_tests/test_bytes.py#L1161-L1185
https://github.com/CityOfZion/neo3-boa/blob/12aa115d6258a0f4488c7a350b5243362b6422da/boa3_test/tests/compiler_tests/test_string.py#L912-L941
**Platform:**
=> Refactor lower implementation to improve readability

boa3/internal/model/builtin/classmethod/copydictmethod.py
Refactored `dict.copy` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/bf71b7230d6747b99ed071251e5d83aa503497c6/boa3_test/test_sc/dict_test/DictCopy.py#L6-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/bf71b7230d6747b99ed071251e5d83aa503497c6/boa3_test/tests/compiler_tests/test_dict.py#L746-L791
**Platform:**
=> Refactor dict.copy implementation to improve readability

boa3/internal/compiler/codegenerator/codegenerator.py, boa3/internal/model/builtin/method/intbytestringmethod.py, boa3/internal/model/builtin/method/intintmethod.py, boa3_test/tests/compiler_tests/test_string.py
Refactored `int` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/cea5b51b0935b3736d557a6c7483f063ac4fc93d/boa3_test/test_sc/built_in_methods_test/IntStr.py#L1-L7
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/cea5b51b0935b3736d557a6c7483f063ac4fc93d/boa3_test/tests/compiler_tests/test_builtin_method.py#L2170-L2397
**Platform:**
=> Refactor int constructor implementation to improve readability

boa3/internal/model/builtin/classmethod/joinmethod.py
Refactored `join` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/c7168432e2dd2196178b1ee1525ea83641894c4a/boa3_test/test_sc/string_test/JoinStringMethodWithDictionary.py#L1-L8
https://github.com/CityOfZion/neo3-boa/blob/c7168432e2dd2196178b1ee1525ea83641894c4a/boa3_test/test_sc/string_test/JoinStringMethodWithSequence.py#L1-L8
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/c7168432e2dd2196178b1ee1525ea83641894c4a/boa3_test/tests/compiler_tests/test_string.py#L1203-L1257
**Platform:**
=> Refactor join implementation to improve readability

boa3/internal/compiler/codegenerator/stackmemento.py, boa3/internal/model/builtin/classmethod/countsequencegenericmethod.py, boa3/internal/model/builtin/classmethod/countsequencemethod.py, boa3/internal/model/builtin/classmethod/countstrmethod.py, boa3/internal/neo3/vm/vmstate.py
Refactored `count` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/d23e08e2b3daa768aa7f41458b696f3ad4721874/boa3_test/test_sc/built_in_methods_test/CountListAnyType.py#L6-L16
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/d23e08e2b3daa768aa7f41458b696f3ad4721874/boa3_test/tests/compiler_tests/test_builtin_method.py#L1692-L2166
**Platform:**
=> Refactor count implementation to improve readability

boa3/internal/cli_commands/compile_command.py, boa3_test/test_cli/smart_contract_folder/smart_contract.py, boa3_test/tests/cli_tests/test_compile.py
Added CLI tests on neo3-boa
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/982065cc0c13e2e25da481e052271fe9f18328ce/boa3_test/tests/cli_tests/test_compile.py#L1-L160
**Platform:**
=> Add CLI tests

docs/migration-guide-v0.14.0.md
remove validation warning (after https://github.com/CityOfZion/neo3-boa/pull/1077)
=> remove obsolete warning

boa3/internal/model/builtin/classmethod/startswithmethod.py
Refactored `startswith` built-in method.
**Tests**
The previously written tests.
**Platform:**
=> Refactor startswith implementation to improve readability

boa3/internal/model/builtin/classmethod/uppermethod.py, boa3_test/tests/run_unit_tests.py
Refactored `upper` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/e2c75a8f9ea084b457d0dd585ade006378c1f78f/boa3_test/test_sc/string_test/UpperStringMethod.py#L4-L6
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/e2c75a8f9ea084b457d0dd585ade006378c1f78f/boa3_test/tests/compiler_tests/test_bytes.py#L1136-L1160
https://github.com/CityOfZion/neo3-boa/blob/e2c75a8f9ea084b457d0dd585ade006378c1f78f/boa3_test/tests/compiler_tests/test_string.py#L867-L897
**Platform:**
=> Refactor upper implementation to improve readability

boa3/internal/model/builtin/classmethod/removemethod.py
Refactored `list` `remove` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/57b4554b061890a79bcf55d3a678828a5a353ffc/boa3_test/test_sc/list_test/RemoveIntValue.py#L6-L10
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/57b4554b061890a79bcf55d3a678828a5a353ffc/boa3_test/tests/compiler_tests/test_list.py#L1787-L1843
**Platform:**
=> Refactor remove implementation to improve readability

boa3/internal/model/builtin/classmethod/insertmethod.py
Refactored `list` `insert` built-in method.
https://github.com/CityOfZion/neo3-boa/blob/816d918e6d51ef37edbe6dc5dc6330f28b4bedd4/boa3_test/test_sc/list_test/InsertAnyValue.py#L6-L9
**Tests**
https://github.com/CityOfZion/neo3-boa/blob/816d918e6d51ef37edbe6dc5dc6330f28b4bedd4/boa3_test/tests/compiler_tests/test_list.py#L1663-L1744
**Platform:**
=> Refactor insert implementation to improve readability

boa3/internal/model/builtin/classmethod/popdictdefaultmethod.py, boa3/internal/model/builtin/classmethod/popmethod.py, boa3/internal/model/builtin/classmethod/popsequencemethod.py, boa3_test/tests/compiler_tests/test_dict.py, boa3_test/tests/compiler_tests/test_list.py
Refactored `pop` built-in method.
**Platform:**
=> Refactor pop implementation to improve readability

boa3/internal/model/builtin/classmethod/isdigitmethod.py
Refactored `isdigit `built-in method.
**Platform:**
=> Refactor isdigit implementation to improve readability

boa3/internal/model/builtin/classmethod/stripmethod.py
Refactored `strip` built-in method.
**Platform:**
=> Refactor strip implementation to improve readability

boa3/internal/compiler/codegenerator/codegenerator.py, boa3/internal/compiler/codegenerator/codegeneratorvisitor.py, boa3/internal/neo/vm/opcode/Opcode.py, boa3/internal/neo/vm/opcode/OpcodeInfo.py, boa3_test/examples/amm.py, boa3_test/examples/ico.py, boa3_test/examples/nep11_non_divisible.py, boa3_test/tests/boa_test.py, boa3_test/tests/compiler_tests/test_assert.py
Added the ASSERTMSG Opcode on Neo3-boa.
**How to Reproduce & Tests**
It's not possible to run or test the Opcode yet, because the Neo version with this Opcode was not released yet. 
**Platform:**
=> support new ASSERTMSG opcode

boa3/builtin/interop/crypto/__init__.py, boa3/builtin/nativecontract/cryptolib.py, boa3/internal/model/builtin/interop/crypto/bls12381addmethod.py, boa3/internal/model/builtin/interop/crypto/bls12381deserializemethod.py, boa3/internal/model/builtin/interop/crypto/bls12381equalmethod.py, boa3/internal/model/builtin/interop/crypto/bls12381mulmethod.py, boa3/internal/model/builtin/interop/crypto/bls12381pairingmethod.py, boa3/internal/model/builtin/interop/crypto/bls12381serializemethod.py, boa3/internal/model/builtin/native/cryptolibclass.py, boa3_test/examples/amm.py, boa3_test/examples/ico.py, boa3_test/examples/nep11_non_divisible.py, boa3_test/test_sc/interop_test/crypto/Bls12381Add.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Add.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Deserialize.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Equal.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Mul.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Pairing.py, boa3_test/test_sc/native_test/cryptolib/Bls12381Serialize.py, boa3_test/tests/compiler_tests/test_assert.py, boa3_test/tests/compiler_tests/test_boa_builtin_method.py, boa3_test/tests/compiler_tests/test_interop/test_crypto.py, boa3_test/tests/compiler_tests/test_native/test_cryptolib.py
Changed some tests for the Neo 3.6 features that were implemented on other PRs, added some new tests, and changed the parameters of the BLS crypto methods
**Tests**
Also tested the 3.6 features on TestNet
**Platform:**
=> Create functional tests for Neo 3.6 features

boa3/internal/analyser/astoptimizer.py, boa3/internal/analyser/importanalyser.py, boa3/internal/analyser/moduleanalyser.py, boa3/internal/analyser/typeanalyser.py, boa3/internal/compiler/codegenerator/codegenerator.py, boa3/internal/compiler/codegenerator/codegeneratorvisitor.py, boa3/internal/compiler/filegenerator/filegenerator.py, boa3/internal/model/builtin/classmethod/indexmethod.py, boa3/internal/model/builtin/classmethod/lowermethod.py, boa3/internal/model/builtin/classmethod/uppermethod.py, boa3/internal/model/builtin/interop/contract/callmethod.py, boa3/internal/model/builtin/interop/contract/contractmanifest/contractmanifesttype.py, boa3/internal/model/builtin/method/bytearrayencodingmethod.py, boa3/internal/model/builtin/method/bytearraymethod.py, boa3/internal/model/builtin/method/strsplitmethod.py, boa3/internal/model/builtin/method/supermethod.py, boa3/internal/model/operation/binary/arithmetic/division.py, boa3/internal/model/type/classes/classinitmethoddefault.py, boa3/internal/model/type/classes/classtype.py, boa3/internal/model/type/classes/pythonclass.py, boa3/internal/model/type/classes/userclass.py, boa3_test/test_drive/model/network/payloads/signer.py, boa3_test/tests/compiler_tests/test_builtin_method.py, boa3_test/tests/compiler_tests/test_function.py, boa3_test/tests/compiler_tests/test_nep17_contract_interface.py, boa3_test/tests/compiler_tests/test_range.py, boa3_test/tests/compiler_tests/test_string.py, boa3_test/tests/test_classes/contract/neomanifeststruct.py, boa3_test/tests/test_classes/nativeaccountstate.py
Removed some TODO messages and added the task codes to the ones that remain
=> Check and do something about all "TODO" comments in code

boa3/internal/model/operation/binary/arithmetic/strbytesmultiplication.py, boa3_test/test_drive/utils.py, boa3_test/tests/boatestcase.py, boa3_test/tests/compiler_tests/test_arithmetic.py, boa3_test/tests/run_unit_tests.py
Created a TestCase clas to use features from boa_test_constructor on boa3 tests. 
Also refactored `test_arithmetic` to use this new class.
=> Implement the structure used on all boa unit tests working with BoaTestConstructor

boa3_test/tests/compiler_tests/test_union.py
Refactored `test_union` file to use `boatestconstructor` in place of `TestRunner` for unit testing.
=> CU-86a1huquw - Refactor test_union.py to use BoaTestConstructor

boa3_test/tests/compiler_tests/test_assert.py
Summary or solution description
Refactored `test_assert` file to use `boatestconstructor `in place of TestRunner for unit testing.
=> CU-86a1humxp - Refactor test_assert.py to use BoaTestConstructor

boa3_test/tests/boatestcase.py, boa3_test/tests/compiler_tests/test_file_generation.py
Refactored `test_file_generation` file to use `BoaTestCase` in place of `BoaTest` for unit testing.
=> Refactor test_file_generation.py to use BoaTestCase

boa3_test/tests/boatestcase.py, boa3_test/tests/compiler_tests/test_bytes.py
#1166 
Refactored the remaining tests from `test_bytes.py`
=> CU-86drpne27 - Refactor bytearray tests that result in a buffer in test_bytes.py to use BoaTestConstructor

boa3_test/tests/compiler_tests/test_native/test_policy.py
Refactored `test_native/test_policy.py `files to use `BoaTestCase `in place of `BoaTest `for unit testing.
=> Refactor test_native/test_policy.py to use BoaConstructor

.github/workflows/main.yml
This adds support to AI codereviewer, to add automated comments and suggestions to pull requests
=> #86drpnn0q - Add codereviewer to all projects being worked on

boa3_test/tests/boatestcase.py, boa3_test/tests/examples_tests/test_wrapped_neo.py
Rewrote `examples_tests/test_wrapped_neo.py` file so the tests are more efficient do test the `WrappedNeo` example contract using `BoaTestCase`
=> CU-86drpndam - Refactor example_tests/test_wrapped_neo.py to use BoaConstructor

boa3_test/tests/examples_tests/test_amm.py
Refactored `example_tests/test_amm.py` files to use `BoaTestCase `in place of `BoaTest `for unit testing.
=> CU-86drpnczu - Refactor example_tests/test_amm.py to use BoaConstructor

pyproject.toml
=> CU-86dtn4tfx - Fix python supported version by NeoBoa
